package validate

import (
	"fmt"
	"strings"

	validatepb "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	"buf.build/go/protovalidate"
	"google.golang.org/protobuf/proto"

	"github.com/sylphylabs/forge/errors"
	"github.com/sylphylabs/forge/middleware"
)

// ProtoValidateStream validates the initial request of a stream, once, before
// the handler runs.
//
// This suits server-streaming methods, where the client sends one request and
// then only receives. For client and bidirectional streaming the initial
// request is nil and nothing is validated — use [PerMessageProtoValidateStream]
// there.
func ProtoValidateStream() middleware.StreamMiddleware {
	return func(handler middleware.StreamHandler) middleware.StreamHandler {
		return func(request any, stream middleware.ServerStream) error {
			if request != nil {
				if err := validateMessage(request); err != nil {
					return err
				}
			}
			return handler(request, stream)
		}
	}
}

// PerMessageProtoValidateStream validates every message received on a stream.
//
// This suits client and bidirectional streaming, where each message is a
// separate input worth checking. A message that fails validation fails that
// RecvMsg with a BadRequest error and leaves the stream open, so the handler
// decides whether to continue or return. The initial request, when a method
// has one, is validated too.
func PerMessageProtoValidateStream() middleware.StreamMiddleware {
	return func(handler middleware.StreamHandler) middleware.StreamHandler {
		return func(request any, stream middleware.ServerStream) error {
			if request != nil {
				if err := validateMessage(request); err != nil {
					return err
				}
			}
			return handler(request, &validatingStream{ServerStream: stream})
		}
	}
}

// validatingStream validates every message it receives.
type validatingStream struct {
	middleware.ServerStream
}

func (s *validatingStream) RecvMsg(m any) error {
	if err := s.ServerStream.RecvMsg(m); err != nil {
		return err
	}
	return validateMessage(m)
}

// ErrValidation identifies a request rejected by a validator.
var ErrValidation = errors.MustDefine(errors.KindInvalidArgument, errors.Domain, "VALIDATION_FAILED")

// validateMessage runs protovalidate and the Validate() error hook.
func validateMessage(msg any) error {
	if m, ok := msg.(proto.Message); ok {
		if err := protovalidate.Validate(m); err != nil {
			return validationError(err)
		}
	}

	// Messages that implement Validate() error carry their own rules, whether
	// hand-written or generated by an external tool.
	if v, ok := msg.(validator); ok {
		if err := v.Validate(); err != nil {
			return validationError(err)
		}
	}
	return nil
}

// validationError converts a validator's error into a Forge error.
//
// protovalidate reports every rule that failed, so those become an aggregate
// error and reach the caller intact: a client can then show a user each bad
// field rather than only the first.
func validationError(err error) error {
	var validationErr *protovalidate.ValidationError
	if errors.As(err, &validationErr) {
		var v errors.Violations
		for _, violation := range validationErr.Violations {
			v.Add(fieldPath(violation), violation.Proto.GetMessage())
		}
		if !v.Empty() {
			return errors.FromError(v.Err(errors.KindInvalidArgument)).
				WithDomain(errors.Domain).
				WithReason("VALIDATION_FAILED").
				Msg(err.Error()).
				Wrap(err)
		}
	}
	return ErrValidation.Msg(err.Error()).Wrap(err)
}

// fieldPath renders the path of the field a violation refers to, as a dotted
// path a client can match against its own request ("user.email", "items[2]").
//
// The generated FieldPath String method renders the whole protobuf message,
// which names the field but is not usable by a caller.
func fieldPath(v *protovalidate.Violation) string {
	if v.Proto == nil {
		return ""
	}
	var b strings.Builder
	for _, element := range v.Proto.GetField().GetElements() {
		if b.Len() > 0 {
			b.WriteByte('.')
		}
		b.WriteString(element.GetFieldName())
		switch subscript := element.GetSubscript().(type) {
		case *validatepb.FieldPathElement_Index:
			fmt.Fprintf(&b, "[%d]", subscript.Index)
		case *validatepb.FieldPathElement_BoolKey:
			fmt.Fprintf(&b, "[%t]", subscript.BoolKey)
		case *validatepb.FieldPathElement_IntKey:
			fmt.Fprintf(&b, "[%d]", subscript.IntKey)
		case *validatepb.FieldPathElement_UintKey:
			fmt.Fprintf(&b, "[%d]", subscript.UintKey)
		case *validatepb.FieldPathElement_StringKey:
			fmt.Fprintf(&b, "[%q]", subscript.StringKey)
		}
	}
	return b.String()
}
