// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc         (unknown)
// source: internal/testdata/helloworld/helloworld.proto

package helloworld

import (
	context "context"
	http "github.com/sylphylabs/forge/transport/http"
	transcoding "github.com/sylphylabs/forge/transport/http/transcoding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the forge package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion5
const _ = transcoding.SupportPackageIsVersion1

const OperationGreeterSayHello = "/helloworld.Greeter/SayHello"

var _Greeter_SayHello0_HTTP_Path = transcoding.MustCompilePath("/helloworld/{name}", new(HelloRequest), transcoding.WithQueryParams())

const _GreeterHTTPMethodSet = 1

type GreeterHTTPServer interface {
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/helloworld/{name}", _Greeter_SayHello0_HTTP_Handler(srv))
}

func _Greeter_SayHello0_HTTP_Handler(srv GreeterHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHello)
		out, err := srv.SayHello(ctx, &in)
		if err != nil {
			return err
		}
		reply := out
		return ctx.JSON(200, transcoding.NewProtoJSON(reply))
	}
}

type GreeterHTTPClient interface {
	// SayHello Sends a greeting
	SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

// SayHello Sends a greeting
func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld/{name}"
	path, err := _Greeter_SayHello0_HTTP_Path.Build(in)
	if err != nil {
		return nil, err
	}
	opts = append([]http.CallOption{
		http.WithAccept("application/json"),
		http.WithOperation(OperationGreeterSayHello),
		http.WithPathTemplate(pattern),
	}, opts...)
	err = c.cc.Invoke(ctx, "GET", path, nil, transcoding.NewProtoJSON(&out), opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
