// Code generated by protoc-gen-go-middleware. DO NOT EDIT.
// versions:
// - protoc-gen-go-middleware v3.0.0
// - protoc                   v7.35.1
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	middleware "github.com/sylphylabs/forge/middleware"
	grpc "google.golang.org/grpc"
)

// GreeterMiddleware configures generated server middleware for helloworld.Greeter.
type GreeterMiddleware struct {
	Unary   []middleware.UnaryMiddleware
	Stream  []middleware.StreamMiddleware
	Methods GreeterMethodMiddleware
}

// GreeterMethodMiddleware configures middleware for individual RPC methods.
type GreeterMethodMiddleware struct {
	SayHello       []middleware.UnaryMiddleware
	SayHelloStream []middleware.StreamMiddleware
}

var _ [_GreeterHTTPMethodSet - 1]struct{}
var _ [1 - _GreeterHTTPMethodSet]struct{}

type _GreeterHTTPMiddlewareServer struct {
	GreeterHTTPServer
	handlerSayHello middleware.UnaryHandler
}

// WrapGreeterHTTPServer snapshots plan and composes every HTTP handler before registration.
func WrapGreeterHTTPServer(srv GreeterHTTPServer, plan GreeterMiddleware) (GreeterHTTPServer, error) {
	if srv == nil {
		return nil, fmt.Errorf("forge: nil Greeter HTTP server")
	}
	wrapped := &_GreeterHTTPMiddlewareServer{GreeterHTTPServer: srv}
	{
		middlewares := make([]middleware.UnaryMiddleware, 0, len(plan.Unary)+len(plan.Methods.SayHello))
		middlewares = append(middlewares, plan.Unary...)
		middlewares = append(middlewares, plan.Methods.SayHello...)
		handler, err := middleware.ComposeUnary(func(ctx context.Context, request any) (any, error) {
			typed, ok := request.(*HelloRequest)
			if !ok {
				return nil, fmt.Errorf("forge: helloworld.Greeter/SayHello HTTP request type %T, want *HelloRequest", request)
			}
			return srv.SayHello(ctx, typed)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping helloworld.Greeter/SayHello HTTP: %w", err)
		}
		wrapped.handlerSayHello = handler
	}
	return wrapped, nil
}

func (s *_GreeterHTTPMiddlewareServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	reply, err := s.handlerSayHello(ctx, request)
	if err != nil {
		return nil, err
	}
	typed, ok := reply.(*HelloReply)
	if !ok {
		return nil, fmt.Errorf("forge: helloworld.Greeter/SayHello HTTP reply type %T, want *HelloReply", reply)
	}
	return typed, nil
}

type _GreeterGRPCMiddlewareServer struct {
	GreeterServer
	handlerSayHello       middleware.UnaryHandler
	handlerSayHelloStream middleware.StreamHandler
}

type _Greeter_SayHelloStreamGRPCMiddlewareStreamKey struct{}
type _Greeter_SayHelloStreamGRPCMiddlewareStream struct {
	grpc.ServerStream
	ctx context.Context
}

func (s *_Greeter_SayHelloStreamGRPCMiddlewareStream) Context() context.Context { return s.ctx }

type _Greeter_SayHelloStreamGRPCMiddlewareStreamTyped struct {
	grpc.ServerStream
	stream middleware.ServerStream
}

func (s *_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped) Context() context.Context {
	return s.stream.Context()
}
func (s *_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped) SendMsg(message any) error {
	return s.stream.SendMsg(message)
}
func (s *_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped) RecvMsg(message any) error {
	return s.stream.RecvMsg(message)
}
func (s *_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped) Send(message *HelloReply) error {
	return s.stream.SendMsg(message)
}
func (s *_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped) Recv() (*HelloRequest, error) {
	message := new(HelloRequest)
	if err := s.stream.RecvMsg(message); err != nil {
		return nil, err
	}
	return message, nil
}

// WrapGreeterGRPCServer snapshots plan and composes every gRPC handler before registration.
func WrapGreeterGRPCServer(srv GreeterServer, plan GreeterMiddleware) (GreeterServer, error) {
	if srv == nil {
		return nil, fmt.Errorf("forge: nil Greeter gRPC server")
	}
	wrapped := &_GreeterGRPCMiddlewareServer{GreeterServer: srv}
	{
		middlewares := make([]middleware.UnaryMiddleware, 0, len(plan.Unary)+len(plan.Methods.SayHello))
		middlewares = append(middlewares, plan.Unary...)
		middlewares = append(middlewares, plan.Methods.SayHello...)
		handler, err := middleware.ComposeUnary(func(ctx context.Context, request any) (any, error) {
			typed, ok := request.(*HelloRequest)
			if !ok {
				return nil, fmt.Errorf("forge: helloworld.Greeter/SayHello gRPC request type %T, want *HelloRequest", request)
			}
			return srv.SayHello(ctx, typed)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping helloworld.Greeter/SayHello gRPC: %w", err)
		}
		wrapped.handlerSayHello = handler
	}
	{
		middlewares := make([]middleware.StreamMiddleware, 0, len(plan.Stream)+len(plan.Methods.SayHelloStream))
		middlewares = append(middlewares, plan.Stream...)
		middlewares = append(middlewares, plan.Methods.SayHelloStream...)
		handler, err := middleware.ComposeStream(func(request any, stream middleware.ServerStream) error {
			native, ok := stream.Context().Value(_Greeter_SayHelloStreamGRPCMiddlewareStreamKey{}).(grpc.ServerStream)
			if !ok {
				return fmt.Errorf("forge: helloworld.Greeter/SayHelloStream gRPC lost native stream")
			}
			typedStream := &_Greeter_SayHelloStreamGRPCMiddlewareStreamTyped{ServerStream: native, stream: stream}
			if request != nil {
				return fmt.Errorf("forge: helloworld.Greeter/SayHelloStream gRPC initial request type %T, want nil", request)
			}
			return srv.SayHelloStream(typedStream)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping helloworld.Greeter/SayHelloStream gRPC: %w", err)
		}
		wrapped.handlerSayHelloStream = handler
	}
	return wrapped, nil
}

func (s *_GreeterGRPCMiddlewareServer) SayHello(ctx context.Context, request *HelloRequest) (*HelloReply, error) {
	reply, err := s.handlerSayHello(ctx, request)
	if err != nil {
		return nil, err
	}
	typed, ok := reply.(*HelloReply)
	if !ok {
		return nil, fmt.Errorf("forge: helloworld.Greeter/SayHello gRPC reply type %T, want *HelloReply", reply)
	}
	return typed, nil
}

func (s *_GreeterGRPCMiddlewareServer) SayHelloStream(stream Greeter_SayHelloStreamServer) error {
	base := &_Greeter_SayHelloStreamGRPCMiddlewareStream{ServerStream: stream, ctx: context.WithValue(stream.Context(), _Greeter_SayHelloStreamGRPCMiddlewareStreamKey{}, grpc.ServerStream(stream))}
	return s.handlerSayHelloStream(nil, base)
}
