// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v7.35.1
// source: helloworld.proto

package helloworld

import (
	context "context"
	http "github.com/openkratos/kratos/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion5

const OperationGreeterSayHello = "/helloworld.Greeter/SayHello"

var _Greeter_SayHello0_HTTP_Path = http.MustCompilePath("/helloworld/{name}", new(HelloRequest), http.WithQueryParams())

type GreeterHTTPServer interface {
	// SayHello Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterHTTPServer(s *http.Server, srv GreeterHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/helloworld/{name}", _Greeter_SayHello0_HTTP_Handler(s, srv))
}

func _Greeter_SayHello0_HTTP_Handler(s *http.Server, srv GreeterHTTPServer) func(ctx http.Context) error {
	h := s.WrapMiddleware(OperationGreeterSayHello, func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.SayHello(ctx, req.(*HelloRequest))
	})
	return func(ctx http.Context) error {
		var in HelloRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGreeterSayHello)
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloReply)
		return ctx.JSON(200, http.NewProtoJSON(reply))
	}
}

type GreeterHTTPClient interface {
	// SayHello Sends a greeting
	SayHello(ctx context.Context, req *HelloRequest, opts ...http.CallOption) (rsp *HelloReply, err error)
}

type GreeterHTTPClientImpl struct {
	cc *http.Client
}

func NewGreeterHTTPClient(client *http.Client) GreeterHTTPClient {
	return &GreeterHTTPClientImpl{client}
}

// SayHello Sends a greeting
func (c *GreeterHTTPClientImpl) SayHello(ctx context.Context, in *HelloRequest, opts ...http.CallOption) (*HelloReply, error) {
	var out HelloReply
	pattern := "/helloworld/{name}"
	path, err := _Greeter_SayHello0_HTTP_Path.Build(in)
	if err != nil {
		return nil, err
	}
	opts = append([]http.CallOption{
		http.Accept("application/json"),
		http.Operation(OperationGreeterSayHello),
		http.PathTemplate(pattern),
	}, opts...)
	err = c.cc.Invoke(ctx, "GET", path, nil, http.NewProtoJSON(&out), opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
