// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sylphy/message/v1/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscription declares that an RPC is served by the asynchronous message
// transport rather than by a request/response transport.
//
// The RPC's response type is ignored: proto requires every rpc to name one,
// but a delivered message has no reply channel to carry it.
type Subscription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// destination names what the handler subscribes to. It is a default, not a
	// constant: RegisterXMessageServer accepts overrides because the same
	// contract is deployed against per-environment prefixes.
	//
	// What the string means is the adapter's to decide, and adapters do not
	// agree. For Kafka, MQTT, and core NATS it is the wire address — a topic
	// name, topic filter, or subject, each with its own separator and wildcard
	// grammar. For RabbitMQ and NATS JetStream it is a logical name resolved
	// through the adapter's own binding table to a pre-provisioned queue or
	// consumer, and never reaches the broker at all.
	//
	// So this field is deliberately not a portable topic pattern. Wildcards work
	// where the adapter's broker defines them, and are declared in the adapter's
	// bindings where it does not. An adapter that cannot honour a destination
	// rejects it when the subscription is registered, rather than silently
	// receiving no messages. See docs/adr/0015.
	Destination   string `protobuf:"bytes,1,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_sylphy_message_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_message_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_sylphy_message_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

var file_sylphy_message_v1_message_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Subscription)(nil),
		Field:         500201,
		Name:          "sylphy.message.v1.subscribe",
		Tag:           "bytes,500201,opt,name=subscribe",
		Filename:      "sylphy/message/v1/message.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sylphy.message.v1.Subscription subscribe = 500201;
	E_Subscribe = &file_sylphy_message_v1_message_proto_extTypes[0]
)

var File_sylphy_message_v1_message_proto protoreflect.FileDescriptor

const file_sylphy_message_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1fsylphy/message/v1/message.proto\x12\x11sylphy.message.v1\x1a google/protobuf/descriptor.proto\"0\n" +
	"\fSubscription\x12 \n" +
	"\vdestination\x18\x01 \x01(\tR\vdestination:_\n" +
	"\tsubscribe\x12\x1e.google.protobuf.MethodOptions\x18\xe9\xc3\x1e \x01(\v2\x1f.sylphy.message.v1.SubscriptionR\tsubscribeBT\n" +
	"\x1ccom.github.sylphy.message.v1P\x01Z2github.com/sylphylabs/forge/api/message/v1;messageb\x06proto3"

var (
	file_sylphy_message_v1_message_proto_rawDescOnce sync.Once
	file_sylphy_message_v1_message_proto_rawDescData []byte
)

func file_sylphy_message_v1_message_proto_rawDescGZIP() []byte {
	file_sylphy_message_v1_message_proto_rawDescOnce.Do(func() {
		file_sylphy_message_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sylphy_message_v1_message_proto_rawDesc), len(file_sylphy_message_v1_message_proto_rawDesc)))
	})
	return file_sylphy_message_v1_message_proto_rawDescData
}

var file_sylphy_message_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sylphy_message_v1_message_proto_goTypes = []any{
	(*Subscription)(nil),               // 0: sylphy.message.v1.Subscription
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_sylphy_message_v1_message_proto_depIdxs = []int32{
	1, // 0: sylphy.message.v1.subscribe:extendee -> google.protobuf.MethodOptions
	0, // 1: sylphy.message.v1.subscribe:type_name -> sylphy.message.v1.Subscription
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sylphy_message_v1_message_proto_init() }
func file_sylphy_message_v1_message_proto_init() {
	if File_sylphy_message_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sylphy_message_v1_message_proto_rawDesc), len(file_sylphy_message_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_sylphy_message_v1_message_proto_goTypes,
		DependencyIndexes: file_sylphy_message_v1_message_proto_depIdxs,
		MessageInfos:      file_sylphy_message_v1_message_proto_msgTypes,
		ExtensionInfos:    file_sylphy_message_v1_message_proto_extTypes,
	}.Build()
	File_sylphy_message_v1_message_proto = out.File
	file_sylphy_message_v1_message_proto_goTypes = nil
	file_sylphy_message_v1_message_proto_depIdxs = nil
}
