package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	errorapi "github.com/sylphylabs/forge/api/errors/v1"
	"github.com/sylphylabs/forge/cmd/internal/generator"
)

const (
	errorsPackage = protogen.GoImportPath("github.com/sylphylabs/forge/errors")
	fmtPackage    = protogen.GoImportPath("fmt")
)

type errorFile struct {
	wrappers []*errorWrapper
}

func analyzeErrorFile(file *protogen.File) (*errorFile, error) {
	facts := new(errorFile)
	for _, enum := range file.Enums {
		wrapper, err := analyzeErrorEnum(file, enum)
		if err != nil {
			return nil, err
		}
		if len(wrapper.Errors) != 0 {
			facts.wrappers = append(facts.wrappers, wrapper)
		}
	}
	return facts, nil
}

func analyzeErrorEnum(file *protogen.File, enum *protogen.Enum) (*errorWrapper, error) {
	code := int(proto.GetExtension(enum.Desc.Options(), errorapi.E_DefaultCode).(int32))
	if code < 0 || code > 600 {
		return nil, fmt.Errorf("proto %q enum %s: default_code %d is outside [0, 600]", file.Desc.Path(), enum.Desc.FullName(), code)
	}
	wrapper := new(errorWrapper)
	for _, value := range enum.Values {
		enumCode := code
		if proto.HasExtension(value.Desc.Options(), errorapi.E_Code) {
			enumCode = int(proto.GetExtension(value.Desc.Options(), errorapi.E_Code).(int32))
		}
		if enumCode < 0 || enumCode > 600 {
			return nil, fmt.Errorf("proto %q enum value %s: code %d is outside [0, 600]", file.Desc.Path(), value.Desc.FullName(), enumCode)
		}
		if enumCode == 0 {
			continue
		}

		comment := value.Comments.Leading.String()
		if comment == "" {
			comment = value.Comments.Trailing.String()
		}
		wrapper.Errors = append(wrapper.Errors, &errorInfo{
			Name:       string(enum.Desc.Name()),
			Value:      string(value.Desc.Name()),
			CamelValue: case2Camel(string(value.Desc.Name())),
			HTTPCode:   enumCode,
			Comment:    comment,
			HasComment: comment != "",
		})
	}
	return wrapper, nil
}

// generateErrorFile analyzes and emits one file for focused tests.
func generateErrorFile(gen *protogen.Plugin, file *protogen.File) (*protogen.GeneratedFile, error) {
	facts, err := analyzeErrorFile(file)
	if err != nil {
		return nil, err
	}
	return emitErrorFile(gen, file, facts)
}

func emitErrorFile(gen *protogen.Plugin, file *protogen.File, facts *errorFile) (*protogen.GeneratedFile, error) {
	if len(facts.wrappers) == 0 {
		return nil, nil
	}
	filename := file.GeneratedFilenamePrefix + "_errors.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-errors. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-errors %s", generator.Release))
	g.P("// - protoc               ", generator.ProtocVersion(gen))
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	g.QualifiedGoIdent(fmtPackage.Ident(""))
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the Forge package it is being compiled against.")
	g.P("const _ = ", errorsPackage.Ident("SupportPackageIsVersion1"))
	g.P()
	for _, wrapper := range facts.wrappers {
		source, err := wrapper.execute()
		if err != nil {
			return nil, fmt.Errorf("proto %q: render errors: %w", file.Desc.Path(), err)
		}
		g.P(source)
	}
	return g, nil
}

func case2Camel(name string) string {
	if !strings.Contains(name, "_") {
		return titleProtoIdentifier(name)
	}
	strs := strings.Split(name, "_")
	words := make([]string, 0, len(strs))
	for _, w := range strs {
		words = append(words, titleProtoIdentifier(w))
	}

	return strings.Join(words, "")
}

// Protobuf identifiers are ASCII, so language-aware title casing is unnecessary.
func titleProtoIdentifier(word string) string {
	if word == "" {
		return ""
	}
	if word == strings.ToUpper(word) {
		word = strings.ToLower(word)
	}
	return strings.ToUpper(word[:1]) + word[1:]
}
