// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: internal/testdata/orderevents/orderevents.proto

package orderevents

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderEvents_OnOrderCreated_FullMethodName = "/orderevents.OrderEvents/OnOrderCreated"
	OrderEvents_OnOrderShipped_FullMethodName = "/orderevents.OrderEvents/OnOrderShipped"
	OrderEvents_OnOrderAudited_FullMethodName = "/orderevents.OrderEvents/OnOrderAudited"
)

// OrderEventsClient is the client API for OrderEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The order event consumer definition.
type OrderEventsClient interface {
	// consumes a newly created order.
	OnOrderCreated(ctx context.Context, in *OrderCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// consumes a shipped order.
	OnOrderShipped(ctx context.Context, in *OrderShipped, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// has no subscribe annotation and is therefore not bound to any destination.
	OnOrderAudited(ctx context.Context, in *OrderCreated, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type orderEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderEventsClient(cc grpc.ClientConnInterface) OrderEventsClient {
	return &orderEventsClient{cc}
}

func (c *orderEventsClient) OnOrderCreated(ctx context.Context, in *OrderCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderEvents_OnOrderCreated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderEventsClient) OnOrderShipped(ctx context.Context, in *OrderShipped, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderEvents_OnOrderShipped_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderEventsClient) OnOrderAudited(ctx context.Context, in *OrderCreated, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OrderEvents_OnOrderAudited_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderEventsServer is the server API for OrderEvents service.
// All implementations must embed UnimplementedOrderEventsServer
// for forward compatibility.
//
// The order event consumer definition.
type OrderEventsServer interface {
	// consumes a newly created order.
	OnOrderCreated(context.Context, *OrderCreated) (*emptypb.Empty, error)
	// consumes a shipped order.
	OnOrderShipped(context.Context, *OrderShipped) (*emptypb.Empty, error)
	// has no subscribe annotation and is therefore not bound to any destination.
	OnOrderAudited(context.Context, *OrderCreated) (*emptypb.Empty, error)
	mustEmbedUnimplementedOrderEventsServer()
}

// UnimplementedOrderEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderEventsServer struct{}

func (UnimplementedOrderEventsServer) OnOrderCreated(context.Context, *OrderCreated) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnOrderCreated not implemented")
}
func (UnimplementedOrderEventsServer) OnOrderShipped(context.Context, *OrderShipped) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnOrderShipped not implemented")
}
func (UnimplementedOrderEventsServer) OnOrderAudited(context.Context, *OrderCreated) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method OnOrderAudited not implemented")
}
func (UnimplementedOrderEventsServer) mustEmbedUnimplementedOrderEventsServer() {}
func (UnimplementedOrderEventsServer) testEmbeddedByValue()                     {}

// UnsafeOrderEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderEventsServer will
// result in compilation errors.
type UnsafeOrderEventsServer interface {
	mustEmbedUnimplementedOrderEventsServer()
}

func RegisterOrderEventsServer(s grpc.ServiceRegistrar, srv OrderEventsServer) {
	// If the following call panics, it indicates UnimplementedOrderEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderEvents_ServiceDesc, srv)
}

func _OrderEvents_OnOrderCreated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEventsServer).OnOrderCreated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEvents_OnOrderCreated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEventsServer).OnOrderCreated(ctx, req.(*OrderCreated))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderEvents_OnOrderShipped_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderShipped)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEventsServer).OnOrderShipped(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEvents_OnOrderShipped_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEventsServer).OnOrderShipped(ctx, req.(*OrderShipped))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderEvents_OnOrderAudited_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderCreated)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderEventsServer).OnOrderAudited(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderEvents_OnOrderAudited_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderEventsServer).OnOrderAudited(ctx, req.(*OrderCreated))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderEvents_ServiceDesc is the grpc.ServiceDesc for OrderEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orderevents.OrderEvents",
	HandlerType: (*OrderEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnOrderCreated",
			Handler:    _OrderEvents_OnOrderCreated_Handler,
		},
		{
			MethodName: "OnOrderShipped",
			Handler:    _OrderEvents_OnOrderShipped_Handler,
		},
		{
			MethodName: "OnOrderAudited",
			Handler:    _OrderEvents_OnOrderAudited_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/testdata/orderevents/orderevents.proto",
}
