// Code generated by protoc-gen-go-message. DO NOT EDIT.
// versions:
// - protoc-gen-go-message v3.0.0
// - protoc                (unknown)
// source: internal/testdata/orderevents/orderevents.proto

package orderevents

import (
	context "context"
	middleware "github.com/sylphylabs/forge/middleware"
	message "github.com/sylphylabs/forge/transport/message"
	proto "google.golang.org/protobuf/proto"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Forge package it is being compiled against.
var _ = new(context.Context)
var _ = new(message.Message)
var _ middleware.UnaryHandler
var _ = proto.Unmarshal

const OperationMessageOrderEventsOnOrderCreated = "/orderevents.OrderEvents/OnOrderCreated"
const OperationMessageOrderEventsOnOrderShipped = "/orderevents.OrderEvents/OnOrderShipped"

// DestinationOrderEventsOnOrderCreated is the destination declared by the
// contract. It is the default for RegisterOrderEventsMessageServer, not a
// fixed value: see OrderEventsMessageRegisterOption.
const DestinationOrderEventsOnOrderCreated = "order.created"

// DestinationOrderEventsOnOrderShipped is the destination declared by the
// contract. It is the default for RegisterOrderEventsMessageServer, not a
// fixed value: see OrderEventsMessageRegisterOption.
const DestinationOrderEventsOnOrderShipped = "order.shipped"

type OrderEventsMessageServer interface {
	// OnOrderCreated consumes a newly created order.
	OnOrderCreated(context.Context, *OrderCreated) error
	// OnOrderShipped consumes a shipped order.
	OnOrderShipped(context.Context, *OrderShipped) error
}

// OrderEventsMessageRegisterOption overrides contract defaults when
// OrderEventsMessageServer is registered. The proto destination is the
// contract's default; deployments whose topic prefix or naming scheme differs
// override it here instead of editing the schema.
type OrderEventsMessageRegisterOption func(*orderEventsMessageRegisterOptions)

type orderEventsMessageRegisterOptions struct {
	prefix       string
	destinations map[string]string
}

// WithOrderEventsMessageDestination replaces the destination of one
// operation. The operation is the RPC name declared in the proto file, which
// stays stable even when the Go method name is remapped.
func WithOrderEventsMessageDestination(operation, destination string) OrderEventsMessageRegisterOption {
	return func(o *orderEventsMessageRegisterOptions) {
		if o.destinations == nil {
			o.destinations = make(map[string]string)
		}
		o.destinations[operation] = destination
	}
}

// WithOrderEventsMessageDestinationPrefix prepends a prefix to every
// destination that WithOrderEventsMessageDestination did not replace
// outright. The prefix is applied verbatim: a separator, where the broker
// needs one, belongs in the prefix.
func WithOrderEventsMessageDestinationPrefix(prefix string) OrderEventsMessageRegisterOption {
	return func(o *orderEventsMessageRegisterOptions) {
		o.prefix = prefix
	}
}

func (o *orderEventsMessageRegisterOptions) resolve(operation, declared string) string {
	if replacement, ok := o.destinations[operation]; ok {
		return replacement
	}
	return o.prefix + declared
}

// RegisterOrderEventsMessageServer binds every subscribe-annotated method
// of the service to s. Registration must happen before the server starts; the
// first binding error is returned and no further method is bound.
func RegisterOrderEventsMessageServer(s *message.Server, srv OrderEventsMessageServer, opts ...OrderEventsMessageRegisterOption) error {
	o := new(orderEventsMessageRegisterOptions)
	for _, opt := range opts {
		if opt != nil {
			opt(o)
		}
	}
	if err := s.Handle(
		o.resolve("OnOrderCreated", DestinationOrderEventsOnOrderCreated),
		_OrderEvents_OnOrderCreated_Message_Handler(srv),
	); err != nil {
		return err
	}
	if err := s.Handle(
		o.resolve("OnOrderShipped", DestinationOrderEventsOnOrderShipped),
		_OrderEvents_OnOrderShipped_Message_Handler(srv),
	); err != nil {
		return err
	}
	return nil
}

func _OrderEvents_OnOrderCreated_Message_Handler(srv OrderEventsMessageServer) middleware.UnaryHandler {
	return func(ctx context.Context, req any) (any, error) {
		var in OrderCreated
		if msg, ok := req.(*message.Message); ok && msg != nil {
			if err := proto.Unmarshal(msg.Body, &in); err != nil {
				return nil, err
			}
		}
		return nil, srv.OnOrderCreated(ctx, &in)
	}
}

func _OrderEvents_OnOrderShipped_Message_Handler(srv OrderEventsMessageServer) middleware.UnaryHandler {
	return func(ctx context.Context, req any) (any, error) {
		var in OrderShipped
		if msg, ok := req.(*message.Message); ok && msg != nil {
			if err := proto.Unmarshal(msg.Body, &in); err != nil {
				return nil, err
			}
		}
		return nil, srv.OnOrderShipped(ctx, &in)
	}
}
