// Code generated by protoc-gen-go-message. DO NOT EDIT.
// versions:
// - protoc-gen-go-message v3.0.0
// - protoc                (unknown)
// source: internal/testdata/orderevents/orderevents.proto

package orderevents

import (
	context "context"
	fmt "fmt"
	middleware "github.com/sylphylabs/forge/middleware"
	message "github.com/sylphylabs/forge/transport/message"
	proto "google.golang.org/protobuf/proto"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the Forge package it is being compiled against.
var _ = new(context.Context)
var _ = new(message.Message)
var _ middleware.UnaryHandler
var _ = proto.Unmarshal
var _ = fmt.Errorf
var _ = strings.TrimSpace

// DestinationOrderEventsOnOrderCreated is the destination declared by the
// contract. It is the default for RegisterOrderEventsMessageServer, not a
// fixed value: see OrderEventsMessageRegisterOption.
//
// It is also the key middleware matches on, because a delivered message reports
// its destination as the operation in flight. There is deliberately no
// "/orderevents.OrderEvents/OnOrderCreated" constant: that shape is what HTTP and gRPC
// report, and a matcher built from it would never fire here.
const DestinationOrderEventsOnOrderCreated = "order.created"

// DestinationOrderEventsOnOrderShipped is the destination declared by the
// contract. It is the default for RegisterOrderEventsMessageServer, not a
// fixed value: see OrderEventsMessageRegisterOption.
//
// It is also the key middleware matches on, because a delivered message reports
// its destination as the operation in flight. There is deliberately no
// "/orderevents.OrderEvents/OnOrderShipped" constant: that shape is what HTTP and gRPC
// report, and a matcher built from it would never fire here.
const DestinationOrderEventsOnOrderShipped = "order.shipped"

type OrderEventsMessageServer interface {
	// OnOrderCreated consumes a newly created order.
	OnOrderCreated(context.Context, *OrderCreated) error
	// OnOrderShipped consumes a shipped order.
	OnOrderShipped(context.Context, *OrderShipped) error
}

// OrderEventsMessageRegisterOption overrides contract defaults when
// OrderEventsMessageServer is registered. The proto destination is the
// contract's default; deployments whose topic prefix or naming scheme differs
// override it here instead of editing the schema.
type OrderEventsMessageRegisterOption func(*orderEventsMessageRegisterOptions)

type orderEventsMessageRegisterOptions struct {
	prefix       string
	destinations map[string]string
}

// WithOrderEventsMessageDestination replaces the destination of one
// operation. The operation is the RPC name declared in the proto file, which
// stays stable even when the Go method name is remapped.
func WithOrderEventsMessageDestination(operation, destination string) OrderEventsMessageRegisterOption {
	return func(o *orderEventsMessageRegisterOptions) {
		if o.destinations == nil {
			o.destinations = make(map[string]string)
		}
		o.destinations[operation] = destination
	}
}

// WithOrderEventsMessageDestinationPrefix prepends a prefix to every
// destination that WithOrderEventsMessageDestination did not replace
// outright. The prefix is applied verbatim: a separator, where the broker
// needs one, belongs in the prefix.
func WithOrderEventsMessageDestinationPrefix(prefix string) OrderEventsMessageRegisterOption {
	return func(o *orderEventsMessageRegisterOptions) {
		o.prefix = prefix
	}
}

func (o *orderEventsMessageRegisterOptions) resolve(operation, declared string) string {
	if replacement, ok := o.destinations[operation]; ok {
		return replacement
	}
	return o.prefix + declared
}

// orderEventsMessageOperations lists the operations this
// contract declares, so that an override naming something else is reported
// rather than silently ignored.
var orderEventsMessageOperations = map[string]struct{}{
	"OnOrderCreated": {},
	"OnOrderShipped": {},
}

// RegisterOrderEventsMessageServer binds every subscribe-annotated method
// of the service to s. Registration must happen before the server starts.
//
// Every destination is resolved and checked before the first binding, so a
// rejected registration binds nothing at all. Binding as it went would leave a
// server that returns an error and still starts, consuming part of its contract
// while the rest is silently absent.
func RegisterOrderEventsMessageServer(s *message.Server, srv OrderEventsMessageServer, opts ...OrderEventsMessageRegisterOption) error {
	o := new(orderEventsMessageRegisterOptions)
	for _, opt := range opts {
		if opt != nil {
			opt(o)
		}
	}
	for operation := range o.destinations {
		if _, ok := orderEventsMessageOperations[operation]; !ok {
			return fmt.Errorf("orderevents.OrderEvents: override names unknown operation %q", operation)
		}
	}

	type binding struct {
		destination string
		handler     middleware.UnaryHandler
	}
	bindings := []binding{
		{
			destination: o.resolve("OnOrderCreated", DestinationOrderEventsOnOrderCreated),
			handler:     _OrderEvents_OnOrderCreated_Message_Handler(srv),
		},
		{
			destination: o.resolve("OnOrderShipped", DestinationOrderEventsOnOrderShipped),
			handler:     _OrderEvents_OnOrderShipped_Message_Handler(srv),
		},
	}

	claimed := make(map[string]struct{}, len(bindings))
	for _, b := range bindings {
		if strings.TrimSpace(b.destination) == "" {
			return fmt.Errorf("orderevents.OrderEvents: empty destination after resolution")
		}
		if _, dup := claimed[b.destination]; dup {
			// The second Handle would shadow the first, so the contract would
			// be half-consumed with no error at delivery time.
			return fmt.Errorf("orderevents.OrderEvents: two operations resolve to destination %q", b.destination)
		}
		claimed[b.destination] = struct{}{}
	}

	for _, b := range bindings {
		if err := s.Handle(b.destination, b.handler); err != nil {
			return err
		}
	}
	return nil
}

func _OrderEvents_OnOrderCreated_Message_Handler(srv OrderEventsMessageServer) middleware.UnaryHandler {
	return func(ctx context.Context, req any) (any, error) {
		msg, ok := req.(*message.Message)
		if !ok || msg == nil {
			// The request is always the delivered envelope. Anything else means
			// this handler was mounted somewhere other than a message server,
			// and decoding an empty request would hand business code a
			// plausible-looking event that never arrived.
			return nil, fmt.Errorf("orderevents.OrderEvents: handler wants a *message.Message, got %T", req)
		}
		var in OrderCreated
		if err := proto.Unmarshal(msg.Body, &in); err != nil {
			return nil, err
		}
		return nil, srv.OnOrderCreated(ctx, &in)
	}
}

func _OrderEvents_OnOrderShipped_Message_Handler(srv OrderEventsMessageServer) middleware.UnaryHandler {
	return func(ctx context.Context, req any) (any, error) {
		msg, ok := req.(*message.Message)
		if !ok || msg == nil {
			// The request is always the delivered envelope. Anything else means
			// this handler was mounted somewhere other than a message server,
			// and decoding an empty request would hand business code a
			// plausible-looking event that never arrived.
			return nil, fmt.Errorf("orderevents.OrderEvents: handler wants a *message.Message, got %T", req)
		}
		var in OrderShipped
		if err := proto.Unmarshal(msg.Body, &in); err != nil {
			return nil, err
		}
		return nil, srv.OnOrderShipped(ctx, &in)
	}
}
