// Code generated by protoc-gen-go-middleware. DO NOT EDIT.
// versions:
// - protoc-gen-go-middleware v3.0.0
// - protoc                   (unknown)
// source: internal/testdata/orderevents/orderevents.proto

package orderevents

import (
	context "context"
	fmt "fmt"
	middleware "github.com/sylphylabs/forge/middleware"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// OrderEventsMiddleware configures generated server middleware for orderevents.OrderEvents.
type OrderEventsMiddleware struct {
	Unary   []middleware.UnaryMiddleware
	Stream  []middleware.StreamMiddleware
	Methods OrderEventsMethodMiddleware
}

// OrderEventsMethodMiddleware configures middleware for individual RPC methods.
type OrderEventsMethodMiddleware struct {
	OnOrderCreated []middleware.UnaryMiddleware
	OnOrderShipped []middleware.UnaryMiddleware
	OnOrderAudited []middleware.UnaryMiddleware
}

type _OrderEventsGRPCMiddlewareServer struct {
	OrderEventsServer
	handlerOnOrderCreated middleware.UnaryHandler
	handlerOnOrderShipped middleware.UnaryHandler
	handlerOnOrderAudited middleware.UnaryHandler
}

// WrapOrderEventsGRPCServer snapshots plan and composes every gRPC handler before registration.
func WrapOrderEventsGRPCServer(srv OrderEventsServer, plan OrderEventsMiddleware) (OrderEventsServer, error) {
	if srv == nil {
		return nil, fmt.Errorf("forge: nil OrderEvents gRPC server")
	}
	wrapped := &_OrderEventsGRPCMiddlewareServer{OrderEventsServer: srv}
	{
		middlewares := make([]middleware.UnaryMiddleware, 0, len(plan.Unary)+len(plan.Methods.OnOrderCreated))
		middlewares = append(middlewares, plan.Unary...)
		middlewares = append(middlewares, plan.Methods.OnOrderCreated...)
		handler, err := middleware.ComposeUnary(func(ctx context.Context, request any) (any, error) {
			typed, ok := request.(*OrderCreated)
			if !ok {
				return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderCreated gRPC request type %T, want *OrderCreated", request)
			}
			return srv.OnOrderCreated(ctx, typed)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping orderevents.OrderEvents/OnOrderCreated gRPC: %w", err)
		}
		wrapped.handlerOnOrderCreated = handler
	}
	{
		middlewares := make([]middleware.UnaryMiddleware, 0, len(plan.Unary)+len(plan.Methods.OnOrderShipped))
		middlewares = append(middlewares, plan.Unary...)
		middlewares = append(middlewares, plan.Methods.OnOrderShipped...)
		handler, err := middleware.ComposeUnary(func(ctx context.Context, request any) (any, error) {
			typed, ok := request.(*OrderShipped)
			if !ok {
				return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderShipped gRPC request type %T, want *OrderShipped", request)
			}
			return srv.OnOrderShipped(ctx, typed)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping orderevents.OrderEvents/OnOrderShipped gRPC: %w", err)
		}
		wrapped.handlerOnOrderShipped = handler
	}
	{
		middlewares := make([]middleware.UnaryMiddleware, 0, len(plan.Unary)+len(plan.Methods.OnOrderAudited))
		middlewares = append(middlewares, plan.Unary...)
		middlewares = append(middlewares, plan.Methods.OnOrderAudited...)
		handler, err := middleware.ComposeUnary(func(ctx context.Context, request any) (any, error) {
			typed, ok := request.(*OrderCreated)
			if !ok {
				return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderAudited gRPC request type %T, want *OrderCreated", request)
			}
			return srv.OnOrderAudited(ctx, typed)
		}, middlewares...)
		if err != nil {
			return nil, fmt.Errorf("forge: wrapping orderevents.OrderEvents/OnOrderAudited gRPC: %w", err)
		}
		wrapped.handlerOnOrderAudited = handler
	}
	return wrapped, nil
}

func (s *_OrderEventsGRPCMiddlewareServer) OnOrderCreated(ctx context.Context, request *OrderCreated) (*emptypb.Empty, error) {
	reply, err := s.handlerOnOrderCreated(ctx, request)
	if err != nil {
		return nil, err
	}
	typed, ok := reply.(*emptypb.Empty)
	if !ok {
		return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderCreated gRPC reply type %T, want *Empty", reply)
	}
	return typed, nil
}

func (s *_OrderEventsGRPCMiddlewareServer) OnOrderShipped(ctx context.Context, request *OrderShipped) (*emptypb.Empty, error) {
	reply, err := s.handlerOnOrderShipped(ctx, request)
	if err != nil {
		return nil, err
	}
	typed, ok := reply.(*emptypb.Empty)
	if !ok {
		return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderShipped gRPC reply type %T, want *Empty", reply)
	}
	return typed, nil
}

func (s *_OrderEventsGRPCMiddlewareServer) OnOrderAudited(ctx context.Context, request *OrderCreated) (*emptypb.Empty, error) {
	reply, err := s.handlerOnOrderAudited(ctx, request)
	if err != nil {
		return nil, err
	}
	typed, ok := reply.(*emptypb.Empty)
	if !ok {
		return nil, fmt.Errorf("forge: orderevents.OrderEvents/OnOrderAudited gRPC reply type %T, want *Empty", reply)
	}
	return typed, nil
}
