// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/testdata/orderevents/orderevents.proto

package orderevents

import (
	_ "github.com/sylphylabs/forge/api/message/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderCreated is published when an order is accepted.
type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer      string                 `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_internal_testdata_orderevents_orderevents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_orderevents_orderevents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_internal_testdata_orderevents_orderevents_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCreated) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

// OrderShipped is published when an order leaves the warehouse.
type OrderShipped struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Carrier       string                 `protobuf:"bytes,2,opt,name=carrier,proto3" json:"carrier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderShipped) Reset() {
	*x = OrderShipped{}
	mi := &file_internal_testdata_orderevents_orderevents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderShipped) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderShipped) ProtoMessage() {}

func (x *OrderShipped) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_orderevents_orderevents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderShipped.ProtoReflect.Descriptor instead.
func (*OrderShipped) Descriptor() ([]byte, []int) {
	return file_internal_testdata_orderevents_orderevents_proto_rawDescGZIP(), []int{1}
}

func (x *OrderShipped) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderShipped) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

var File_internal_testdata_orderevents_orderevents_proto protoreflect.FileDescriptor

const file_internal_testdata_orderevents_orderevents_proto_rawDesc = "" +
	"\n" +
	"/internal/testdata/orderevents/orderevents.proto\x12\vorderevents\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fsylphy/message/v1/message.proto\":\n" +
	"\fOrderCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bcustomer\x18\x02 \x01(\tR\bcustomer\"8\n" +
	"\fOrderShipped\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acarrier\x18\x02 \x01(\tR\acarrier2\x88\x02\n" +
	"\vOrderEvents\x12Y\n" +
	"\x0eOnOrderCreated\x12\x19.orderevents.OrderCreated\x1a\x16.google.protobuf.Empty\"\x14ʞ\xf4\x01\x0f\n" +
	"\rorder.created\x12Y\n" +
	"\x0eOnOrderShipped\x12\x19.orderevents.OrderShipped\x1a\x16.google.protobuf.Empty\"\x14ʞ\xf4\x01\x0f\n" +
	"\rorder.shipped\x12C\n" +
	"\x0eOnOrderAudited\x12\x19.orderevents.OrderCreated\x1a\x16.google.protobuf.EmptyB;Z9github.com/sylphylabs/forge/internal/testdata/ordereventsb\x06proto3"

var (
	file_internal_testdata_orderevents_orderevents_proto_rawDescOnce sync.Once
	file_internal_testdata_orderevents_orderevents_proto_rawDescData []byte
)

func file_internal_testdata_orderevents_orderevents_proto_rawDescGZIP() []byte {
	file_internal_testdata_orderevents_orderevents_proto_rawDescOnce.Do(func() {
		file_internal_testdata_orderevents_orderevents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testdata_orderevents_orderevents_proto_rawDesc), len(file_internal_testdata_orderevents_orderevents_proto_rawDesc)))
	})
	return file_internal_testdata_orderevents_orderevents_proto_rawDescData
}

var file_internal_testdata_orderevents_orderevents_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testdata_orderevents_orderevents_proto_goTypes = []any{
	(*OrderCreated)(nil),  // 0: orderevents.OrderCreated
	(*OrderShipped)(nil),  // 1: orderevents.OrderShipped
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_internal_testdata_orderevents_orderevents_proto_depIdxs = []int32{
	0, // 0: orderevents.OrderEvents.OnOrderCreated:input_type -> orderevents.OrderCreated
	1, // 1: orderevents.OrderEvents.OnOrderShipped:input_type -> orderevents.OrderShipped
	0, // 2: orderevents.OrderEvents.OnOrderAudited:input_type -> orderevents.OrderCreated
	2, // 3: orderevents.OrderEvents.OnOrderCreated:output_type -> google.protobuf.Empty
	2, // 4: orderevents.OrderEvents.OnOrderShipped:output_type -> google.protobuf.Empty
	2, // 5: orderevents.OrderEvents.OnOrderAudited:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testdata_orderevents_orderevents_proto_init() }
func file_internal_testdata_orderevents_orderevents_proto_init() {
	if File_internal_testdata_orderevents_orderevents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testdata_orderevents_orderevents_proto_rawDesc), len(file_internal_testdata_orderevents_orderevents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testdata_orderevents_orderevents_proto_goTypes,
		DependencyIndexes: file_internal_testdata_orderevents_orderevents_proto_depIdxs,
		MessageInfos:      file_internal_testdata_orderevents_orderevents_proto_msgTypes,
	}.Build()
	File_internal_testdata_orderevents_orderevents_proto = out.File
	file_internal_testdata_orderevents_orderevents_proto_goTypes = nil
	file_internal_testdata_orderevents_orderevents_proto_depIdxs = nil
}
