package main

import (
	"errors"
	"fmt"
	"net/http"
	"os"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/gofeaturespb"

	"github.com/openkratos/kratos/internal/httprule"
)

const (
	contextPackage       = protogen.GoImportPath("context")
	transportHTTPPackage = protogen.GoImportPath("github.com/openkratos/kratos/transport/http")
	httpBodyFullName     = protoreflect.FullName("google.api.HttpBody")
)

// generateFile generates a _http.pb.go file containing kratos errors definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File, omitempty bool, omitemptyPrefix string) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 || (omitempty && !hasHTTPRule(file.Services)) {
		return nil, nil
	}
	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-http %s", release))
	g.P("// - protoc             ", protocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	if err := generateFileContent(gen, file, g, omitempty, omitemptyPrefix); err != nil {
		return nil, err
	}
	return g, nil
}

// generateFileContent generates the kratos errors definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, omitempty bool, omitemptyPrefix string) error {
	if len(file.Services) == 0 {
		return nil
	}
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the kratos package it is being compiled against.")
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")
	g.P("const _ = ", transportHTTPPackage.Ident("SupportPackageIsVersion3"))
	g.P()

	rules := newRuleSet()
	for _, service := range file.Services {
		if err := genService(gen, file, g, service, omitempty, omitemptyPrefix, rules); err != nil {
			return err
		}
	}
	return nil
}

func genService(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service, omitempty bool, omitemptyPrefix string, rules *ruleSet) error {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	// HTTP Server.
	sd := &serviceDesc{
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Metadata:    file.Desc.Path(),
	}
	for _, method := range service.Methods {
		rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if rule != nil && ok {
			primary, err := buildHTTPRule(g, service, method, rule, 0)
			if err != nil {
				return fmt.Errorf("RPC %s: %w", method.Desc.FullName(), err)
			}
			if err := rules.add(primary); err != nil {
				return fmt.Errorf("RPC %s: %w", method.Desc.FullName(), err)
			}
			sd.Methods = append(sd.Methods, primary)
			sd.ClientMethods = append(sd.ClientMethods, primary)
			for i, binding := range rule.AdditionalBindings {
				if len(binding.AdditionalBindings) != 0 {
					return fmt.Errorf("RPC %s additional binding %d: nested additional bindings are not allowed", method.Desc.FullName(), i+1)
				}
				desc, err := buildHTTPRule(g, service, method, binding, i+1)
				if err != nil {
					return fmt.Errorf("RPC %s additional binding %d: %w", method.Desc.FullName(), i+1, err)
				}
				if err := rules.add(desc); err != nil {
					return fmt.Errorf("RPC %s additional binding %d: %w", method.Desc.FullName(), i+1, err)
				}
				sd.Methods = append(sd.Methods, desc)
			}
		} else if !omitempty && !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			path := fmt.Sprintf("%s/%s/%s", omitemptyPrefix, service.Desc.FullName(), method.Desc.Name())
			template, err := httprule.Parse(path)
			if err != nil {
				return fmt.Errorf("RPC %s default rule: %w", method.Desc.FullName(), err)
			}
			desc := buildMethodDesc(g, method, http.MethodPost, path, template, 0)
			if err := rules.add(desc); err != nil {
				return fmt.Errorf("RPC %s default rule: %w", method.Desc.FullName(), err)
			}
			sd.Methods = append(sd.Methods, desc)
			sd.ClientMethods = append(sd.ClientMethods, desc)
		}
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute())
	}
	return nil
}

func hasHTTPRule(services []*protogen.Service) bool {
	for _, service := range services {
		for _, method := range service.Methods {
			rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
			if rule != nil && ok {
				return true
			}
		}
	}
	return false
}

func buildHTTPRule(g *protogen.GeneratedFile, _ *protogen.Service, m *protogen.Method, rule *annotations.HttpRule, bindingNum int) (*methodDesc, error) {
	var (
		path         string
		method       string
		body         string
		responseBody string
	)

	switch pattern := rule.Pattern.(type) {
	case *annotations.HttpRule_Get:
		path = pattern.Get
		method = http.MethodGet
	case *annotations.HttpRule_Put:
		path = pattern.Put
		method = http.MethodPut
	case *annotations.HttpRule_Post:
		path = pattern.Post
		method = http.MethodPost
	case *annotations.HttpRule_Delete:
		path = pattern.Delete
		method = http.MethodDelete
	case *annotations.HttpRule_Patch:
		path = pattern.Patch
		method = http.MethodPatch
	case *annotations.HttpRule_Custom:
		if pattern.Custom == nil || pattern.Custom.Kind == "" {
			return nil, errors.New("custom HTTP method is empty")
		}
		path = pattern.Custom.Path
		method = pattern.Custom.Kind
	}
	if method == "" {
		return nil, errors.New("HTTP method is not specified")
	}
	if path == "" {
		return nil, errors.New("HTTP path is empty")
	}
	template, err := httprule.Parse(path)
	if err != nil {
		return nil, fmt.Errorf("path %q: %w", path, err)
	}
	if err := validatePathFields(m.Input.Desc, template.Variables()); err != nil {
		return nil, fmt.Errorf("path %q: %w", path, err)
	}
	body = rule.Body
	responseBody = rule.ResponseBody
	md := buildMethodDesc(g, m, method, path, template, bindingNum)
	// Client-streaming RPCs are served over WebSocket, whose handshake is always an
	// HTTP GET regardless of the declared verb. Declaring a body for them is legitimate
	// (it identifies the streamed message field), so skip the GET/DELETE body warnings.
	if !m.Desc.IsStreamingClient() {
		if method == http.MethodGet || method == http.MethodDelete {
			if body != "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s body should not be declared.\n", method, path)
			}
		} else {
			if body == "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s does not declare a body.\n", method, path)
			}
		}
	}
	if body == "*" {
		md.HasBody = true
		md.BodyField = "*"
		md.BodyHTTPBody = isHTTPBodyMessage(m.Input.Desc)
		md.BodyProtoJSON = true
	} else if body != "" {
		if strings.ContainsRune(body, '.') {
			return nil, fmt.Errorf("body field %q must be top-level", body)
		}
		field := fieldByName(m.Input, body)
		var fd protoreflect.FieldDescriptor
		if field != nil {
			fd = field.Desc
		}
		if fd == nil {
			return nil, fmt.Errorf("body field %q does not exist in request %s", body, m.Input.Desc.FullName())
		}
		for _, variable := range template.Variables() {
			if variable.FieldPath == body || strings.HasPrefix(variable.FieldPath, body+".") {
				return nil, fmt.Errorf("body field %q overlaps path field %q", body, variable.FieldPath)
			}
		}
		md.HasBody = true
		md.BodyField = body
		md.BodyQueryName = fd.JSONName()
		md.BodyGetter = fieldGetter(field)
		md.BodyType = fieldGoType(g, field)
		md.BodyAssignment = fieldAssignment(g, "in", field, "body")
		md.BodyHTTPBody = isHTTPBodyField(fd)
		// A singular message-kind body field can be streamed frame-by-frame for
		// client-streaming RPCs (each frame carries just this field's payload).
		md.BodyMessage = fd.Kind() == protoreflect.MessageKind && !fd.IsList() && !fd.IsMap()
		md.BodyProtoJSON = md.BodyMessage
	} else {
		md.HasBody = false
	}
	if err := validateQueryFields(m.Input.Desc, template.Variables(), body); err != nil {
		return nil, fmt.Errorf("query parameters: %w", err)
	}
	if responseBody == "*" {
		return nil, errors.New("response_body \"*\" is invalid; omit response_body for the whole response")
	}
	if responseBody != "" {
		if strings.ContainsRune(responseBody, '.') {
			return nil, fmt.Errorf("response_body field %q must be top-level", responseBody)
		}
		field := fieldByName(m.Output, responseBody)
		var fd protoreflect.FieldDescriptor
		if field != nil {
			fd = field.Desc
		}
		if fd == nil {
			return nil, fmt.Errorf("response_body field %q does not exist in response %s", responseBody, m.Output.Desc.FullName())
		}
		md.ResponseBodyGetter = fieldGetter(field)
		md.ResponseBodyField = responseBody
		md.ResponseBodyType = fieldGoType(g, field)
		md.ResponseAssignment = fieldAssignment(g, "out", field, "responseBody")
		md.ResponseBodyHTTPBody = isHTTPBodyField(fd)
	}
	return md, nil
}

type ruleSet struct {
	mux        *http.ServeMux
	matches    map[string]struct{}
	structures map[string]struct{}
}

func newRuleSet() *ruleSet {
	return &ruleSet{
		mux:        http.NewServeMux(),
		matches:    make(map[string]struct{}),
		structures: make(map[string]struct{}),
	}
}

func (s *ruleSet) add(method *methodDesc) (err error) {
	matchKey := method.Method + "\x00" + method.matchKey
	if _, exists := s.matches[matchKey]; exists {
		return fmt.Errorf("duplicate HTTP match set for %s %s", method.Method, method.Path)
	}
	s.matches[matchKey] = struct{}{}

	pattern := method.serveMuxPattern
	if method.Method != "*" {
		pattern = method.Method + " " + pattern
	}
	structureKey := method.Method + "\x00" + method.serveMuxPattern
	if _, exists := s.structures[structureKey]; exists {
		return nil
	}
	defer func() {
		if recovered := recover(); recovered != nil {
			err = fmt.Errorf("conflicting HTTP rule %s %s: %v", method.Method, method.Path, recovered)
		}
	}()
	s.mux.Handle(pattern, http.NotFoundHandler())
	s.structures[structureKey] = struct{}{}
	return nil
}

func validatePathFields(message protoreflect.MessageDescriptor, variables []httprule.Variable) error {
	for _, variable := range variables {
		fields := message.Fields()
		parts := strings.Split(variable.FieldPath, ".")
		for i, part := range parts {
			field := fields.ByName(protoreflect.Name(part))
			if field == nil {
				return fmt.Errorf("path field %q does not exist", strings.Join(parts[:i+1], "."))
			}
			if i < len(parts)-1 {
				if field.IsList() || field.IsMap() || field.Kind() != protoreflect.MessageKind && field.Kind() != protoreflect.GroupKind {
					return fmt.Errorf("path field %q is not a singular message", strings.Join(parts[:i+1], "."))
				}
				fields = field.Message().Fields()
				continue
			}
			if field.IsList() || field.IsMap() {
				return fmt.Errorf("path field %q is repeated or mapped", variable.FieldPath)
			}
			if field.Kind() == protoreflect.MessageKind || field.Kind() == protoreflect.GroupKind {
				return fmt.Errorf("path field %q is a message", variable.FieldPath)
			}
		}
	}
	return nil
}

func validateQueryFields(message protoreflect.MessageDescriptor, variables []httprule.Variable, body string) error {
	if body == "*" {
		return nil
	}
	pathFields := make(map[string]struct{}, len(variables))
	for _, variable := range variables {
		pathFields[variable.FieldPath] = struct{}{}
	}
	return validateQueryMessage(message, "", body, pathFields)
}

func validateQueryMessage(message protoreflect.MessageDescriptor, prefix, body string, pathFields map[string]struct{}) error {
	fields := message.Fields()
	for i := range fields.Len() {
		field := fields.Get(i)
		name := string(field.Name())
		path := name
		if prefix != "" {
			path = prefix + "." + name
		}
		if _, bound := pathFields[path]; bound || body != "" && (path == body || strings.HasPrefix(path, body+".")) {
			continue
		}
		if field.IsMap() {
			return fmt.Errorf("field %q is a map and cannot be encoded as a query parameter", path)
		}
		if field.IsList() && (field.Kind() == protoreflect.MessageKind || field.Kind() == protoreflect.GroupKind) {
			return fmt.Errorf("field %q is a repeated message and cannot be encoded as a query parameter", path)
		}
		if !field.IsList() && (field.Kind() == protoreflect.MessageKind || field.Kind() == protoreflect.GroupKind) && !isScalarQueryMessage(field.Message()) {
			if err := validateQueryMessage(field.Message(), path, body, pathFields); err != nil {
				return err
			}
		}
	}
	return nil
}

func isScalarQueryMessage(message protoreflect.MessageDescriptor) bool {
	switch message.FullName() {
	case "google.protobuf.Timestamp", "google.protobuf.Duration", "google.protobuf.BytesValue",
		"google.protobuf.DoubleValue", "google.protobuf.FloatValue", "google.protobuf.Int64Value",
		"google.protobuf.Int32Value", "google.protobuf.UInt64Value", "google.protobuf.UInt32Value",
		"google.protobuf.BoolValue", "google.protobuf.StringValue", "google.protobuf.FieldMask",
		"google.protobuf.Value", "google.protobuf.Struct":
		return true
	default:
		return false
	}
}

func fieldByName(message *protogen.Message, name string) *protogen.Field {
	for _, field := range message.Fields {
		if string(field.Desc.Name()) == name {
			return field
		}
	}
	return nil
}

func fieldGetter(field *protogen.Field) string {
	getter, _ := field.MethodName("Get")
	return "." + getter + "()"
}

func fieldAssignment(g *protogen.GeneratedFile, target string, field *protogen.Field, value string) string {
	if field.Parent.APILevel != gofeaturespb.GoFeatures_API_OPEN {
		setter, _ := field.MethodName("Set")
		return fmt.Sprintf("%s.%s(%s)", target, setter, value)
	}
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		return fmt.Sprintf(
			"%s.%s = &%s{%s: %s}",
			target,
			field.Oneof.GoName,
			g.QualifiedGoIdent(field.GoIdent),
			field.GoName,
			value,
		)
	}
	if openStructFieldIsPointer(field) {
		return fmt.Sprintf("%s.%s = &%s", target, field.GoName, value)
	}
	return fmt.Sprintf("%s.%s = %s", target, field.GoName, value)
}

func openStructFieldIsPointer(field *protogen.Field) bool {
	if !field.Desc.HasPresence() || field.Desc.IsList() || field.Desc.IsMap() {
		return false
	}
	switch field.Desc.Kind() {
	case protoreflect.BytesKind, protoreflect.MessageKind, protoreflect.GroupKind:
		return false
	default:
		return true
	}
}

func fieldGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch {
	case field.Desc.IsMap():
		key := scalarGoType(g, field.Message.Fields[0])
		value := scalarGoType(g, field.Message.Fields[1])
		return fmt.Sprintf("map[%s]%s", key, value)
	}
	base := scalarGoType(g, field)
	if field.Desc.IsList() {
		return "[]" + base
	}
	return base
}

func scalarGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	default:
		panic(fmt.Sprintf("unsupported protobuf field kind %s", field.Desc.Kind()))
	}
}

func buildMethodDesc(g *protogen.GeneratedFile, m *protogen.Method, method, path string, template *httprule.Template, bindingNum int) *methodDesc {
	comment := m.Comments.Leading.String() + m.Comments.Trailing.String()
	if comment != "" {
		comment = "// " + m.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
	}
	if m.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		if comment != "" {
			comment += "\n"
		}
		comment += deprecationComment
	}
	variables := template.Variables()
	pathFields := make([]string, 0, len(variables))
	for _, variable := range variables {
		pathFields = append(pathFields, variable.FieldPath)
	}
	return &methodDesc{
		Name:                m.GoName,
		OriginalName:        string(m.Desc.Name()),
		Num:                 bindingNum,
		Request:             g.QualifiedGoIdent(m.Input.GoIdent),
		Reply:               g.QualifiedGoIdent(m.Output.GoIdent),
		Comment:             comment,
		Path:                path,
		PathTemplate:        path,
		PathFields:          pathFields,
		Method:              method,
		HasVars:             len(template.Variables()) > 0,
		ReplyHTTPBody:       isHTTPBodyMessage(m.Output.Desc),
		ClientStreaming:     m.Desc.IsStreamingClient(),
		ServerStreaming:     m.Desc.IsStreamingServer(),
		UnspecifiedMethod:   method == "*",
		UnboundPathWildcard: template.HasUnboundWildcard(),
		serveMuxPattern:     template.ServeMuxPattern(),
		matchKey:            template.MatchKey(),
	}
}

func isHTTPBodyField(fd protoreflect.FieldDescriptor) bool {
	return fd != nil && fd.Kind() == protoreflect.MessageKind && isHTTPBodyMessage(fd.Message())
}

func isHTTPBodyMessage(md protoreflect.MessageDescriptor) bool {
	return md != nil && md.FullName() == httpBodyFullName
}

func protocVersion(gen *protogen.Plugin) string {
	v := gen.Request.GetCompilerVersion()
	if v == nil {
		return "(unknown)"
	}
	var suffix string
	if s := v.GetSuffix(); s != "" {
		suffix = "-" + s
	}
	return fmt.Sprintf("v%d.%d.%d%s", v.GetMajor(), v.GetMinor(), v.GetPatch(), suffix)
}

const deprecationComment = "// Deprecated: Do not use."
