package main

import (
	"fmt"
	"net/http"
	"os"
	"strings"

	"google.golang.org/protobuf/reflect/protoreflect"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/gofeaturespb"

	"github.com/openkratos/kratos/cmd/internal/generator"
	"github.com/openkratos/kratos/cmd/internal/httpbinding"
	"github.com/openkratos/kratos/internal/httprule"
)

const (
	contextPackage       = protogen.GoImportPath("context")
	transportHTTPPackage = protogen.GoImportPath("github.com/openkratos/kratos/transport/http")
	httpBodyFullName     = protoreflect.FullName("google.api.HttpBody")
)

// generateHTTPFile generates a _http.pb.go file containing OpenKratos HTTP bindings.
func generateHTTPFile(gen *protogen.Plugin, file *protogen.File, omitempty bool, omitemptyPrefix string) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 || (omitempty && !hasHTTPRule(file.Services)) {
		return nil, nil
	}
	filename := file.GeneratedFilenamePrefix + "_http.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-http. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-http %s", generator.Release))
	g.P("// - protoc         ", generator.ProtocVersion(gen))
	if file.Proto.GetOptions().GetDeprecated() {
		g.P("// ", file.Desc.Path(), " is a deprecated file.")
	} else {
		g.P("// source: ", file.Desc.Path())
	}
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()
	if err := generateHTTPFileContent(gen, file, g, omitempty, omitemptyPrefix); err != nil {
		return nil, err
	}
	return g, nil
}

// generateHTTPFileContent generates the kratos errors definitions, excluding the package statement.
func generateHTTPFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, omitempty bool, omitemptyPrefix string) error {
	if len(file.Services) == 0 {
		return nil
	}
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the kratos package it is being compiled against.")
	g.P("var _ = new(", contextPackage.Ident("Context"), ")")
	g.P("const _ = ", transportHTTPPackage.Ident("SupportPackageIsVersion5"))
	g.P()

	rules := httpbinding.NewSet()
	for _, service := range file.Services {
		if err := genService(gen, file, g, service, omitempty, omitemptyPrefix, rules); err != nil {
			return err
		}
	}
	return nil
}

func genService(_ *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, service *protogen.Service, omitempty bool, omitemptyPrefix string, rules *httpbinding.Set) error {
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		g.P("//")
		g.P(deprecationComment)
	}
	// HTTP Server.
	sd := &serviceDesc{
		ServiceType: service.GoName,
		ServiceName: string(service.Desc.FullName()),
		Metadata:    file.Desc.Path(),
		MethodSet:   1,
	}
	if !omitempty {
		sd.MethodSet = 2
	}
	for _, method := range service.Methods {
		bindings, annotated, err := httpbinding.Analyze(method.Desc)
		if err != nil {
			return fmt.Errorf("RPC %s: %w", method.Desc.FullName(), err)
		}
		if annotated {
			for _, binding := range bindings {
				if err := rules.Add(binding); err != nil {
					if binding.Index == 0 {
						return fmt.Errorf("RPC %s: %w", method.Desc.FullName(), err)
					}
					return fmt.Errorf("RPC %s additional binding %d: %w", method.Desc.FullName(), binding.Index, err)
				}
				desc := buildHTTPBinding(g, method, binding)
				sd.Methods = append(sd.Methods, desc)
				if binding.Index == 0 {
					sd.ClientMethods = append(sd.ClientMethods, desc)
				}
			}
		} else if !omitempty && !method.Desc.IsStreamingClient() && !method.Desc.IsStreamingServer() {
			path := fmt.Sprintf("%s/%s/%s", omitemptyPrefix, service.Desc.FullName(), method.Desc.Name())
			template, err := httprule.Parse(path)
			if err != nil {
				return fmt.Errorf("RPC %s default rule: %w", method.Desc.FullName(), err)
			}
			binding := &httpbinding.Binding{Method: http.MethodPost, Path: path, Template: template}
			if err := rules.Add(binding); err != nil {
				return fmt.Errorf("RPC %s default rule: %w", method.Desc.FullName(), err)
			}
			desc := buildHTTPBinding(g, method, binding)
			sd.Methods = append(sd.Methods, desc)
			sd.ClientMethods = append(sd.ClientMethods, desc)
		}
	}
	if len(sd.Methods) != 0 {
		g.P(sd.execute())
	}
	return nil
}

func hasHTTPRule(services []*protogen.Service) bool {
	for _, service := range services {
		for _, method := range service.Methods {
			if httpbinding.HasRule(method.Desc) {
				return true
			}
		}
	}
	return false
}

func buildHTTPBinding(g *protogen.GeneratedFile, m *protogen.Method, binding *httpbinding.Binding) *methodDesc {
	md := buildMethodDesc(g, m, binding.Method, binding.Path, binding.Template, binding.Index)
	// Client-streaming RPCs are served over WebSocket, whose handshake is always an
	// HTTP GET regardless of the declared verb. Declaring a body for them is legitimate
	// (it identifies the streamed message field), so skip the GET/DELETE body warnings.
	if !m.Desc.IsStreamingClient() {
		if binding.Method == http.MethodGet || binding.Method == http.MethodDelete {
			if binding.Body != "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s body should not be declared.\n", binding.Method, binding.Path)
			}
		} else {
			if binding.Body == "" {
				_, _ = fmt.Fprintf(os.Stderr, "\u001B[31mWARN\u001B[m: %s %s does not declare a body.\n", binding.Method, binding.Path)
			}
		}
	}
	if binding.Body == "*" {
		md.HasBody = true
		md.BodyField = "*"
		md.BodyHTTPBody = isHTTPBodyMessage(m.Input.Desc)
		md.BodyProtoJSON = true
	} else if binding.BodyField != nil {
		field := fieldByName(m.Input, binding.Body)
		fd := binding.BodyField
		md.HasBody = true
		md.BodyField = binding.Body
		md.BodyQueryName = fd.JSONName()
		md.BodyGetter = fieldGetter(field)
		md.BodyType = fieldGoType(g, field)
		md.BodyAssignment = fieldAssignment(g, "in", field, "body")
		md.BodyHTTPBody = isHTTPBodyField(fd)
		// A singular message-kind body field can be streamed frame-by-frame for
		// client-streaming RPCs (each frame carries just this field's payload).
		md.BodyMessage = fd.Kind() == protoreflect.MessageKind && !fd.IsList() && !fd.IsMap()
		md.BodyProtoJSON = md.BodyMessage
	} else {
		md.HasBody = false
	}
	if binding.ResponseBodyField != nil {
		field := fieldByName(m.Output, binding.ResponseBody)
		fd := binding.ResponseBodyField
		md.ResponseBodyGetter = fieldGetter(field)
		md.ResponseBodyField = binding.ResponseBody
		md.ResponseBodyType = fieldGoType(g, field)
		md.ResponseAssignment = fieldAssignment(g, "out", field, "responseBody")
		md.ResponseBodyHTTPBody = isHTTPBodyField(fd)
	}
	return md
}

func fieldByName(message *protogen.Message, name string) *protogen.Field {
	for _, field := range message.Fields {
		if string(field.Desc.Name()) == name {
			return field
		}
	}
	return nil
}

func fieldGetter(field *protogen.Field) string {
	getter, _ := field.MethodName("Get")
	return "." + getter + "()"
}

func fieldAssignment(g *protogen.GeneratedFile, target string, field *protogen.Field, value string) string {
	if field.Parent.APILevel != gofeaturespb.GoFeatures_API_OPEN {
		setter, _ := field.MethodName("Set")
		return fmt.Sprintf("%s.%s(%s)", target, setter, value)
	}
	if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
		return fmt.Sprintf(
			"%s.%s = &%s{%s: %s}",
			target,
			field.Oneof.GoName,
			g.QualifiedGoIdent(field.GoIdent),
			field.GoName,
			value,
		)
	}
	if openStructFieldIsPointer(field) {
		return fmt.Sprintf("%s.%s = &%s", target, field.GoName, value)
	}
	return fmt.Sprintf("%s.%s = %s", target, field.GoName, value)
}

func openStructFieldIsPointer(field *protogen.Field) bool {
	if !field.Desc.HasPresence() || field.Desc.IsList() || field.Desc.IsMap() {
		return false
	}
	switch field.Desc.Kind() {
	case protoreflect.BytesKind, protoreflect.MessageKind, protoreflect.GroupKind:
		return false
	default:
		return true
	}
}

func fieldGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch {
	case field.Desc.IsMap():
		key := scalarGoType(g, field.Message.Fields[0])
		value := scalarGoType(g, field.Message.Fields[1])
		return fmt.Sprintf("map[%s]%s", key, value)
	}
	base := scalarGoType(g, field)
	if field.Desc.IsList() {
		return "[]" + base
	}
	return base
}

func scalarGoType(g *protogen.GeneratedFile, field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.BoolKind:
		return "bool"
	case protoreflect.EnumKind:
		return g.QualifiedGoIdent(field.Enum.GoIdent)
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return "int32"
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return "uint32"
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return "int64"
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return "uint64"
	case protoreflect.FloatKind:
		return "float32"
	case protoreflect.DoubleKind:
		return "float64"
	case protoreflect.StringKind:
		return "string"
	case protoreflect.BytesKind:
		return "[]byte"
	case protoreflect.MessageKind, protoreflect.GroupKind:
		return "*" + g.QualifiedGoIdent(field.Message.GoIdent)
	default:
		panic(fmt.Sprintf("unsupported protobuf field kind %s", field.Desc.Kind()))
	}
}

func buildMethodDesc(g *protogen.GeneratedFile, m *protogen.Method, method, path string, template *httprule.Template, bindingNum int) *methodDesc {
	comment := m.Comments.Leading.String() + m.Comments.Trailing.String()
	if comment != "" {
		comment = "// " + m.GoName + strings.TrimPrefix(strings.TrimSuffix(comment, "\n"), "//")
	}
	if m.Desc.Options().(*descriptorpb.MethodOptions).GetDeprecated() {
		if comment != "" {
			comment += "\n"
		}
		comment += deprecationComment
	}
	variables := template.Variables()
	pathFields := make([]string, 0, len(variables))
	for _, variable := range variables {
		pathFields = append(pathFields, variable.FieldPath)
	}
	return &methodDesc{
		Name:                m.GoName,
		OriginalName:        string(m.Desc.Name()),
		Num:                 bindingNum,
		Request:             g.QualifiedGoIdent(m.Input.GoIdent),
		Reply:               g.QualifiedGoIdent(m.Output.GoIdent),
		Comment:             comment,
		Path:                path,
		PathTemplate:        path,
		PathFields:          pathFields,
		Method:              method,
		HasVars:             len(template.Variables()) > 0,
		ReplyHTTPBody:       isHTTPBodyMessage(m.Output.Desc),
		ClientStreaming:     m.Desc.IsStreamingClient(),
		ServerStreaming:     m.Desc.IsStreamingServer(),
		UnspecifiedMethod:   method == "*",
		UnboundPathWildcard: template.HasUnboundWildcard(),
		serveMuxPattern:     template.ServeMuxPattern(),
		matchKey:            template.MatchKey(),
	}
}

func isHTTPBodyField(fd protoreflect.FieldDescriptor) bool {
	return fd != nil && fd.Kind() == protoreflect.MessageKind && isHTTPBodyMessage(fd.Message())
}

func isHTTPBodyMessage(md protoreflect.MessageDescriptor) bool {
	return md != nil && md.FullName() == httpBodyFullName
}

const deprecationComment = "// Deprecated: Do not use."
