// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sylphy/errors/v1/errors.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind classifies a failure independently of any transport. It is the single
// source of truth for an error's category: transports project a Kind onto their
// own status vocabulary, never the reverse.
//
// The values are the annotation vocabulary for declaring contract errors on
// enums. Each value is the KIND_-prefixed spelling of the wire name the Forge
// runtime uses (KIND_NOT_FOUND names the kind that travels as "NOT_FOUND"):
// the prefix is Protobuf enum scoping, not part of the name. There is no
// Protobuf error envelope; HTTP carries errors as Problem Details and gRPC as
// a status with standard details.
type Kind int32

const (
	Kind_KIND_UNSPECIFIED         Kind = 0
	Kind_KIND_INVALID_ARGUMENT    Kind = 1
	Kind_KIND_FAILED_PRECONDITION Kind = 2
	Kind_KIND_OUT_OF_RANGE        Kind = 3
	Kind_KIND_UNAUTHENTICATED     Kind = 4
	Kind_KIND_PERMISSION_DENIED   Kind = 5
	Kind_KIND_NOT_FOUND           Kind = 6
	Kind_KIND_ALREADY_EXISTS      Kind = 7
	Kind_KIND_CONFLICT            Kind = 8
	Kind_KIND_RESOURCE_EXHAUSTED  Kind = 9
	Kind_KIND_CANCELED            Kind = 10
	Kind_KIND_DEADLINE_EXCEEDED   Kind = 11
	Kind_KIND_UNAVAILABLE         Kind = 12
	Kind_KIND_UNIMPLEMENTED       Kind = 13
	Kind_KIND_INTERNAL            Kind = 14
	Kind_KIND_DATA_LOSS           Kind = 15
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0:  "KIND_UNSPECIFIED",
		1:  "KIND_INVALID_ARGUMENT",
		2:  "KIND_FAILED_PRECONDITION",
		3:  "KIND_OUT_OF_RANGE",
		4:  "KIND_UNAUTHENTICATED",
		5:  "KIND_PERMISSION_DENIED",
		6:  "KIND_NOT_FOUND",
		7:  "KIND_ALREADY_EXISTS",
		8:  "KIND_CONFLICT",
		9:  "KIND_RESOURCE_EXHAUSTED",
		10: "KIND_CANCELED",
		11: "KIND_DEADLINE_EXCEEDED",
		12: "KIND_UNAVAILABLE",
		13: "KIND_UNIMPLEMENTED",
		14: "KIND_INTERNAL",
		15: "KIND_DATA_LOSS",
	}
	Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":         0,
		"KIND_INVALID_ARGUMENT":    1,
		"KIND_FAILED_PRECONDITION": 2,
		"KIND_OUT_OF_RANGE":        3,
		"KIND_UNAUTHENTICATED":     4,
		"KIND_PERMISSION_DENIED":   5,
		"KIND_NOT_FOUND":           6,
		"KIND_ALREADY_EXISTS":      7,
		"KIND_CONFLICT":            8,
		"KIND_RESOURCE_EXHAUSTED":  9,
		"KIND_CANCELED":            10,
		"KIND_DEADLINE_EXCEEDED":   11,
		"KIND_UNAVAILABLE":         12,
		"KIND_UNIMPLEMENTED":       13,
		"KIND_INTERNAL":            14,
		"KIND_DATA_LOSS":           15,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_sylphy_errors_v1_errors_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_sylphy_errors_v1_errors_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_sylphy_errors_v1_errors_proto_rawDescGZIP(), []int{0}
}

var file_sylphy_errors_v1_errors_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*Kind)(nil),
		Field:         500101,
		Name:          "sylphy.errors.v1.default_kind",
		Tag:           "varint,500101,opt,name=default_kind,enum=sylphy.errors.v1.Kind",
		Filename:      "sylphy/errors/v1/errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*Kind)(nil),
		Field:         500102,
		Name:          "sylphy.errors.v1.kind",
		Tag:           "varint,500102,opt,name=kind,enum=sylphy.errors.v1.Kind",
		Filename:      "sylphy/errors/v1/errors.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         500103,
		Name:          "sylphy.errors.v1.throws",
		Tag:           "varint,500103,opt,name=throws",
		Filename:      "sylphy/errors/v1/errors.proto",
	},
}

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional sylphy.errors.v1.Kind default_kind = 500101;
	E_DefaultKind = &file_sylphy_errors_v1_errors_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional sylphy.errors.v1.Kind kind = 500102;
	E_Kind = &file_sylphy_errors_v1_errors_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional bool throws = 500103;
	E_Throws = &file_sylphy_errors_v1_errors_proto_extTypes[2]
)

var File_sylphy_errors_v1_errors_proto protoreflect.FileDescriptor

const file_sylphy_errors_v1_errors_proto_rawDesc = "" +
	"\n" +
	"\x1dsylphy/errors/v1/errors.proto\x12\x10sylphy.errors.v1\x1a google/protobuf/descriptor.proto*\x83\x03\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15KIND_INVALID_ARGUMENT\x10\x01\x12\x1c\n" +
	"\x18KIND_FAILED_PRECONDITION\x10\x02\x12\x15\n" +
	"\x11KIND_OUT_OF_RANGE\x10\x03\x12\x18\n" +
	"\x14KIND_UNAUTHENTICATED\x10\x04\x12\x1a\n" +
	"\x16KIND_PERMISSION_DENIED\x10\x05\x12\x12\n" +
	"\x0eKIND_NOT_FOUND\x10\x06\x12\x17\n" +
	"\x13KIND_ALREADY_EXISTS\x10\a\x12\x11\n" +
	"\rKIND_CONFLICT\x10\b\x12\x1b\n" +
	"\x17KIND_RESOURCE_EXHAUSTED\x10\t\x12\x11\n" +
	"\rKIND_CANCELED\x10\n" +
	"\x12\x1a\n" +
	"\x16KIND_DEADLINE_EXCEEDED\x10\v\x12\x14\n" +
	"\x10KIND_UNAVAILABLE\x10\f\x12\x16\n" +
	"\x12KIND_UNIMPLEMENTED\x10\r\x12\x11\n" +
	"\rKIND_INTERNAL\x10\x0e\x12\x12\n" +
	"\x0eKIND_DATA_LOSS\x10\x0f:Y\n" +
	"\fdefault_kind\x12\x1c.google.protobuf.EnumOptions\x18\x85\xc3\x1e \x01(\x0e2\x16.sylphy.errors.v1.KindR\vdefaultKind:O\n" +
	"\x04kind\x12!.google.protobuf.EnumValueOptions\x18\x86\xc3\x1e \x01(\x0e2\x16.sylphy.errors.v1.KindR\x04kind:7\n" +
	"\x06throws\x12\x1d.google.protobuf.FieldOptions\x18\x87\xc3\x1e \x01(\bR\x06throwsBQ\n" +
	"\x1bcom.github.sylphy.errors.v1P\x01Z0github.com/sylphylabs/forge/api/errors/v1;errorsb\x06proto3"

var (
	file_sylphy_errors_v1_errors_proto_rawDescOnce sync.Once
	file_sylphy_errors_v1_errors_proto_rawDescData []byte
)

func file_sylphy_errors_v1_errors_proto_rawDescGZIP() []byte {
	file_sylphy_errors_v1_errors_proto_rawDescOnce.Do(func() {
		file_sylphy_errors_v1_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sylphy_errors_v1_errors_proto_rawDesc), len(file_sylphy_errors_v1_errors_proto_rawDesc)))
	})
	return file_sylphy_errors_v1_errors_proto_rawDescData
}

var file_sylphy_errors_v1_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sylphy_errors_v1_errors_proto_goTypes = []any{
	(Kind)(0),                             // 0: sylphy.errors.v1.Kind
	(*descriptorpb.EnumOptions)(nil),      // 1: google.protobuf.EnumOptions
	(*descriptorpb.EnumValueOptions)(nil), // 2: google.protobuf.EnumValueOptions
	(*descriptorpb.FieldOptions)(nil),     // 3: google.protobuf.FieldOptions
}
var file_sylphy_errors_v1_errors_proto_depIdxs = []int32{
	1, // 0: sylphy.errors.v1.default_kind:extendee -> google.protobuf.EnumOptions
	2, // 1: sylphy.errors.v1.kind:extendee -> google.protobuf.EnumValueOptions
	3, // 2: sylphy.errors.v1.throws:extendee -> google.protobuf.FieldOptions
	0, // 3: sylphy.errors.v1.default_kind:type_name -> sylphy.errors.v1.Kind
	0, // 4: sylphy.errors.v1.kind:type_name -> sylphy.errors.v1.Kind
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	3, // [3:5] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sylphy_errors_v1_errors_proto_init() }
func file_sylphy_errors_v1_errors_proto_init() {
	if File_sylphy_errors_v1_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sylphy_errors_v1_errors_proto_rawDesc), len(file_sylphy_errors_v1_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_sylphy_errors_v1_errors_proto_goTypes,
		DependencyIndexes: file_sylphy_errors_v1_errors_proto_depIdxs,
		EnumInfos:         file_sylphy_errors_v1_errors_proto_enumTypes,
		ExtensionInfos:    file_sylphy_errors_v1_errors_proto_extTypes,
	}.Build()
	File_sylphy_errors_v1_errors_proto = out.File
	file_sylphy_errors_v1_errors_proto_goTypes = nil
	file_sylphy_errors_v1_errors_proto_depIdxs = nil
}
