package main

import (
	"fmt"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	"github.com/sylphylabs/forge/cmd/internal/generator"
	"github.com/sylphylabs/forge/cmd/internal/throws"
)

const (
	contextPackage       = protogen.GoImportPath("context")
	fmtPackage           = protogen.GoImportPath("fmt")
	middlewarePackage    = protogen.GoImportPath("github.com/sylphylabs/forge/middleware")
	throwsPackage        = protogen.GoImportPath("github.com/sylphylabs/forge/middleware/throws")
	transportHTTPPackage = protogen.GoImportPath("github.com/sylphylabs/forge/transport/http")
	grpcPackage          = protogen.GoImportPath("google.golang.org/grpc")
)

type httpMode uint8

const (
	httpDisabled httpMode = iota
	httpAnnotated
	httpAll
)

const (
	modeAnnotated = "annotated"
	modeAll       = "all"
)

const (
	transportHTTP = "HTTP"
	transportGRPC = "gRPC"
)

func parseHTTPMode(value string) (httpMode, error) {
	switch value {
	case "":
		return httpDisabled, nil
	case modeAnnotated:
		return httpAnnotated, nil
	case modeAll:
		return httpAll, nil
	default:
		return httpDisabled, fmt.Errorf("go-middleware: invalid http mode %q, want %s or %s", value, modeAnnotated, modeAll)
	}
}

func generateMiddlewareFile(
	gen *protogen.Plugin,
	file *protogen.File,
	mode httpMode,
	grpcEnabled bool,
	analyzer *throws.Analyzer,
) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}
	if err := validateMiddlewareIdentifiers(gen, file, mode, grpcEnabled); err != nil {
		return nil, err
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_middleware.pb.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-middleware. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-middleware %s", generator.Release))
	g.P("// - protoc                   ", generator.ProtocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, service := range file.Services {
		httpMethods := enabledHTTPMethods(service, mode)
		hasHTTP := mode != httpDisabled && len(httpMethods) > 0
		declarations, err := resolveServiceThrows(analyzer, service, hasHTTP || grpcEnabled)
		if err != nil {
			return nil, err
		}
		generateMiddlewarePlan(g, service)
		generateThrowsDeclarations(g, service, declarations)
		if hasHTTP {
			generateHTTPMiddlewareWrapper(g, service, httpMethods, mode, declarations)
		}
		if grpcEnabled {
			generateGRPCMiddlewareWrapper(g, service, declarations)
		}
	}
	return g, nil
}

// serviceThrows is the resolved throws declarations of one service: for each
// declared method, the identity set its wrapper asserts against.
type serviceThrows struct {
	// byMethod holds the effective identity set of each declared method,
	// deduplicated to the (domain, reason) pairs the runtime asserts on and
	// sorted for deterministic output. A method with no declaration is absent.
	byMethod map[*protogen.Method][]runtimeIdentity
	// declared lists the declared methods in service order.
	declared []*protogen.Method
}

// runtimeIdentity is the (domain, reason) pair compiled into generated code.
type runtimeIdentity struct {
	domain string
	reason string
}

// resolveServiceThrows resolves every method's effective declaration through
// the shared analyzer — the same resolution, and the same failure semantics,
// that protoc-gen-openapi applies to the identical declarations. When no
// wrapper is emitted there is no assertion point, so resolution is skipped
// and existing plan-only output stays untouched.
func resolveServiceThrows(analyzer *throws.Analyzer, service *protogen.Service, wrappersEnabled bool) (*serviceThrows, error) {
	result := &serviceThrows{byMethod: make(map[*protogen.Method][]runtimeIdentity)}
	if !wrappersEnabled {
		return result, nil
	}
	for _, method := range service.Methods {
		identities, err := analyzer.MethodDeclarations(service.Desc.Options(), method.Desc.Options())
		if err != nil {
			return nil, fmt.Errorf("resolving throws for %s/%s: %w", service.Desc.FullName(), method.Desc.Name(), err)
		}
		if len(identities) == 0 {
			continue
		}
		seen := make(map[runtimeIdentity]bool, len(identities))
		pairs := make([]runtimeIdentity, 0, len(identities))
		for _, identity := range identities {
			pair := runtimeIdentity{domain: identity.Domain, reason: identity.Reason}
			if seen[pair] {
				continue
			}
			seen[pair] = true
			pairs = append(pairs, pair)
		}
		sort.Slice(pairs, func(i, j int) bool {
			if pairs[i].domain != pairs[j].domain {
				return pairs[i].domain < pairs[j].domain
			}
			return pairs[i].reason < pairs[j].reason
		})
		result.byMethod[method] = pairs
		result.declared = append(result.declared, method)
	}
	return result, nil
}

// hasDeclarations reports whether any method of the service participates in
// runtime assertion.
func (s *serviceThrows) hasDeclarations() bool { return len(s.declared) > 0 }

// declarationVar names the generated package-level throws declaration of one
// method.
func declarationVar(service *protogen.Service, method *protogen.Method) string {
	return "_" + service.GoName + "Throws" + method.GoName
}

// generateThrowsDeclarations emits one compiled declaration per declared
// method. The identity set is static data resolved at generation time: the
// request path reads no descriptors and performs no reflection.
func generateThrowsDeclarations(g *protogen.GeneratedFile, service *protogen.Service, declarations *serviceThrows) {
	if !declarations.hasDeclarations() {
		return
	}
	for _, method := range declarations.declared {
		fullMethod := string(service.Desc.FullName()) + "/" + string(method.Desc.Name())
		g.P("// ", declarationVar(service, method), " is the declared error identity set of ", fullMethod, ",")
		g.P("// compiled from its Protobuf throws declarations. Wrappers assert every")
		g.P("// returned error against it.")
		g.P("var ", declarationVar(service, method), " = ", throwsPackage.Ident("Declare"), "(", strconv.Quote(fullMethod), ",")
		for _, identity := range declarations.byMethod[method] {
			g.P(throwsPackage.Ident("Identity"), "{Domain: ", strconv.Quote(identity.domain), ", Reason: ", strconv.Quote(identity.reason), "},")
		}
		g.P(")")
		g.P()
	}
}

func validateMiddlewareIdentifiers(gen *protogen.Plugin, file *protogen.File, mode httpMode, grpcEnabled bool) error {
	owners := make(map[string]string)
	for _, candidate := range gen.Files {
		if !candidate.Generate || candidate.GoImportPath != file.GoImportPath {
			continue
		}
		for _, enum := range candidate.Enums {
			collectEnumIdentifiers(owners, enum)
		}
		for _, message := range candidate.Messages {
			collectMessageIdentifiers(owners, message)
		}
		for _, extension := range candidate.Extensions {
			owners["E_"+extension.GoIdent.GoName] = fmt.Sprintf("extension %s", extension.Desc.FullName())
		}
	}

	for _, service := range file.Services {
		hasHTTP := mode != httpDisabled && len(enabledHTTPMethods(service, mode)) > 0
		identifiers := []string{
			service.GoName + "Middleware",
			service.GoName + "MethodMiddleware",
		}
		if hasHTTP {
			identifiers = append(identifiers, "Wrap"+service.GoName+"HTTPServer")
		}
		if grpcEnabled {
			identifiers = append(identifiers, "Wrap"+service.GoName+"GRPCServer")
		}
		for _, identifier := range identifiers {
			if owner, ok := owners[identifier]; ok {
				return fmt.Errorf("proto %q service %s: generated middleware identifier %q conflicts with %s", file.Desc.Path(), service.Desc.FullName(), identifier, owner)
			}
			owners[identifier] = fmt.Sprintf("generated middleware for service %s", service.Desc.FullName())
		}
	}
	return nil
}

func collectMessageIdentifiers(owners map[string]string, message *protogen.Message) {
	owners[message.GoIdent.GoName] = fmt.Sprintf("message %s", message.Desc.FullName())
	for _, enum := range message.Enums {
		collectEnumIdentifiers(owners, enum)
	}
	for _, nested := range message.Messages {
		collectMessageIdentifiers(owners, nested)
	}
	for _, extension := range message.Extensions {
		owners["E_"+extension.GoIdent.GoName] = fmt.Sprintf("extension %s", extension.Desc.FullName())
	}
	for _, field := range message.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			owners[field.GoIdent.GoName] = fmt.Sprintf("oneof field %s", field.Desc.FullName())
		}
	}
}

func collectEnumIdentifiers(owners map[string]string, enum *protogen.Enum) {
	owners[enum.GoIdent.GoName] = fmt.Sprintf("enum %s", enum.Desc.FullName())
	for _, value := range enum.Values {
		owners[value.GoIdent.GoName] = fmt.Sprintf("enum value %s", value.Desc.FullName())
	}
}

func generateMiddlewarePlan(g *protogen.GeneratedFile, service *protogen.Service) {
	g.P("// ", service.GoName, "Middleware configures generated server middleware for ", service.Desc.FullName(), ".")
	g.P("type ", service.GoName, "Middleware struct {")
	g.P("Unary []", middlewarePackage.Ident("UnaryMiddleware"))
	g.P("Stream []", middlewarePackage.Ident("StreamMiddleware"))
	g.P("Methods ", service.GoName, "MethodMiddleware")
	g.P("}")
	g.P()
	g.P("// ", service.GoName, "MethodMiddleware configures middleware for individual RPC methods.")
	g.P("type ", service.GoName, "MethodMiddleware struct {")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P(method.GoName, " []", middlewarePackage.Ident("StreamMiddleware"))
		} else {
			g.P(method.GoName, " []", middlewarePackage.Ident("UnaryMiddleware"))
		}
	}
	g.P("}")
	g.P()
}

func generateHTTPMiddlewareWrapper(
	g *protogen.GeneratedFile,
	service *protogen.Service,
	methods []*protogen.Method,
	mode httpMode,
	declarations *serviceThrows,
) {
	wrapper := "_" + service.GoName + "HTTPMiddlewareServer"
	expectedMethodSet := 1
	if mode == httpAll {
		expectedMethodSet = 2
	}
	methodSet := "_" + service.GoName + "HTTPMethodSet"
	g.P("var _ [", methodSet, "-", expectedMethodSet, "]struct{}")
	g.P("var _ [", expectedMethodSet, "-", methodSet, "]struct{}")
	g.P()
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "HTTPServer")
	for _, method := range methods {
		if isStreaming(method) {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("UnaryHandler"))
		}
		if _, ok := declarations.byMethod[method]; ok {
			g.P("assert", method.GoName, " ", throwsPackage.Ident("Assert"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range methods {
		if isStreaming(method) {
			generateHTTPStreamAdapters(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "HTTPServer snapshots plan and composes every HTTP handler before registration.")
	served := servedDeclarations(methods, declarations)
	generateWrapperSignature(g, service, transportHTTP, service.GoName+"HTTPServer", served)
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: nil "+service.GoName+" "+transportHTTP+" server"), ") }")
	generateThrowsConfig(g, service, transportHTTP, served)
	g.P("wrapped := &", wrapper, "{", service.GoName, "HTTPServer: srv}")
	for _, method := range methods {
		generateComposeBlock(g, service, method, transportHTTP, "srv", "wrapped", declarations)
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range methods {
		generateHTTPWrapperMethod(g, service, method, wrapper, declarations)
	}
}

func generateGRPCMiddlewareWrapper(g *protogen.GeneratedFile, service *protogen.Service, declarations *serviceThrows) {
	wrapper := "_" + service.GoName + "GRPCMiddlewareServer"
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "Server")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("UnaryHandler"))
		}
		if _, ok := declarations.byMethod[method]; ok {
			g.P("assert", method.GoName, " ", throwsPackage.Ident("Assert"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if isStreaming(method) {
			generateGRPCStreamAdapter(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "GRPCServer snapshots plan and composes every gRPC handler before registration.")
	served := servedDeclarations(service.Methods, declarations)
	generateWrapperSignature(g, service, transportGRPC, service.GoName+"Server", served)
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: nil "+service.GoName+" "+transportGRPC+" server"), ") }")
	generateThrowsConfig(g, service, transportGRPC, served)
	g.P("wrapped := &", wrapper, "{", service.GoName, "Server: srv}")
	for _, method := range service.Methods {
		generateComposeBlock(g, service, method, transportGRPC, "srv", "wrapped", declarations)
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		generateGRPCWrapperMethod(g, service, method, wrapper, declarations)
	}
}

// servedDeclarations filters declarations to the methods a wrapper actually
// serves: the HTTP wrapper in annotated mode covers only annotated methods,
// so a declared-but-unserved method contributes no assertion — and no
// configuration surface — to that wrapper.
func servedDeclarations(methods []*protogen.Method, declarations *serviceThrows) *serviceThrows {
	served := &serviceThrows{byMethod: make(map[*protogen.Method][]runtimeIdentity)}
	for _, method := range declarations.declared {
		if !containsMethod(methods, method) {
			continue
		}
		served.byMethod[method] = declarations.byMethod[method]
		served.declared = append(served.declared, method)
	}
	return served
}

func containsMethod(methods []*protogen.Method, method *protogen.Method) bool {
	for _, candidate := range methods {
		if candidate == method {
			return true
		}
	}
	return false
}

// generateWrapperSignature emits the Wrap constructor's signature. A service
// with throws declarations accepts assertion options; one without keeps the
// exact signature it had before declarations existed, so undeclared services
// generate byte-identical wrappers.
func generateWrapperSignature(g *protogen.GeneratedFile, service *protogen.Service, transport, serverType string, declarations *serviceThrows) {
	name := "Wrap" + service.GoName + "HTTPServer"
	if transport == transportGRPC {
		name = "Wrap" + service.GoName + "GRPCServer"
	}
	if declarations.hasDeclarations() {
		g.P("func ", name, "(srv ", serverType, ", plan ", service.GoName, "Middleware, opts ...", throwsPackage.Ident("Option"), ") (", serverType, ", error) {")
		return
	}
	g.P("func ", name, "(srv ", serverType, ", plan ", service.GoName, "Middleware) (", serverType, ", error) {")
}

// generateThrowsConfig resolves the assertion configuration once per wrapper
// construction, covering the declared methods this wrapper serves.
func generateThrowsConfig(g *protogen.GeneratedFile, service *protogen.Service, transport string, declarations *serviceThrows) {
	if !declarations.hasDeclarations() {
		return
	}
	vars := make([]string, 0, len(declarations.declared))
	for _, method := range declarations.declared {
		vars = append(vars, declarationVar(service, method))
	}
	g.P("throwsConfig, err := ", throwsPackage.Ident("NewConfig"), "(opts, ", strings.Join(vars, ", "), ")")
	wrapErr := strconv.Quote("forge: wrapping " + string(service.Desc.FullName()) + " " + transport + ": %w")
	g.P("if err != nil { return nil, ", fmtPackage.Ident("Errorf"), "(", wrapErr, ", err) }")
}

func generateComposeBlock(
	g *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
	transport, serviceVar, wrapperVar string,
	declarations *serviceThrows,
) {
	field := "handler" + method.GoName
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	g.P("{")
	if isStreaming(method) {
		g.P("middlewares := make([]", middlewarePackage.Ident("StreamMiddleware"), ", 0, len(plan.Stream)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Stream...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeStream"), "(func(request any, stream ", middlewarePackage.Ident("ServerStream"), ") error {")
		generateStreamTerminal(g, service, method, transport, serviceVar)
		g.P("}, middlewares...)")
	} else {
		g.P("middlewares := make([]", middlewarePackage.Ident("UnaryMiddleware"), ", 0, len(plan.Unary)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Unary...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeUnary"), "(func(ctx ", contextPackage.Ident("Context"), ", request any) (any, error) {")
		g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(",
			strconv.Quote("forge: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(ctx, typed)")
		g.P("}, middlewares...)")
	}
	g.P("if err != nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: wrapping "+qualified+": %w"), ", err) }")
	g.P(wrapperVar, ".", field, " = handler")
	if _, ok := declarations.byMethod[method]; ok {
		g.P(wrapperVar, ".assert", method.GoName, " = throwsConfig.Asserter(", declarationVar(service, method), ")")
	}
	g.P("}")
}

func generateStreamTerminal(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, transport, serviceVar string) {
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	adapter := streamAdapterName(service, method, transport)
	nativeType := transportHTTPPackage.Ident("ServerStream")
	if transport == transportGRPC {
		nativeType = grpcPackage.Ident("ServerStream")
	}
	g.P("native, ok := stream.Context().Value(", adapter, "Key{}).(", nativeType, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: "+qualified+" lost native stream"), ") }")
	g.P("typedStream := &", adapter, "Typed{ServerStream: native, stream: stream}")
	if method.Desc.IsStreamingClient() {
		g.P("if request != nil { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: "+qualified+" initial request type %T, want nil"), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(typedStream)")
		return
	}
	g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(",
		strconv.Quote("forge: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
	g.P("return ", serviceVar, ".", method.GoName, "(typed, typedStream)")
}

// wrapperTransport carries the per-transport naming and types used by generateWrapperMethod.
type wrapperTransport struct {
	name         string
	wrapper      string
	streamType   string
	nativeStream protogen.GoIdent
}

func generateHTTPWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string, declarations *serviceThrows) {
	generateWrapperMethod(g, service, method, wrapperTransport{
		name:         transportHTTP,
		wrapper:      wrapper,
		streamType:   service.GoName + "_" + method.GoName + "HTTPServer",
		nativeStream: transportHTTPPackage.Ident("ServerStream"),
	}, declarations)
}

func generateGRPCWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string, declarations *serviceThrows) {
	generateWrapperMethod(g, service, method, wrapperTransport{
		name:         transportGRPC,
		wrapper:      wrapper,
		streamType:   service.GoName + "_" + method.GoName + "Server",
		nativeStream: grpcPackage.Ident("ServerStream"),
	}, declarations)
}

func generateWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, tr wrapperTransport, declarations *serviceThrows) {
	wrapper, transport, streamType, nativeStream := tr.wrapper, tr.name, tr.streamType, tr.nativeStream
	field := "handler" + method.GoName
	_, asserted := declarations.byMethod[method]
	if !isStreaming(method) {
		g.P("func (s *", wrapper, ") ", method.GoName, "(ctx ", contextPackage.Ident("Context"),
			", request *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
		g.P("reply, err := s.", field, "(ctx, request)")
		if asserted {
			g.P("if err != nil { return nil, s.assert", method.GoName, "(ctx, err) }")
		} else {
			g.P("if err != nil { return nil, err }")
		}
		g.P("typed, ok := reply.(*", method.Output.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(",
			strconv.Quote("forge: "+string(service.Desc.FullName())+"/"+string(method.Desc.Name())+
				" "+transport+" reply type %T, want *"+method.Output.GoIdent.GoName), ", reply) }")
		g.P("return typed, nil")
		g.P("}")
		g.P()
		return
	}
	adapter := streamAdapterName(service, method, transport)
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", wrapper, ") ", method.GoName, "(stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"),
			"(stream.Context(), ", adapter, "Key{}, ", nativeStream, "(stream))}")
		if asserted {
			g.P("return s.assert", method.GoName, "(base.Context(), s.", field, "(nil, base))")
		} else {
			g.P("return s.", field, "(nil, base)")
		}
	} else {
		g.P("func (s *", wrapper, ") ", method.GoName, "(request *", method.Input.GoIdent,
			", stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"),
			"(stream.Context(), ", adapter, "Key{}, ", nativeStream, "(stream))}")
		if asserted {
			g.P("return s.assert", method.GoName, "(base.Context(), s.", field, "(request, base))")
		} else {
			g.P("return s.", field, "(request, base)")
		}
	}
	g.P("}")
	g.P()
}

func generateHTTPStreamAdapters(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, transportHTTP)
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("func (s *", name, ") SendMsg(message any) error { return s.ServerStream.SendMsg(message) }")
	g.P("func (s *", name, ") RecvMsg(message any) error { return s.ServerStream.RecvMsg(message) }")
	g.P("type ", typed, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateGRPCStreamAdapter(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, transportGRPC)
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", grpcPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("type ", typed, " struct { ", grpcPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateCommonStreamDelegates(g *protogen.GeneratedFile, typeName string) {
	g.P("func (s *", typeName, ") Context() ", contextPackage.Ident("Context"), " { return s.stream.Context() }")
	g.P("func (s *", typeName, ") SendMsg(message any) error { return s.stream.SendMsg(message) }")
	g.P("func (s *", typeName, ") RecvMsg(message any) error { return s.stream.RecvMsg(message) }")
}

func generateTypedStreamMethods(g *protogen.GeneratedFile, typeName string, method *protogen.Method) {
	if method.Desc.IsStreamingServer() {
		g.P("func (s *", typeName, ") Send(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	} else {
		g.P("func (s *", typeName, ") SendAndClose(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	}
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", typeName, ") Recv() (*", method.Input.GoIdent, ", error) {")
		g.P("message := new(", method.Input.GoIdent, ")")
		g.P("if err := s.stream.RecvMsg(message); err != nil { return nil, err }")
		g.P("return message, nil")
		g.P("}")
	}
}

func enabledHTTPMethods(service *protogen.Service, mode httpMode) []*protogen.Method {
	methods := make([]*protogen.Method, 0, len(service.Methods))
	for _, method := range service.Methods {
		rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if mode != httpDisabled && (ok && rule != nil || mode == httpAll && !isStreaming(method)) {
			methods = append(methods, method)
		}
	}
	return methods
}

func streamAdapterName(service *protogen.Service, method *protogen.Method, transport string) string {
	return "_" + service.GoName + "_" + method.GoName + strings.ToUpper(transport[:1]) + transport[1:] + "MiddlewareStream"
}

func isStreaming(method *protogen.Method) bool {
	return method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer()
}
