package main

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"

	"github.com/sylphylabs/forge/cmd/internal/generator"
)

const (
	contextPackage       = protogen.GoImportPath("context")
	fmtPackage           = protogen.GoImportPath("fmt")
	middlewarePackage    = protogen.GoImportPath("github.com/sylphylabs/forge/middleware")
	transportHTTPPackage = protogen.GoImportPath("github.com/sylphylabs/forge/transport/http")
	grpcPackage          = protogen.GoImportPath("google.golang.org/grpc")
)

type httpMode uint8

const (
	httpDisabled httpMode = iota
	httpAnnotated
	httpAll
)

const (
	modeAnnotated = "annotated"
	modeAll       = "all"
)

func parseHTTPMode(value string) (httpMode, error) {
	switch value {
	case "":
		return httpDisabled, nil
	case modeAnnotated:
		return httpAnnotated, nil
	case modeAll:
		return httpAll, nil
	default:
		return httpDisabled, fmt.Errorf("go-middleware: invalid http mode %q, want %s or %s", value, modeAnnotated, modeAll)
	}
}

func generateMiddlewareFile(gen *protogen.Plugin, file *protogen.File, mode httpMode, grpcEnabled bool) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 {
		return nil, nil
	}
	if err := validateMiddlewareIdentifiers(gen, file, mode, grpcEnabled); err != nil {
		return nil, err
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_middleware.pb.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-middleware. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-middleware %s", generator.Release))
	g.P("// - protoc                   ", generator.ProtocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, service := range file.Services {
		httpMethods := enabledHTTPMethods(service, mode)
		generateMiddlewarePlan(g, service)
		if mode != httpDisabled && len(httpMethods) > 0 {
			generateHTTPMiddlewareWrapper(g, service, httpMethods, mode)
		}
		if grpcEnabled {
			generateGRPCMiddlewareWrapper(g, service)
		}
	}
	return g, nil
}

func validateMiddlewareIdentifiers(gen *protogen.Plugin, file *protogen.File, mode httpMode, grpcEnabled bool) error {
	owners := make(map[string]string)
	for _, candidate := range gen.Files {
		if !candidate.Generate || candidate.GoImportPath != file.GoImportPath {
			continue
		}
		for _, enum := range candidate.Enums {
			collectEnumIdentifiers(owners, enum)
		}
		for _, message := range candidate.Messages {
			collectMessageIdentifiers(owners, message)
		}
		for _, extension := range candidate.Extensions {
			owners["E_"+extension.GoIdent.GoName] = fmt.Sprintf("extension %s", extension.Desc.FullName())
		}
	}

	for _, service := range file.Services {
		hasHTTP := mode != httpDisabled && len(enabledHTTPMethods(service, mode)) > 0
		identifiers := []string{
			service.GoName + "Middleware",
			service.GoName + "MethodMiddleware",
		}
		if hasHTTP {
			identifiers = append(identifiers, "Wrap"+service.GoName+"HTTPServer")
		}
		if grpcEnabled {
			identifiers = append(identifiers, "Wrap"+service.GoName+"GRPCServer")
		}
		for _, identifier := range identifiers {
			if owner, ok := owners[identifier]; ok {
				return fmt.Errorf("proto %q service %s: generated middleware identifier %q conflicts with %s", file.Desc.Path(), service.Desc.FullName(), identifier, owner)
			}
			owners[identifier] = fmt.Sprintf("generated middleware for service %s", service.Desc.FullName())
		}
	}
	return nil
}

func collectMessageIdentifiers(owners map[string]string, message *protogen.Message) {
	owners[message.GoIdent.GoName] = fmt.Sprintf("message %s", message.Desc.FullName())
	for _, enum := range message.Enums {
		collectEnumIdentifiers(owners, enum)
	}
	for _, nested := range message.Messages {
		collectMessageIdentifiers(owners, nested)
	}
	for _, extension := range message.Extensions {
		owners["E_"+extension.GoIdent.GoName] = fmt.Sprintf("extension %s", extension.Desc.FullName())
	}
	for _, field := range message.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			owners[field.GoIdent.GoName] = fmt.Sprintf("oneof field %s", field.Desc.FullName())
		}
	}
}

func collectEnumIdentifiers(owners map[string]string, enum *protogen.Enum) {
	owners[enum.GoIdent.GoName] = fmt.Sprintf("enum %s", enum.Desc.FullName())
	for _, value := range enum.Values {
		owners[value.GoIdent.GoName] = fmt.Sprintf("enum value %s", value.Desc.FullName())
	}
}

func generateMiddlewarePlan(g *protogen.GeneratedFile, service *protogen.Service) {
	g.P("// ", service.GoName, "Middleware configures generated server middleware for ", service.Desc.FullName(), ".")
	g.P("type ", service.GoName, "Middleware struct {")
	g.P("Unary []", middlewarePackage.Ident("UnaryMiddleware"))
	g.P("Stream []", middlewarePackage.Ident("StreamMiddleware"))
	g.P("Methods ", service.GoName, "MethodMiddleware")
	g.P("}")
	g.P()
	g.P("// ", service.GoName, "MethodMiddleware configures middleware for individual RPC methods.")
	g.P("type ", service.GoName, "MethodMiddleware struct {")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P(method.GoName, " []", middlewarePackage.Ident("StreamMiddleware"))
		} else {
			g.P(method.GoName, " []", middlewarePackage.Ident("UnaryMiddleware"))
		}
	}
	g.P("}")
	g.P()
}

func generateHTTPMiddlewareWrapper(g *protogen.GeneratedFile, service *protogen.Service, methods []*protogen.Method, mode httpMode) {
	wrapper := "_" + service.GoName + "HTTPMiddlewareServer"
	expectedMethodSet := 1
	if mode == httpAll {
		expectedMethodSet = 2
	}
	methodSet := "_" + service.GoName + "HTTPMethodSet"
	g.P("var _ [", methodSet, "-", expectedMethodSet, "]struct{}")
	g.P("var _ [", expectedMethodSet, "-", methodSet, "]struct{}")
	g.P()
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "HTTPServer")
	for _, method := range methods {
		if isStreaming(method) {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("UnaryHandler"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range methods {
		if isStreaming(method) {
			generateHTTPStreamAdapters(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "HTTPServer snapshots plan and composes every HTTP handler before registration.")
	g.P("func Wrap", service.GoName, "HTTPServer(srv ", service.GoName, "HTTPServer, plan ", service.GoName, "Middleware) (",
		service.GoName, "HTTPServer, error) {")
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: nil "+service.GoName+" HTTP server"), ") }")
	g.P("wrapped := &", wrapper, "{", service.GoName, "HTTPServer: srv}")
	for _, method := range methods {
		generateComposeBlock(g, service, method, "HTTP", "srv", "wrapped")
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range methods {
		generateHTTPWrapperMethod(g, service, method, wrapper)
	}
}

func generateGRPCMiddlewareWrapper(g *protogen.GeneratedFile, service *protogen.Service) {
	wrapper := "_" + service.GoName + "GRPCMiddlewareServer"
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "Server")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P("handler", method.GoName, " ", middlewarePackage.Ident("UnaryHandler"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if isStreaming(method) {
			generateGRPCStreamAdapter(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "GRPCServer snapshots plan and composes every gRPC handler before registration.")
	g.P("func Wrap", service.GoName, "GRPCServer(srv ", service.GoName, "Server, plan ", service.GoName, "Middleware) (", service.GoName, "Server, error) {")
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: nil "+service.GoName+" gRPC server"), ") }")
	g.P("wrapped := &", wrapper, "{", service.GoName, "Server: srv}")
	for _, method := range service.Methods {
		generateComposeBlock(g, service, method, "gRPC", "srv", "wrapped")
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		generateGRPCWrapperMethod(g, service, method, wrapper)
	}
}

func generateComposeBlock(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, transport, serviceVar, wrapperVar string) {
	field := "handler" + method.GoName
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	g.P("{")
	if isStreaming(method) {
		g.P("middlewares := make([]", middlewarePackage.Ident("StreamMiddleware"), ", 0, len(plan.Stream)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Stream...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeStream"), "(func(request any, stream ", middlewarePackage.Ident("ServerStream"), ") error {")
		generateStreamTerminal(g, service, method, transport, serviceVar)
		g.P("}, middlewares...)")
	} else {
		g.P("middlewares := make([]", middlewarePackage.Ident("UnaryMiddleware"), ", 0, len(plan.Unary)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Unary...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeUnary"), "(func(ctx ", contextPackage.Ident("Context"), ", request any) (any, error) {")
		g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(",
			strconv.Quote("forge: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(ctx, typed)")
		g.P("}, middlewares...)")
	}
	g.P("if err != nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: wrapping "+qualified+": %w"), ", err) }")
	g.P(wrapperVar, ".", field, " = handler")
	g.P("}")
}

func generateStreamTerminal(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, transport, serviceVar string) {
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	adapter := streamAdapterName(service, method, transport)
	nativeType := transportHTTPPackage.Ident("ServerStream")
	if transport == "gRPC" {
		nativeType = grpcPackage.Ident("ServerStream")
	}
	g.P("native, ok := stream.Context().Value(", adapter, "Key{}).(", nativeType, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: "+qualified+" lost native stream"), ") }")
	g.P("typedStream := &", adapter, "Typed{ServerStream: native, stream: stream}")
	if method.Desc.IsStreamingClient() {
		g.P("if request != nil { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("forge: "+qualified+" initial request type %T, want nil"), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(typedStream)")
		return
	}
	g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(",
		strconv.Quote("forge: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
	g.P("return ", serviceVar, ".", method.GoName, "(typed, typedStream)")
}

func generateHTTPWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string) {
	generateWrapperMethod(g, service, method, wrapper, "HTTP",
		service.GoName+"_"+method.GoName+"HTTPServer", transportHTTPPackage.Ident("ServerStream"))
}

func generateGRPCWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string) {
	generateWrapperMethod(g, service, method, wrapper, "gRPC",
		service.GoName+"_"+method.GoName+"Server", grpcPackage.Ident("ServerStream"))
}

func generateWrapperMethod(
	g *protogen.GeneratedFile,
	service *protogen.Service,
	method *protogen.Method,
	wrapper, transport, streamType string,
	nativeStream protogen.GoIdent,
) {
	field := "handler" + method.GoName
	if !isStreaming(method) {
		g.P("func (s *", wrapper, ") ", method.GoName, "(ctx ", contextPackage.Ident("Context"),
			", request *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
		g.P("reply, err := s.", field, "(ctx, request)")
		g.P("if err != nil { return nil, err }")
		g.P("typed, ok := reply.(*", method.Output.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(",
			strconv.Quote("forge: "+string(service.Desc.FullName())+"/"+string(method.Desc.Name())+
				" "+transport+" reply type %T, want *"+method.Output.GoIdent.GoName), ", reply) }")
		g.P("return typed, nil")
		g.P("}")
		g.P()
		return
	}
	adapter := streamAdapterName(service, method, transport)
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", wrapper, ") ", method.GoName, "(stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"),
			"(stream.Context(), ", adapter, "Key{}, ", nativeStream, "(stream))}")
		g.P("return s.", field, "(nil, base)")
	} else {
		g.P("func (s *", wrapper, ") ", method.GoName, "(request *", method.Input.GoIdent,
			", stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"),
			"(stream.Context(), ", adapter, "Key{}, ", nativeStream, "(stream))}")
		g.P("return s.", field, "(request, base)")
	}
	g.P("}")
	g.P()
}

func generateHTTPStreamAdapters(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, "HTTP")
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("func (s *", name, ") SendMsg(message any) error { return s.ServerStream.SendMsg(message) }")
	g.P("func (s *", name, ") RecvMsg(message any) error { return s.ServerStream.RecvMsg(message) }")
	g.P("type ", typed, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateGRPCStreamAdapter(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, "gRPC")
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", grpcPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("type ", typed, " struct { ", grpcPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateCommonStreamDelegates(g *protogen.GeneratedFile, typeName string) {
	g.P("func (s *", typeName, ") Context() ", contextPackage.Ident("Context"), " { return s.stream.Context() }")
	g.P("func (s *", typeName, ") SendMsg(message any) error { return s.stream.SendMsg(message) }")
	g.P("func (s *", typeName, ") RecvMsg(message any) error { return s.stream.RecvMsg(message) }")
}

func generateTypedStreamMethods(g *protogen.GeneratedFile, typeName string, method *protogen.Method) {
	if method.Desc.IsStreamingServer() {
		g.P("func (s *", typeName, ") Send(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	} else {
		g.P("func (s *", typeName, ") SendAndClose(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	}
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", typeName, ") Recv() (*", method.Input.GoIdent, ", error) {")
		g.P("message := new(", method.Input.GoIdent, ")")
		g.P("if err := s.stream.RecvMsg(message); err != nil { return nil, err }")
		g.P("return message, nil")
		g.P("}")
	}
}

func enabledHTTPMethods(service *protogen.Service, mode httpMode) []*protogen.Method {
	methods := make([]*protogen.Method, 0, len(service.Methods))
	for _, method := range service.Methods {
		rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if mode != httpDisabled && (ok && rule != nil || mode == httpAll && !isStreaming(method)) {
			methods = append(methods, method)
		}
	}
	return methods
}

func streamAdapterName(service *protogen.Service, method *protogen.Method, transport string) string {
	return "_" + service.GoName + "_" + method.GoName + strings.ToUpper(transport[:1]) + transport[1:] + "MiddlewareStream"
}

func isStreaming(method *protogen.Method) bool {
	return method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer()
}
