// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/testdata/complex/complex.proto

package complex

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Sex int32

const (
	Sex_man   Sex = 0
	Sex_woman Sex = 1
)

// Enum value maps for Sex.
var (
	Sex_name = map[int32]string{
		0: "man",
		1: "woman",
	}
	Sex_value = map[string]int32{
		"man":   0,
		"woman": 1,
	}
)

func (x Sex) Enum() *Sex {
	p := new(Sex)
	*p = x
	return p
}

func (x Sex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sex) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_testdata_complex_complex_proto_enumTypes[0].Descriptor()
}

func (Sex) Type() protoreflect.EnumType {
	return &file_internal_testdata_complex_complex_proto_enumTypes[0]
}

func (x Sex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sex.Descriptor instead.
func (Sex) EnumDescriptor() ([]byte, []int) {
	return file_internal_testdata_complex_complex_proto_rawDescGZIP(), []int{0}
}

// SimpleMessage represents a simple message sent to the Echo service.
type Complex struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id represents the message identifier.
	Id            int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoOne         string                  `protobuf:"bytes,2,opt,name=no_one,json=numberOne,proto3" json:"no_one,omitempty"`
	Simple        *Simple                 `protobuf:"bytes,3,opt,name=simple,json=very_simple,proto3" json:"simple,omitempty"`
	Strings       []string                `protobuf:"bytes,4,rep,name=strings,proto3" json:"strings,omitempty"`
	Simples       []*Simple               `protobuf:"bytes,27,rep,name=simples,proto3" json:"simples,omitempty"`
	B             bool                    `protobuf:"varint,5,opt,name=b,proto3" json:"b,omitempty"`
	Sex           Sex                     `protobuf:"varint,6,opt,name=sex,proto3,enum=testproto.Sex" json:"sex,omitempty"`
	Age           int32                   `protobuf:"varint,7,opt,name=age,proto3" json:"age,omitempty"`
	A             uint32                  `protobuf:"varint,8,opt,name=a,proto3" json:"a,omitempty"`
	Count         uint64                  `protobuf:"varint,9,opt,name=count,proto3" json:"count,omitempty"`
	Price         float32                 `protobuf:"fixed32,10,opt,name=price,proto3" json:"price,omitempty"`
	D             float64                 `protobuf:"fixed64,11,opt,name=d,proto3" json:"d,omitempty"`
	Byte          []byte                  `protobuf:"bytes,12,opt,name=byte,proto3" json:"byte,omitempty"`
	Timestamp     *timestamppb.Timestamp  `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration      *durationpb.Duration    `protobuf:"bytes,14,opt,name=duration,proto3" json:"duration,omitempty"`
	Field         *fieldmaskpb.FieldMask  `protobuf:"bytes,15,opt,name=field,proto3" json:"field,omitempty"`
	Double        *wrapperspb.DoubleValue `protobuf:"bytes,16,opt,name=double,proto3" json:"double,omitempty"`
	Float         *wrapperspb.FloatValue  `protobuf:"bytes,17,opt,name=float,proto3" json:"float,omitempty"`
	Int64         *wrapperspb.Int64Value  `protobuf:"bytes,18,opt,name=int64,proto3" json:"int64,omitempty"`
	Int32         *wrapperspb.Int32Value  `protobuf:"bytes,19,opt,name=int32,proto3" json:"int32,omitempty"`
	Uint64        *wrapperspb.UInt64Value `protobuf:"bytes,20,opt,name=uint64,proto3" json:"uint64,omitempty"`
	Uint32        *wrapperspb.UInt32Value `protobuf:"bytes,21,opt,name=uint32,proto3" json:"uint32,omitempty"`
	Bool          *wrapperspb.BoolValue   `protobuf:"bytes,22,opt,name=bool,proto3" json:"bool,omitempty"`
	String_       *wrapperspb.StringValue `protobuf:"bytes,23,opt,name=string,proto3" json:"string,omitempty"`
	Bytes         *wrapperspb.BytesValue  `protobuf:"bytes,24,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Map           map[string]string       `protobuf:"bytes,25,rep,name=map,proto3" json:"map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MapInt64Key   map[int64]string        `protobuf:"bytes,26,rep,name=map_int64_key,proto3" json:"map_int64_key,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Complex) Reset() {
	*x = Complex{}
	mi := &file_internal_testdata_complex_complex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Complex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complex) ProtoMessage() {}

func (x *Complex) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_complex_complex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complex.ProtoReflect.Descriptor instead.
func (*Complex) Descriptor() ([]byte, []int) {
	return file_internal_testdata_complex_complex_proto_rawDescGZIP(), []int{0}
}

func (x *Complex) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Complex) GetNoOne() string {
	if x != nil {
		return x.NoOne
	}
	return ""
}

func (x *Complex) GetSimple() *Simple {
	if x != nil {
		return x.Simple
	}
	return nil
}

func (x *Complex) GetStrings() []string {
	if x != nil {
		return x.Strings
	}
	return nil
}

func (x *Complex) GetSimples() []*Simple {
	if x != nil {
		return x.Simples
	}
	return nil
}

func (x *Complex) GetB() bool {
	if x != nil {
		return x.B
	}
	return false
}

func (x *Complex) GetSex() Sex {
	if x != nil {
		return x.Sex
	}
	return Sex_man
}

func (x *Complex) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Complex) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Complex) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Complex) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Complex) GetD() float64 {
	if x != nil {
		return x.D
	}
	return 0
}

func (x *Complex) GetByte() []byte {
	if x != nil {
		return x.Byte
	}
	return nil
}

func (x *Complex) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Complex) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *Complex) GetField() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Field
	}
	return nil
}

func (x *Complex) GetDouble() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Double
	}
	return nil
}

func (x *Complex) GetFloat() *wrapperspb.FloatValue {
	if x != nil {
		return x.Float
	}
	return nil
}

func (x *Complex) GetInt64() *wrapperspb.Int64Value {
	if x != nil {
		return x.Int64
	}
	return nil
}

func (x *Complex) GetInt32() *wrapperspb.Int32Value {
	if x != nil {
		return x.Int32
	}
	return nil
}

func (x *Complex) GetUint64() *wrapperspb.UInt64Value {
	if x != nil {
		return x.Uint64
	}
	return nil
}

func (x *Complex) GetUint32() *wrapperspb.UInt32Value {
	if x != nil {
		return x.Uint32
	}
	return nil
}

func (x *Complex) GetBool() *wrapperspb.BoolValue {
	if x != nil {
		return x.Bool
	}
	return nil
}

func (x *Complex) GetString_() *wrapperspb.StringValue {
	if x != nil {
		return x.String_
	}
	return nil
}

func (x *Complex) GetBytes() *wrapperspb.BytesValue {
	if x != nil {
		return x.Bytes
	}
	return nil
}

func (x *Complex) GetMap() map[string]string {
	if x != nil {
		return x.Map
	}
	return nil
}

func (x *Complex) GetMapInt64Key() map[int64]string {
	if x != nil {
		return x.MapInt64Key
	}
	return nil
}

type Simple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Simple) Reset() {
	*x = Simple{}
	mi := &file_internal_testdata_complex_complex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Simple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Simple) ProtoMessage() {}

func (x *Simple) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_complex_complex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Simple.ProtoReflect.Descriptor instead.
func (*Simple) Descriptor() ([]byte, []int) {
	return file_internal_testdata_complex_complex_proto_rawDescGZIP(), []int{1}
}

func (x *Simple) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

var File_internal_testdata_complex_complex_proto protoreflect.FileDescriptor

const file_internal_testdata_complex_complex_proto_rawDesc = "" +
	"\n" +
	"'internal/testdata/complex/complex.proto\x12\ttestproto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb2\t\n" +
	"\aComplex\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\x06no_one\x18\x02 \x01(\tR\tnumberOne\x12.\n" +
	"\x06simple\x18\x03 \x01(\v2\x11.testproto.SimpleR\vvery_simple\x12\x18\n" +
	"\astrings\x18\x04 \x03(\tR\astrings\x12+\n" +
	"\asimples\x18\x1b \x03(\v2\x11.testproto.SimpleR\asimples\x12\f\n" +
	"\x01b\x18\x05 \x01(\bR\x01b\x12 \n" +
	"\x03sex\x18\x06 \x01(\x0e2\x0e.testproto.sexR\x03sex\x12\x10\n" +
	"\x03age\x18\a \x01(\x05R\x03age\x12\f\n" +
	"\x01a\x18\b \x01(\rR\x01a\x12\x14\n" +
	"\x05count\x18\t \x01(\x04R\x05count\x12\x14\n" +
	"\x05price\x18\n" +
	" \x01(\x02R\x05price\x12\f\n" +
	"\x01d\x18\v \x01(\x01R\x01d\x12\x12\n" +
	"\x04byte\x18\f \x01(\fR\x04byte\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x125\n" +
	"\bduration\x18\x0e \x01(\v2\x19.google.protobuf.DurationR\bduration\x120\n" +
	"\x05field\x18\x0f \x01(\v2\x1a.google.protobuf.FieldMaskR\x05field\x124\n" +
	"\x06double\x18\x10 \x01(\v2\x1c.google.protobuf.DoubleValueR\x06double\x121\n" +
	"\x05float\x18\x11 \x01(\v2\x1b.google.protobuf.FloatValueR\x05float\x121\n" +
	"\x05int64\x18\x12 \x01(\v2\x1b.google.protobuf.Int64ValueR\x05int64\x121\n" +
	"\x05int32\x18\x13 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05int32\x124\n" +
	"\x06uint64\x18\x14 \x01(\v2\x1c.google.protobuf.UInt64ValueR\x06uint64\x124\n" +
	"\x06uint32\x18\x15 \x01(\v2\x1c.google.protobuf.UInt32ValueR\x06uint32\x12.\n" +
	"\x04bool\x18\x16 \x01(\v2\x1a.google.protobuf.BoolValueR\x04bool\x124\n" +
	"\x06string\x18\x17 \x01(\v2\x1c.google.protobuf.StringValueR\x06string\x121\n" +
	"\x05bytes\x18\x18 \x01(\v2\x1b.google.protobuf.BytesValueR\x05bytes\x12-\n" +
	"\x03map\x18\x19 \x03(\v2\x1b.testproto.Complex.MapEntryR\x03map\x12I\n" +
	"\rmap_int64_key\x18\x1a \x03(\v2#.testproto.Complex.MapInt64KeyEntryR\rmap_int64_key\x1a6\n" +
	"\bMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10MapInt64KeyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x06Simple\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent*\x19\n" +
	"\x03sex\x12\a\n" +
	"\x03man\x10\x00\x12\t\n" +
	"\x05woman\x10\x01B?Z=github.com/sylphylabs/forge/internal/testdata/complex;complexb\x06proto3"

var (
	file_internal_testdata_complex_complex_proto_rawDescOnce sync.Once
	file_internal_testdata_complex_complex_proto_rawDescData []byte
)

func file_internal_testdata_complex_complex_proto_rawDescGZIP() []byte {
	file_internal_testdata_complex_complex_proto_rawDescOnce.Do(func() {
		file_internal_testdata_complex_complex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testdata_complex_complex_proto_rawDesc), len(file_internal_testdata_complex_complex_proto_rawDesc)))
	})
	return file_internal_testdata_complex_complex_proto_rawDescData
}

var file_internal_testdata_complex_complex_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_testdata_complex_complex_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_testdata_complex_complex_proto_goTypes = []any{
	(Sex)(0),                       // 0: testproto.sex
	(*Complex)(nil),                // 1: testproto.Complex
	(*Simple)(nil),                 // 2: testproto.Simple
	nil,                            // 3: testproto.Complex.MapEntry
	nil,                            // 4: testproto.Complex.MapInt64KeyEntry
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 6: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),  // 7: google.protobuf.FieldMask
	(*wrapperspb.DoubleValue)(nil), // 8: google.protobuf.DoubleValue
	(*wrapperspb.FloatValue)(nil),  // 9: google.protobuf.FloatValue
	(*wrapperspb.Int64Value)(nil),  // 10: google.protobuf.Int64Value
	(*wrapperspb.Int32Value)(nil),  // 11: google.protobuf.Int32Value
	(*wrapperspb.UInt64Value)(nil), // 12: google.protobuf.UInt64Value
	(*wrapperspb.UInt32Value)(nil), // 13: google.protobuf.UInt32Value
	(*wrapperspb.BoolValue)(nil),   // 14: google.protobuf.BoolValue
	(*wrapperspb.StringValue)(nil), // 15: google.protobuf.StringValue
	(*wrapperspb.BytesValue)(nil),  // 16: google.protobuf.BytesValue
}
var file_internal_testdata_complex_complex_proto_depIdxs = []int32{
	2,  // 0: testproto.Complex.simple:type_name -> testproto.Simple
	2,  // 1: testproto.Complex.simples:type_name -> testproto.Simple
	0,  // 2: testproto.Complex.sex:type_name -> testproto.sex
	5,  // 3: testproto.Complex.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 4: testproto.Complex.duration:type_name -> google.protobuf.Duration
	7,  // 5: testproto.Complex.field:type_name -> google.protobuf.FieldMask
	8,  // 6: testproto.Complex.double:type_name -> google.protobuf.DoubleValue
	9,  // 7: testproto.Complex.float:type_name -> google.protobuf.FloatValue
	10, // 8: testproto.Complex.int64:type_name -> google.protobuf.Int64Value
	11, // 9: testproto.Complex.int32:type_name -> google.protobuf.Int32Value
	12, // 10: testproto.Complex.uint64:type_name -> google.protobuf.UInt64Value
	13, // 11: testproto.Complex.uint32:type_name -> google.protobuf.UInt32Value
	14, // 12: testproto.Complex.bool:type_name -> google.protobuf.BoolValue
	15, // 13: testproto.Complex.string:type_name -> google.protobuf.StringValue
	16, // 14: testproto.Complex.bytes:type_name -> google.protobuf.BytesValue
	3,  // 15: testproto.Complex.map:type_name -> testproto.Complex.MapEntry
	4,  // 16: testproto.Complex.map_int64_key:type_name -> testproto.Complex.MapInt64KeyEntry
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_testdata_complex_complex_proto_init() }
func file_internal_testdata_complex_complex_proto_init() {
	if File_internal_testdata_complex_complex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testdata_complex_complex_proto_rawDesc), len(file_internal_testdata_complex_complex_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_complex_complex_proto_goTypes,
		DependencyIndexes: file_internal_testdata_complex_complex_proto_depIdxs,
		EnumInfos:         file_internal_testdata_complex_complex_proto_enumTypes,
		MessageInfos:      file_internal_testdata_complex_complex_proto_msgTypes,
	}.Build()
	File_internal_testdata_complex_complex_proto = out.File
	file_internal_testdata_complex_complex_proto_goTypes = nil
	file_internal_testdata_complex_complex_proto_depIdxs = nil
}
