syntax = "proto3";

package openkratos.test.v1;

import "openkratos/errors/v1/errors.proto";

option go_package = "example.com/openkratos/api-consumer/test/v1;testv1";

enum FailureReason {
  option (openkratos.errors.v1.default_code) = 500;

  FAILURE_REASON_UNSPECIFIED = 0;
  FAILURE_REASON_NOT_FOUND = 1 [(openkratos.errors.v1.code) = 404];
}

message GetDocumentRequest {
  string name = 1;
}

message GetDocumentReply {
  string name = 1;
}

service DocumentService {
  rpc GetDocument(GetDocumentRequest) returns (GetDocumentReply) {
    option idempotency_level = IDEMPOTENT;
  }
}
