// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test/v1/consumer.proto

package testv1

import (
	_ "github.com/sylphylabs/forge/api/errors/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED FailureReason = 0
	FailureReason_FAILURE_REASON_NOT_FOUND   FailureReason = 1
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_REASON_UNSPECIFIED",
		1: "FAILURE_REASON_NOT_FOUND",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED": 0,
		"FAILURE_REASON_NOT_FOUND":   1,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_test_v1_consumer_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_test_v1_consumer_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{0}
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_test_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDocumentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentReply) Reset() {
	*x = GetDocumentReply{}
	mi := &file_test_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentReply) ProtoMessage() {}

func (x *GetDocumentReply) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentReply.ProtoReflect.Descriptor instead.
func (*GetDocumentReply) Descriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_test_v1_consumer_proto protoreflect.FileDescriptor

const file_test_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"\x16test/v1/consumer.proto\x12\x0esylphy.test.v1\x1a\x1dsylphy/errors/v1/errors.proto\"(\n" +
	"\x12GetDocumentRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"&\n" +
	"\x10GetDocumentReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name*]\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12$\n" +
	"\x18FAILURE_REASON_NOT_FOUND\x10\x01\x1a\x06\xb0\x98\xf4\x01\x94\x03\x1a\x06\xa8\x98\xf4\x01\xf4\x032k\n" +
	"\x0fDocumentService\x12X\n" +
	"\vGetDocument\x12\".sylphy.test.v1.GetDocumentRequest\x1a .sylphy.test.v1.GetDocumentReply\"\x03\x90\x02\x02B0Z.example.com/sylphy/api-consumer/test/v1;testv1b\x06proto3"

var (
	file_test_v1_consumer_proto_rawDescOnce sync.Once
	file_test_v1_consumer_proto_rawDescData []byte
)

func file_test_v1_consumer_proto_rawDescGZIP() []byte {
	file_test_v1_consumer_proto_rawDescOnce.Do(func() {
		file_test_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_consumer_proto_rawDesc), len(file_test_v1_consumer_proto_rawDesc)))
	})
	return file_test_v1_consumer_proto_rawDescData
}

var file_test_v1_consumer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_v1_consumer_proto_goTypes = []any{
	(FailureReason)(0),         // 0: sylphy.test.v1.FailureReason
	(*GetDocumentRequest)(nil), // 1: sylphy.test.v1.GetDocumentRequest
	(*GetDocumentReply)(nil),   // 2: sylphy.test.v1.GetDocumentReply
}
var file_test_v1_consumer_proto_depIdxs = []int32{
	1, // 0: sylphy.test.v1.DocumentService.GetDocument:input_type -> sylphy.test.v1.GetDocumentRequest
	2, // 1: sylphy.test.v1.DocumentService.GetDocument:output_type -> sylphy.test.v1.GetDocumentReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_consumer_proto_init() }
func file_test_v1_consumer_proto_init() {
	if File_test_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_consumer_proto_rawDesc), len(file_test_v1_consumer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_consumer_proto_goTypes,
		DependencyIndexes: file_test_v1_consumer_proto_depIdxs,
		EnumInfos:         file_test_v1_consumer_proto_enumTypes,
		MessageInfos:      file_test_v1_consumer_proto_msgTypes,
	}.Build()
	File_test_v1_consumer_proto = out.File
	file_test_v1_consumer_proto_goTypes = nil
	file_test_v1_consumer_proto_depIdxs = nil
}
