// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: test/v1/consumer.proto

package testv1

import (
	_ "github.com/sylphylabs/forge/api/errors/v1"
	_ "github.com/sylphylabs/forge/api/openapi/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED FailureReason = 0
	FailureReason_FAILURE_REASON_NOT_FOUND   FailureReason = 1
	FailureReason_FAILURE_REASON_DENIED      FailureReason = 2
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_REASON_UNSPECIFIED",
		1: "FAILURE_REASON_NOT_FOUND",
		2: "FAILURE_REASON_DENIED",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED": 0,
		"FAILURE_REASON_NOT_FOUND":   1,
		"FAILURE_REASON_DENIED":      2,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_test_v1_consumer_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_test_v1_consumer_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{0}
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_test_v1_consumer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_consumer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *GetDocumentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDocumentReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentReply) Reset() {
	*x = GetDocumentReply{}
	mi := &file_test_v1_consumer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentReply) ProtoMessage() {}

func (x *GetDocumentReply) ProtoReflect() protoreflect.Message {
	mi := &file_test_v1_consumer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentReply.ProtoReflect.Descriptor instead.
func (*GetDocumentReply) Descriptor() ([]byte, []int) {
	return file_test_v1_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *GetDocumentReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_test_v1_consumer_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: ([]FailureReason)(nil),
		Field:         50000,
		Name:          "sylphy.test.v1.throws",
		Tag:           "varint,50000,rep,packed,name=throws,enum=sylphy.test.v1.FailureReason",
		Filename:      "test/v1/consumer.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: ([]FailureReason)(nil),
		Field:         50001,
		Name:          "sylphy.test.v1.service_throws",
		Tag:           "varint,50001,rep,packed,name=service_throws,enum=sylphy.test.v1.FailureReason",
		Filename:      "test/v1/consumer.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// repeated sylphy.test.v1.FailureReason throws = 50000;
	E_Throws = &file_test_v1_consumer_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// repeated sylphy.test.v1.FailureReason service_throws = 50001;
	E_ServiceThrows = &file_test_v1_consumer_proto_extTypes[1]
)

var File_test_v1_consumer_proto protoreflect.FileDescriptor

const file_test_v1_consumer_proto_rawDesc = "" +
	"\n" +
	"\x16test/v1/consumer.proto\x12\x0esylphy.test.v1\x1a google/protobuf/descriptor.proto\x1a\x1dsylphy/errors/v1/errors.proto\x1a#sylphy/openapi/v1/annotations.proto\"\x83\x01\n" +
	"\x12GetDocumentRequest\x12F\n" +
	"\x04name\x18\x01 \x01(\tB2\x82\xa5\xf4\x01-\n" +
	"\x1eResource name of the document.\x12\vdocuments/1R\x04name:%\xfa\xa4\xf4\x01 \n" +
	"\x1eRequest to fetch one document.\"&\n" +
	"\x10GetDocumentReply\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name*}\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12#\n" +
	"\x18FAILURE_REASON_NOT_FOUND\x10\x01\x1a\x05\xb0\x98\xf4\x01\x06\x12 \n" +
	"\x15FAILURE_REASON_DENIED\x10\x02\x1a\x05\xb0\x98\xf4\x01\x05\x1a\x05\xa8\x98\xf4\x01\x0e2\xa4\x01\n" +
	"\x0fDocumentService\x12\x89\x01\n" +
	"\vGetDocument\x12\".sylphy.test.v1.GetDocumentRequest\x1a .sylphy.test.v1.GetDocumentReply\"4\x82\xb5\x18\x01\x01\xf2\xa4\xf4\x01'\n" +
	"\x10Get one document\x1a\tdocuments*\b\n" +
	"\x06bearer\x90\x02\x02\x1a\x05\x8a\xb5\x18\x01\x02:^\n" +
	"\x06throws\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x03(\x0e2\x1d.sylphy.test.v1.FailureReasonB\x05\xb8\x98\xf4\x01\x01R\x06throws:n\n" +
	"\x0eservice_throws\x12\x1f.google.protobuf.ServiceOptions\x18ц\x03 \x03(\x0e2\x1d.sylphy.test.v1.FailureReasonB\x05\xb8\x98\xf4\x01\x01R\rserviceThrowsB\xc4\x01\xea\xa4\xf4\x01\x8e\x01\n" +
	"\fDocument API\x12\x051.0.0\x1a\x12Manages documents.\"%\n" +
	"\x17https://api.example.com\x12\n" +
	"Production*$\n" +
	"\x06bearer\x12\x13Service-issued JWT.\x1a\x05\n" +
	"\x03JWT*\x16\n" +
	"\aapi_key\"\v\n" +
	"\tX-Api-KeyZ.example.com/sylphy/api-consumer/test/v1;testv1b\x06proto3"

var (
	file_test_v1_consumer_proto_rawDescOnce sync.Once
	file_test_v1_consumer_proto_rawDescData []byte
)

func file_test_v1_consumer_proto_rawDescGZIP() []byte {
	file_test_v1_consumer_proto_rawDescOnce.Do(func() {
		file_test_v1_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_v1_consumer_proto_rawDesc), len(file_test_v1_consumer_proto_rawDesc)))
	})
	return file_test_v1_consumer_proto_rawDescData
}

var file_test_v1_consumer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_v1_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_v1_consumer_proto_goTypes = []any{
	(FailureReason)(0),                  // 0: sylphy.test.v1.FailureReason
	(*GetDocumentRequest)(nil),          // 1: sylphy.test.v1.GetDocumentRequest
	(*GetDocumentReply)(nil),            // 2: sylphy.test.v1.GetDocumentReply
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 4: google.protobuf.ServiceOptions
}
var file_test_v1_consumer_proto_depIdxs = []int32{
	3, // 0: sylphy.test.v1.throws:extendee -> google.protobuf.MethodOptions
	4, // 1: sylphy.test.v1.service_throws:extendee -> google.protobuf.ServiceOptions
	0, // 2: sylphy.test.v1.throws:type_name -> sylphy.test.v1.FailureReason
	0, // 3: sylphy.test.v1.service_throws:type_name -> sylphy.test.v1.FailureReason
	1, // 4: sylphy.test.v1.DocumentService.GetDocument:input_type -> sylphy.test.v1.GetDocumentRequest
	2, // 5: sylphy.test.v1.DocumentService.GetDocument:output_type -> sylphy.test.v1.GetDocumentReply
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_v1_consumer_proto_init() }
func file_test_v1_consumer_proto_init() {
	if File_test_v1_consumer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_v1_consumer_proto_rawDesc), len(file_test_v1_consumer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   1,
		},
		GoTypes:           file_test_v1_consumer_proto_goTypes,
		DependencyIndexes: file_test_v1_consumer_proto_depIdxs,
		EnumInfos:         file_test_v1_consumer_proto_enumTypes,
		MessageInfos:      file_test_v1_consumer_proto_msgTypes,
		ExtensionInfos:    file_test_v1_consumer_proto_extTypes,
	}.Build()
	File_test_v1_consumer_proto = out.File
	file_test_v1_consumer_proto_goTypes = nil
	file_test_v1_consumer_proto_depIdxs = nil
}
