// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/testdata/encoding/test.proto

package encoding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Hobby         []string               `protobuf:"bytes,3,rep,name=hobby,proto3" json:"hobby,omitempty"`
	Attrs         map[string]string      `protobuf:"bytes,4,rep,name=attrs,proto3" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestModel) Reset() {
	*x = TestModel{}
	mi := &file_internal_testdata_encoding_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestModel) ProtoMessage() {}

func (x *TestModel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_encoding_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestModel.ProtoReflect.Descriptor instead.
func (*TestModel) Descriptor() ([]byte, []int) {
	return file_internal_testdata_encoding_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestModel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TestModel) GetHobby() []string {
	if x != nil {
		return x.Hobby
	}
	return nil
}

func (x *TestModel) GetAttrs() map[string]string {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type StructPb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataList      []*structpb.Struct     `protobuf:"bytes,2,rep,name=data_list,json=dataList,proto3" json:"data_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StructPb) Reset() {
	*x = StructPb{}
	mi := &file_internal_testdata_encoding_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StructPb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructPb) ProtoMessage() {}

func (x *StructPb) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_encoding_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructPb.ProtoReflect.Descriptor instead.
func (*StructPb) Descriptor() ([]byte, []int) {
	return file_internal_testdata_encoding_test_proto_rawDescGZIP(), []int{1}
}

func (x *StructPb) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StructPb) GetDataList() []*structpb.Struct {
	if x != nil {
		return x.DataList
	}
	return nil
}

var File_internal_testdata_encoding_test_proto protoreflect.FileDescriptor

const file_internal_testdata_encoding_test_proto_rawDesc = "" +
	"\n" +
	"%internal/testdata/encoding/test.proto\x12\x04test\x1a\x1cgoogle/protobuf/struct.proto\"\xb3\x01\n" +
	"\n" +
	"test_model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05hobby\x18\x03 \x03(\tR\x05hobby\x121\n" +
	"\x05attrs\x18\x04 \x03(\v2\x1b.test.test_model.AttrsEntryR\x05attrs\x1a8\n" +
	"\n" +
	"AttrsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\bStructPb\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data\x124\n" +
	"\tdata_list\x18\x02 \x03(\v2\x17.google.protobuf.StructR\bdataListB\rZ\v../encodingb\x06proto3"

var (
	file_internal_testdata_encoding_test_proto_rawDescOnce sync.Once
	file_internal_testdata_encoding_test_proto_rawDescData []byte
)

func file_internal_testdata_encoding_test_proto_rawDescGZIP() []byte {
	file_internal_testdata_encoding_test_proto_rawDescOnce.Do(func() {
		file_internal_testdata_encoding_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testdata_encoding_test_proto_rawDesc), len(file_internal_testdata_encoding_test_proto_rawDesc)))
	})
	return file_internal_testdata_encoding_test_proto_rawDescData
}

var file_internal_testdata_encoding_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_testdata_encoding_test_proto_goTypes = []any{
	(*TestModel)(nil),       // 0: test.test_model
	(*StructPb)(nil),        // 1: test.StructPb
	nil,                     // 2: test.test_model.AttrsEntry
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_internal_testdata_encoding_test_proto_depIdxs = []int32{
	2, // 0: test.test_model.attrs:type_name -> test.test_model.AttrsEntry
	3, // 1: test.StructPb.data:type_name -> google.protobuf.Struct
	3, // 2: test.StructPb.data_list:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_testdata_encoding_test_proto_init() }
func file_internal_testdata_encoding_test_proto_init() {
	if File_internal_testdata_encoding_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testdata_encoding_test_proto_rawDesc), len(file_internal_testdata_encoding_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_encoding_test_proto_goTypes,
		DependencyIndexes: file_internal_testdata_encoding_test_proto_depIdxs,
		MessageInfos:      file_internal_testdata_encoding_test_proto_msgTypes,
	}.Build()
	File_internal_testdata_encoding_test_proto = out.File
	file_internal_testdata_encoding_test_proto_goTypes = nil
	file_internal_testdata_encoding_test_proto_depIdxs = nil
}
