package main

import (
	"fmt"
	"strconv"
	"strings"

	"google.golang.org/genproto/googleapis/api/annotations"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
)

const (
	middlewarePackage = protogen.GoImportPath("github.com/openkratos/kratos/middleware")
	grpcPackage       = protogen.GoImportPath("google.golang.org/grpc")
)

func generateMiddlewareFile(gen *protogen.Plugin, file *protogen.File, httpEnabled, grpcEnabled, omitHTTP bool) (*protogen.GeneratedFile, error) {
	if len(file.Services) == 0 || !httpEnabled && !grpcEnabled {
		return nil, nil
	}
	applicable := false
	for _, service := range file.Services {
		if grpcEnabled || len(enabledHTTPMethods(service, omitHTTP)) > 0 {
			applicable = true
			break
		}
	}
	if !applicable {
		return nil, nil
	}

	g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_openkratos.pb.go", file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-openkratos. DO NOT EDIT.")
	g.P("// versions:")
	g.P(fmt.Sprintf("// - protoc-gen-go-openkratos %s", release))
	g.P("// - protoc                    ", protocVersion(gen))
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, service := range file.Services {
		httpMethods := enabledHTTPMethods(service, omitHTTP)
		if !grpcEnabled && len(httpMethods) == 0 {
			continue
		}
		generateMiddlewarePlan(g, service)
		if len(httpMethods) > 0 {
			generateHTTPMiddlewareWrapper(g, service, httpMethods)
		}
		if grpcEnabled {
			generateGRPCMiddlewareWrapper(g, service)
		}
	}
	return g, nil
}

func generateMiddlewarePlan(g *protogen.GeneratedFile, service *protogen.Service) {
	g.P("// ", service.GoName, "Middleware configures generated server middleware for ", service.Desc.FullName(), ".")
	g.P("type ", service.GoName, "Middleware struct {")
	g.P("Unary []", middlewarePackage.Ident("UnaryMiddleware"))
	g.P("Stream []", middlewarePackage.Ident("StreamMiddleware"))
	g.P("Methods ", service.GoName, "MethodMiddleware")
	g.P("}")
	g.P()
	g.P("// ", service.GoName, "MethodMiddleware configures middleware for individual RPC methods.")
	g.P("type ", service.GoName, "MethodMiddleware struct {")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P(method.GoName, " []", middlewarePackage.Ident("StreamMiddleware"))
		} else {
			g.P(method.GoName, " []", middlewarePackage.Ident("UnaryMiddleware"))
		}
	}
	g.P("}")
	g.P()
}

func generateHTTPMiddlewareWrapper(g *protogen.GeneratedFile, service *protogen.Service, methods []*protogen.Method) {
	wrapper := lowerFirst(service.GoName) + "HTTPMiddlewareServer"
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "HTTPServer")
	for _, method := range methods {
		if isStreaming(method) {
			g.P(lowerFirst(method.GoName), " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P(lowerFirst(method.GoName), " ", middlewarePackage.Ident("UnaryHandler"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range methods {
		if isStreaming(method) {
			generateHTTPStreamAdapters(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "HTTPServer snapshots plan and composes every HTTP handler before registration.")
	g.P("func Wrap", service.GoName, "HTTPServer(srv ", service.GoName, "HTTPServer, plan ", service.GoName, "Middleware) (", service.GoName, "HTTPServer, error) {")
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: nil "+service.GoName+" HTTP server"), ") }")
	g.P("wrapped := &", wrapper, "{", service.GoName, "HTTPServer: srv}")
	for _, method := range methods {
		generateComposeBlock(g, service, method, "HTTP", "srv", "wrapped")
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range methods {
		generateHTTPWrapperMethod(g, service, method, wrapper)
	}
}

func generateGRPCMiddlewareWrapper(g *protogen.GeneratedFile, service *protogen.Service) {
	wrapper := lowerFirst(service.GoName) + "GRPCMiddlewareServer"
	g.P("type ", wrapper, " struct {")
	g.P(service.GoName, "Server")
	for _, method := range service.Methods {
		if isStreaming(method) {
			g.P(lowerFirst(method.GoName), " ", middlewarePackage.Ident("StreamHandler"))
		} else {
			g.P(lowerFirst(method.GoName), " ", middlewarePackage.Ident("UnaryHandler"))
		}
	}
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		if isStreaming(method) {
			generateGRPCStreamAdapter(g, service, method)
		}
	}

	g.P("// Wrap", service.GoName, "GRPCServer snapshots plan and composes every gRPC handler before registration.")
	g.P("func Wrap", service.GoName, "GRPCServer(srv ", service.GoName, "Server, plan ", service.GoName, "Middleware) (", service.GoName, "Server, error) {")
	g.P("if srv == nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: nil "+service.GoName+" gRPC server"), ") }")
	g.P("wrapped := &", wrapper, "{", service.GoName, "Server: srv}")
	for _, method := range service.Methods {
		generateComposeBlock(g, service, method, "gRPC", "srv", "wrapped")
	}
	g.P("return wrapped, nil")
	g.P("}")
	g.P()

	for _, method := range service.Methods {
		generateGRPCWrapperMethod(g, service, method, wrapper)
	}
}

func generateComposeBlock(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, transport, serviceVar, wrapperVar string) {
	field := lowerFirst(method.GoName)
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	g.P("{")
	if isStreaming(method) {
		g.P("middlewares := make([]", middlewarePackage.Ident("StreamMiddleware"), ", 0, len(plan.Stream)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Stream...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeStream"), "(func(request any, stream ", middlewarePackage.Ident("ServerStream"), ") error {")
		generateStreamTerminal(g, service, method, transport, serviceVar)
		g.P("}, middlewares...)")
	} else {
		g.P("middlewares := make([]", middlewarePackage.Ident("UnaryMiddleware"), ", 0, len(plan.Unary)+len(plan.Methods.", method.GoName, "))")
		g.P("middlewares = append(middlewares, plan.Unary...)")
		g.P("middlewares = append(middlewares, plan.Methods.", method.GoName, "...)")
		g.P("handler, err := ", middlewarePackage.Ident("ComposeUnary"), "(func(ctx ", contextPackage.Ident("Context"), ", request any) (any, error) {")
		g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(ctx, typed)")
		g.P("}, middlewares...)")
	}
	g.P("if err != nil { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: wrapping "+qualified+": %w"), ", err) }")
	g.P(wrapperVar, ".", field, " = handler")
	g.P("}")
}

func generateStreamTerminal(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, transport, serviceVar string) {
	qualified := string(service.Desc.FullName()) + "/" + string(method.Desc.Name()) + " " + transport
	adapter := streamAdapterName(service, method, transport)
	nativeType := transportHTTPPackage.Ident("ServerStream")
	if transport == "gRPC" {
		nativeType = grpcPackage.Ident("ServerStream")
	}
	g.P("native, ok := stream.Context().Value(", adapter, "Key{}).(", nativeType, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+qualified+" lost native stream"), ") }")
	g.P("typedStream := &", adapter, "Typed{ServerStream: native, stream: stream}")
	if method.Desc.IsStreamingClient() {
		g.P("if request != nil { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+qualified+" initial request type %T, want nil"), ", request) }")
		g.P("return ", serviceVar, ".", method.GoName, "(typedStream)")
		return
	}
	g.P("typed, ok := request.(*", method.Input.GoIdent, ")")
	g.P("if !ok { return ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+qualified+" request type %T, want *"+method.Input.GoIdent.GoName), ", request) }")
	g.P("return ", serviceVar, ".", method.GoName, "(typed, typedStream)")
}

func generateHTTPWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string) {
	field := lowerFirst(method.GoName)
	if !isStreaming(method) {
		g.P("func (s *", wrapper, ") ", method.GoName, "(ctx ", contextPackage.Ident("Context"), ", request *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
		g.P("reply, err := s.", field, "(ctx, request)")
		g.P("if err != nil { return nil, err }")
		g.P("typed, ok := reply.(*", method.Output.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+string(service.Desc.FullName())+"/"+string(method.Desc.Name())+" HTTP reply type %T, want *"+method.Output.GoIdent.GoName), ", reply) }")
		g.P("return typed, nil")
		g.P("}")
		g.P()
		return
	}
	streamType := service.GoName + "_" + method.GoName + "HTTPServer"
	adapter := streamAdapterName(service, method, "HTTP")
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", wrapper, ") ", method.GoName, "(stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"), "(stream.Context(), ", adapter, "Key{}, ", transportHTTPPackage.Ident("ServerStream"), "(stream))}")
		g.P("return s.", field, "(nil, base)")
	} else {
		g.P("func (s *", wrapper, ") ", method.GoName, "(request *", method.Input.GoIdent, ", stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"), "(stream.Context(), ", adapter, "Key{}, ", transportHTTPPackage.Ident("ServerStream"), "(stream))}")
		g.P("return s.", field, "(request, base)")
	}
	g.P("}")
	g.P()
}

func generateGRPCWrapperMethod(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method, wrapper string) {
	field := lowerFirst(method.GoName)
	if !isStreaming(method) {
		g.P("func (s *", wrapper, ") ", method.GoName, "(ctx ", contextPackage.Ident("Context"), ", request *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
		g.P("reply, err := s.", field, "(ctx, request)")
		g.P("if err != nil { return nil, err }")
		g.P("typed, ok := reply.(*", method.Output.GoIdent, ")")
		g.P("if !ok { return nil, ", fmtPackage.Ident("Errorf"), "(", strconv.Quote("openkratos: "+string(service.Desc.FullName())+"/"+string(method.Desc.Name())+" gRPC reply type %T, want *"+method.Output.GoIdent.GoName), ", reply) }")
		g.P("return typed, nil")
		g.P("}")
		g.P()
		return
	}
	streamType := service.GoName + "_" + method.GoName + "Server"
	adapter := streamAdapterName(service, method, "gRPC")
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", wrapper, ") ", method.GoName, "(stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"), "(stream.Context(), ", adapter, "Key{}, ", grpcPackage.Ident("ServerStream"), "(stream))}")
		g.P("return s.", field, "(nil, base)")
	} else {
		g.P("func (s *", wrapper, ") ", method.GoName, "(request *", method.Input.GoIdent, ", stream ", streamType, ") error {")
		g.P("base := &", adapter, "{ServerStream: stream, ctx: ", contextPackage.Ident("WithValue"), "(stream.Context(), ", adapter, "Key{}, ", grpcPackage.Ident("ServerStream"), "(stream))}")
		g.P("return s.", field, "(request, base)")
	}
	g.P("}")
	g.P()
}

func generateHTTPStreamAdapters(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, "HTTP")
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("func (s *", name, ") SendMsg(message any) error { return s.ServerStream.SendMsg(message) }")
	g.P("func (s *", name, ") RecvMsg(message any) error { return s.ServerStream.RecvMsg(message) }")
	g.P("type ", typed, " struct { ", transportHTTPPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateGRPCStreamAdapter(g *protogen.GeneratedFile, service *protogen.Service, method *protogen.Method) {
	name := streamAdapterName(service, method, "gRPC")
	typed := name + "Typed"
	g.P("type ", name, "Key struct{}")
	g.P("type ", name, " struct { ", grpcPackage.Ident("ServerStream"), "; ctx ", contextPackage.Ident("Context"), " }")
	g.P("func (s *", name, ") Context() ", contextPackage.Ident("Context"), " { return s.ctx }")
	g.P("type ", typed, " struct { ", grpcPackage.Ident("ServerStream"), "; stream ", middlewarePackage.Ident("ServerStream"), " }")
	generateCommonStreamDelegates(g, typed)
	generateTypedStreamMethods(g, typed, method)
	g.P()
}

func generateCommonStreamDelegates(g *protogen.GeneratedFile, typeName string) {
	g.P("func (s *", typeName, ") Context() ", contextPackage.Ident("Context"), " { return s.stream.Context() }")
	g.P("func (s *", typeName, ") SendMsg(message any) error { return s.stream.SendMsg(message) }")
	g.P("func (s *", typeName, ") RecvMsg(message any) error { return s.stream.RecvMsg(message) }")
}

func generateTypedStreamMethods(g *protogen.GeneratedFile, typeName string, method *protogen.Method) {
	if method.Desc.IsStreamingServer() {
		g.P("func (s *", typeName, ") Send(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	} else {
		g.P("func (s *", typeName, ") SendAndClose(message *", method.Output.GoIdent, ") error { return s.stream.SendMsg(message) }")
	}
	if method.Desc.IsStreamingClient() {
		g.P("func (s *", typeName, ") Recv() (*", method.Input.GoIdent, ", error) {")
		g.P("message := new(", method.Input.GoIdent, ")")
		g.P("if err := s.stream.RecvMsg(message); err != nil { return nil, err }")
		g.P("return message, nil")
		g.P("}")
	}
}

func enabledHTTPMethods(service *protogen.Service, omitHTTP bool) []*protogen.Method {
	methods := make([]*protogen.Method, 0, len(service.Methods))
	for _, method := range service.Methods {
		rule, ok := proto.GetExtension(method.Desc.Options(), annotations.E_Http).(*annotations.HttpRule)
		if ok && rule != nil || !omitHTTP && !isStreaming(method) {
			methods = append(methods, method)
		}
	}
	return methods
}

func streamAdapterName(service *protogen.Service, method *protogen.Method, transport string) string {
	return "_" + service.GoName + "_" + method.GoName + strings.ToUpper(transport[:1]) + transport[1:] + "MiddlewareStream"
}

func isStreaming(method *protogen.Method) bool {
	return method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer()
}

func lowerFirst(name string) string {
	if name == "" {
		return ""
	}
	return strings.ToLower(name[:1]) + name[1:]
}
