// Package errors defines Forge's error contract: a portable representation
// that carries a failure's category, identity, and cause across process
// boundaries without losing meaning.
//
// An error is three separable things, and this package keeps them separate:
//
//   - domain: what kind of failure this is, carried by [Kind];
//   - identity: which specific failure and whose, carried by domain and reason;
//   - diagnosis: why it happened, carried by the wrapped cause and a trace ID.
//
// A transport status code is none of these. It is a projection of [Kind],
// computed at the boundary, so that constructing an error never requires
// knowing which transport will carry it.
//
// Errors that form part of a service contract are declared in Protobuf and
// generated by protoc-gen-go-errors as immutable package-level sentinels.
// Deriving from a sentinel never mutates it:
//
//	return v1.ErrSessionNotFound.Msgf("session %q", id).Wrap(cause)
//
// Matching uses the standard library. This package adds no vocabulary of its
// own for the purpose:
//
//	if errors.Is(err, v1.ErrSessionNotFound) { ... }
package errors

import (
	"errors"
	"fmt"
	"maps"
	"strings"
)

// Error is a Forge error.
//
// It is a plain Go value with no generated machinery embedded in it. Each
// transport owns its own projection — transport/http the Problem document,
// transport/grpc the status and its details — leaving this
// package free of protocol dependencies and free to evolve independently.
//
// An Error is immutable once constructed. Every method that appears to modify
// one returns a copy, so a package-level sentinel is safe to share across
// goroutines.
//
// Every method tolerates a nil receiver: accessors return zero values, and
// deriving methods treat nil as the zero-value error, so a typed-nil *Error
// never panics.
type Error struct {
	kind   Kind
	domain string
	reason string
	msg    string
	meta   map[string]string
	trace  string
	// violations carries per-field failures for an aggregate error.
	violations []Violation
	// cause is the underlying error. It is local by construction: no transport
	// serializes it, so there is no configuration that can disclose it.
	cause error
	// remote marks an Error reconstructed from the wire. Such an error
	// describes a failure in another process, so it carries no cause and no
	// local Go values that As could mistake for its own.
	remote bool
}

// Domain namespaces the reasons owned by the framework itself, so that a
// caller can tell a failure raised by Forge from one raised by the service it
// carries.
const Domain = "forge.sylphylabs.io"

// SupportPackageIsVersion1 is referenced from generated *_errors.pb.go files
// to assert that they are compiled against a runtime that supports them. When
// a release changes what generated code requires, the constant it references
// changes with it, so a stale pairing fails to compile instead of misbehaving.
//
// It should not be referenced from any other code.
const SupportPackageIsVersion1 = true

// MustDefine returns an immutable sentinel error, panicking when the
// declaration is invalid. It is the constructor used by generated code;
// hand-written code normally declares errors in Protobuf instead, or uses [Of]
// for failures that never leave the process.
//
// It panics rather than returning an error because a sentinel is package state
// built during initialization: there is no caller yet to handle a failure, and
// an invalid declaration is a programming error rather than a runtime
// condition. Failing at init surfaces the mistake on the first run, instead of
// letting a sentinel reach the wire with an identity that [Error.Is] cannot
// match anything against. The same reasoning already governs
// [encoding.RegisterCodec].
func MustDefine(kind Kind, domain, reason string) *Error {
	switch {
	case domain == "":
		panic("forge errors: a sentinel needs a domain to be identified by")
	case reason == "":
		panic("forge errors: a sentinel needs a reason to be identified by")
	case !isScreamingSnake(reason):
		panic(fmt.Sprintf("forge errors: reason %q must be SCREAMING_SNAKE_CASE", reason))
	}
	registerContract(domain, reason)
	return &Error{kind: kind, domain: domain, reason: reason}
}

// isScreamingSnake reports whether s is a valid reason.
//
// A reason is matched as a literal by other services, so an inconsistent one is
// a wire-format defect. The rule is enforced here as well as in the generator
// because a hand-written sentinel bypasses the generator entirely.
func isScreamingSnake(s string) bool {
	for i := range len(s) {
		c := s[i]
		switch {
		case c >= 'A' && c <= 'Z':
		case c >= '0' && c <= '9', c == '_':
			// A leading digit or underscore does not name anything.
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return s != ""
}

// Of returns an error of the given Kind. Use it for failures that are internal
// to a process and therefore need no Protobuf declaration; contract errors
// should be declared in Protobuf and generated.
func Of(kind Kind) *Error {
	return &Error{kind: kind}
}

// Error implements the error interface.
//
// The formatted value includes the local cause chain, as Go wrapping errors
// conventionally do. [Error.Message] returns only the public-facing message;
// transports serialize that field and never this formatted string.
func (e *Error) Error() string {
	if e == nil {
		return "<nil>"
	}
	var b strings.Builder
	b.WriteString(e.kind.String())
	if e.domain != "" {
		b.WriteString(" ")
		b.WriteString(e.domain)
	}
	if e.reason != "" {
		if e.domain != "" {
			b.WriteString("/")
		} else {
			b.WriteString(" ")
		}
		b.WriteString(e.reason)
	}
	if e.msg != "" {
		b.WriteString(": ")
		b.WriteString(e.msg)
	}
	for _, v := range e.violations {
		b.WriteString("; ")
		b.WriteString(v.Field)
		b.WriteString(": ")
		b.WriteString(v.Description)
	}
	if e.cause != nil && e.cause.Error() != e.msg {
		b.WriteString(": ")
		b.WriteString(e.cause.Error())
	}
	return b.String()
}

// Unwrap returns the underlying cause, or nil if there is none.
//
// An error received from another process never has a cause: the chain does not
// cross a boundary. Correlate such a failure by its trace ID, and read the
// unredacted detail in the producing service's logs.
func (e *Error) Unwrap() error {
	if e == nil {
		return nil
	}
	return e.cause
}

// Is reports whether target identifies the same failure as e.
//
// Identity is the complete domain and reason pair: two errors match exactly
// when both carry the same non-empty domain and the same non-empty reason. An
// error missing either half has no cross-instance identity and matches only
// itself — the standard library compares values before calling this method —
// so two anonymous errors of one Kind never match each other. Classifying by
// Kind is [KindOf]'s job.
//
// Kind and message deliberately do not participate. The message is
// descriptive and may be interpolated per occurrence, and the Kind is a
// classification a transport boundary may recompute in transit, so neither
// can be allowed to separate two reports of the same failure.
func (e *Error) Is(target error) bool {
	t, ok := target.(*Error)
	if !ok || t == nil || e == nil {
		return false
	}
	return e.domain != "" && e.reason != "" &&
		e.domain == t.domain && e.reason == t.reason
}

// Kind returns the error's category.
func (e *Error) Kind() Kind {
	if e == nil {
		return KindUnknown
	}
	return e.kind
}

// Domain returns the namespace that owns the reason, normally the Protobuf
// package that declared it.
func (e *Error) Domain() string {
	if e == nil {
		return ""
	}
	return e.domain
}

// Reason returns the stable machine-readable identifier for this failure.
func (e *Error) Reason() string {
	if e == nil {
		return ""
	}
	return e.reason
}

// Message returns the human-readable description.
func (e *Error) Message() string {
	if e == nil {
		return ""
	}
	return e.msg
}

// Metadata returns a copy of the error's metadata. The copy keeps a caller from
// mutating a shared sentinel.
func (e *Error) Metadata() map[string]string {
	if e == nil || len(e.meta) == 0 {
		return nil
	}
	return maps.Clone(e.meta)
}

// TraceID returns the trace this error was produced in, or the empty string.
// It is the supported way to correlate a failure across process boundaries.
func (e *Error) TraceID() string {
	if e == nil {
		return ""
	}
	return e.trace
}

// Violations returns the per-field failures of an aggregate error.
func (e *Error) Violations() []Violation {
	if e == nil || len(e.violations) == 0 {
		return nil
	}
	return append([]Violation(nil), e.violations...)
}

// IsRemote reports whether this error was reconstructed from the wire rather
// than produced in this process.
func (e *Error) IsRemote() bool {
	return e != nil && e.remote
}

// clone returns a shallow copy with independently owned maps and slices.
//
// A nil receiver clones as the zero-value error. The accessors already treat a
// typed-nil as that value — Kind returns KindUnknown, everything else its zero
// — so the deriving methods built on clone stay consistent with them instead
// of panicking.
func (e *Error) clone() *Error {
	if e == nil {
		return new(Error)
	}
	c := *e
	c.meta = maps.Clone(e.meta)
	if e.violations != nil {
		c.violations = append([]Violation(nil), e.violations...)
	}
	return &c
}

// Msg returns a copy of e with the given message.
func (e *Error) Msg(message string) *Error {
	c := e.clone()
	c.msg = message
	return c
}

// Msgf returns a copy of e with a formatted message.
func (e *Error) Msgf(format string, a ...any) *Error {
	c := e.clone()
	c.msg = fmt.Sprintf(format, a...)
	return c
}

// Wrap returns a copy of e recording cause as the underlying error.
//
// Prefer it over folding cause.Error() into the message: the message is for
// humans, the cause is for [errors.Is] and [errors.As]. Wrapping a nil cause is
// a no-op, so a call site need not branch on it.
func (e *Error) Wrap(cause error) *Error {
	if cause == nil {
		return e
	}
	c := e.clone()
	c.cause = cause
	return c
}

// Meta returns a copy of e with one metadata entry set.
func (e *Error) Meta(key, value string) *Error {
	c := e.clone()
	if c.meta == nil {
		c.meta = make(map[string]string, 1)
	}
	c.meta[key] = value
	return c
}

// WithMetadata returns a copy of e with the given metadata merged in.
func (e *Error) WithMetadata(md map[string]string) *Error {
	c := e.clone()
	if len(md) == 0 {
		return c
	}
	if c.meta == nil {
		c.meta = make(map[string]string, len(md))
	}
	maps.Copy(c.meta, md)
	return c
}

// WithTraceID returns a copy of e carrying the given trace identifier.
func (e *Error) WithTraceID(id string) *Error {
	c := e.clone()
	c.trace = id
	return c
}

// WithReason returns a copy of e with the given reason. It is intended for
// errors that are internal to a process; contract errors carry a reason from
// their Protobuf declaration.
func (e *Error) WithReason(reason string) *Error {
	c := e.clone()
	c.reason = reason
	return c
}

// WithDomain returns a copy of e with the given domain.
func (e *Error) WithDomain(domain string) *Error {
	c := e.clone()
	c.domain = domain
	return c
}

// KindOf returns the Kind of any error.
//
// It returns KindUnknown for a nil error and for any error that did not
// originate from this package. Recognizing a foreign error — a gRPC status, an
// HTTP response — belongs to the transport that received it, which converts
// before the error reaches application code. It never panics, including for a
// typed-nil *Error.
func KindOf(err error) Kind {
	if err == nil {
		return KindUnknown
	}
	var e *Error
	if errors.As(err, &e) {
		return e.Kind() // nil-safe
	}
	return KindUnknown
}

// ReasonOf returns the reason of any error, or the empty string when it has
// none.
func ReasonOf(err error) string {
	if err == nil {
		return ""
	}
	var e *Error
	if errors.As(err, &e) {
		return e.Reason() // nil-safe
	}
	return ""
}

// DomainOf returns the domain of any error, or the empty string when it has
// none.
func DomainOf(err error) string {
	if err == nil {
		return ""
	}
	var e *Error
	if errors.As(err, &e) {
		return e.Domain() // nil-safe
	}
	return ""
}

// FromError converts any error into an *Error.
//
// It returns nil only for a nil error. An error that did not originate from
// this package is reported as KindUnknown, wrapped so its own type remains
// reachable with [errors.As].
func FromError(err error) *Error {
	if err == nil {
		return nil
	}
	var e *Error
	if errors.As(err, &e) {
		if e == nil {
			// A typed-nil *Error carries no information but must not be
			// mistaken for the absence of an error.
			return Of(KindUnknown).Msg(err.Error())
		}
		return e
	}
	return Of(KindUnknown).Msg(err.Error()).Wrap(err)
}
