// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openkratos/policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Access declares the identity and authorization requirement for an operation.
type Access int32

const (
	Access_ACCESS_UNSPECIFIED   Access = 0
	Access_ACCESS_PUBLIC        Access = 1
	Access_ACCESS_AUTHENTICATED Access = 2
	Access_ACCESS_AUTHORIZED    Access = 3
)

// Enum value maps for Access.
var (
	Access_name = map[int32]string{
		0: "ACCESS_UNSPECIFIED",
		1: "ACCESS_PUBLIC",
		2: "ACCESS_AUTHENTICATED",
		3: "ACCESS_AUTHORIZED",
	}
	Access_value = map[string]int32{
		"ACCESS_UNSPECIFIED":   0,
		"ACCESS_PUBLIC":        1,
		"ACCESS_AUTHENTICATED": 2,
		"ACCESS_AUTHORIZED":    3,
	}
)

func (x Access) Enum() *Access {
	p := new(Access)
	*p = x
	return p
}

func (x Access) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Access) Descriptor() protoreflect.EnumDescriptor {
	return file_openkratos_policy_v1_policy_proto_enumTypes[0].Descriptor()
}

func (Access) Type() protoreflect.EnumType {
	return &file_openkratos_policy_v1_policy_proto_enumTypes[0]
}

func (x Access) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Access.Descriptor instead.
func (Access) EnumDescriptor() ([]byte, []int) {
	return file_openkratos_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

// PermissionPolicy declares permissions required by an authorized operation.
type PermissionPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequireAll    []string               `protobuf:"bytes,1,rep,name=require_all,json=requireAll,proto3" json:"require_all,omitempty"`
	RequireAny    []string               `protobuf:"bytes,2,rep,name=require_any,json=requireAny,proto3" json:"require_any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionPolicy) Reset() {
	*x = PermissionPolicy{}
	mi := &file_openkratos_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionPolicy) ProtoMessage() {}

func (x *PermissionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openkratos_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionPolicy.ProtoReflect.Descriptor instead.
func (*PermissionPolicy) Descriptor() ([]byte, []int) {
	return file_openkratos_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *PermissionPolicy) GetRequireAll() []string {
	if x != nil {
		return x.RequireAll
	}
	return nil
}

func (x *PermissionPolicy) GetRequireAny() []string {
	if x != nil {
		return x.RequireAny
	}
	return nil
}

// OperationPolicy declares portable operation requirements. Named classes are
// resolved to application-owned implementations during service registration.
type OperationPolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Access           *Access                `protobuf:"varint,1,opt,name=access,proto3,enum=openkratos.policy.v1.Access,oneof" json:"access,omitempty"`
	Permissions      *PermissionPolicy      `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	ValidateRequest  *bool                  `protobuf:"varint,3,opt,name=validate_request,json=validateRequest,proto3,oneof" json:"validate_request,omitempty"`
	Audit            *bool                  `protobuf:"varint,4,opt,name=audit,proto3,oneof" json:"audit,omitempty"`
	IdempotencyClass *string                `protobuf:"bytes,5,opt,name=idempotency_class,json=idempotencyClass,proto3,oneof" json:"idempotency_class,omitempty"`
	RateClass        *string                `protobuf:"bytes,6,opt,name=rate_class,json=rateClass,proto3,oneof" json:"rate_class,omitempty"`
	BudgetClass      *string                `protobuf:"bytes,7,opt,name=budget_class,json=budgetClass,proto3,oneof" json:"budget_class,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationPolicy) Reset() {
	*x = OperationPolicy{}
	mi := &file_openkratos_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationPolicy) ProtoMessage() {}

func (x *OperationPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openkratos_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationPolicy.ProtoReflect.Descriptor instead.
func (*OperationPolicy) Descriptor() ([]byte, []int) {
	return file_openkratos_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *OperationPolicy) GetAccess() Access {
	if x != nil && x.Access != nil {
		return *x.Access
	}
	return Access_ACCESS_UNSPECIFIED
}

func (x *OperationPolicy) GetPermissions() *PermissionPolicy {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *OperationPolicy) GetValidateRequest() bool {
	if x != nil && x.ValidateRequest != nil {
		return *x.ValidateRequest
	}
	return false
}

func (x *OperationPolicy) GetAudit() bool {
	if x != nil && x.Audit != nil {
		return *x.Audit
	}
	return false
}

func (x *OperationPolicy) GetIdempotencyClass() string {
	if x != nil && x.IdempotencyClass != nil {
		return *x.IdempotencyClass
	}
	return ""
}

func (x *OperationPolicy) GetRateClass() string {
	if x != nil && x.RateClass != nil {
		return *x.RateClass
	}
	return ""
}

func (x *OperationPolicy) GetBudgetClass() string {
	if x != nil && x.BudgetClass != nil {
		return *x.BudgetClass
	}
	return ""
}

var file_openkratos_policy_v1_policy_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*OperationPolicy)(nil),
		Field:         500201,
		Name:          "openkratos.policy.v1.default_policy",
		Tag:           "bytes,500201,opt,name=default_policy",
		Filename:      "openkratos/policy/v1/policy.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*OperationPolicy)(nil),
		Field:         500202,
		Name:          "openkratos.policy.v1.policy",
		Tag:           "bytes,500202,opt,name=policy",
		Filename:      "openkratos/policy/v1/policy.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional openkratos.policy.v1.OperationPolicy default_policy = 500201;
	E_DefaultPolicy = &file_openkratos_policy_v1_policy_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional openkratos.policy.v1.OperationPolicy policy = 500202;
	E_Policy = &file_openkratos_policy_v1_policy_proto_extTypes[1]
)

var File_openkratos_policy_v1_policy_proto protoreflect.FileDescriptor

const file_openkratos_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"!openkratos/policy/v1/policy.proto\x12\x14openkratos.policy.v1\x1a google/protobuf/descriptor.proto\"T\n" +
	"\x10PermissionPolicy\x12\x1f\n" +
	"\vrequire_all\x18\x01 \x03(\tR\n" +
	"requireAll\x12\x1f\n" +
	"\vrequire_any\x18\x02 \x03(\tR\n" +
	"requireAny\"\xbf\x03\n" +
	"\x0fOperationPolicy\x129\n" +
	"\x06access\x18\x01 \x01(\x0e2\x1c.openkratos.policy.v1.AccessH\x00R\x06access\x88\x01\x01\x12H\n" +
	"\vpermissions\x18\x02 \x01(\v2&.openkratos.policy.v1.PermissionPolicyR\vpermissions\x12.\n" +
	"\x10validate_request\x18\x03 \x01(\bH\x01R\x0fvalidateRequest\x88\x01\x01\x12\x19\n" +
	"\x05audit\x18\x04 \x01(\bH\x02R\x05audit\x88\x01\x01\x120\n" +
	"\x11idempotency_class\x18\x05 \x01(\tH\x03R\x10idempotencyClass\x88\x01\x01\x12\"\n" +
	"\n" +
	"rate_class\x18\x06 \x01(\tH\x04R\trateClass\x88\x01\x01\x12&\n" +
	"\fbudget_class\x18\a \x01(\tH\x05R\vbudgetClass\x88\x01\x01B\t\n" +
	"\a_accessB\x13\n" +
	"\x11_validate_requestB\b\n" +
	"\x06_auditB\x14\n" +
	"\x12_idempotency_classB\r\n" +
	"\v_rate_classB\x0f\n" +
	"\r_budget_class*d\n" +
	"\x06Access\x12\x16\n" +
	"\x12ACCESS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rACCESS_PUBLIC\x10\x01\x12\x18\n" +
	"\x14ACCESS_AUTHENTICATED\x10\x02\x12\x15\n" +
	"\x11ACCESS_AUTHORIZED\x10\x03:o\n" +
	"\x0edefault_policy\x12\x1f.google.protobuf.ServiceOptions\x18\xe9\xc3\x1e \x01(\v2%.openkratos.policy.v1.OperationPolicyR\rdefaultPolicy:_\n" +
	"\x06policy\x12\x1e.google.protobuf.MethodOptions\x18\xea\xc3\x1e \x01(\v2%.openkratos.policy.v1.OperationPolicyR\x06policyBQ\n" +
	"\x1fcom.github.openkratos.policy.v1P\x01Z,github.com/openkratos/api/policy/v1;policyv1b\x06proto3"

var (
	file_openkratos_policy_v1_policy_proto_rawDescOnce sync.Once
	file_openkratos_policy_v1_policy_proto_rawDescData []byte
)

func file_openkratos_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_openkratos_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_openkratos_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openkratos_policy_v1_policy_proto_rawDesc), len(file_openkratos_policy_v1_policy_proto_rawDesc)))
	})
	return file_openkratos_policy_v1_policy_proto_rawDescData
}

var file_openkratos_policy_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_openkratos_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_openkratos_policy_v1_policy_proto_goTypes = []any{
	(Access)(0),                         // 0: openkratos.policy.v1.Access
	(*PermissionPolicy)(nil),            // 1: openkratos.policy.v1.PermissionPolicy
	(*OperationPolicy)(nil),             // 2: openkratos.policy.v1.OperationPolicy
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 4: google.protobuf.MethodOptions
}
var file_openkratos_policy_v1_policy_proto_depIdxs = []int32{
	0, // 0: openkratos.policy.v1.OperationPolicy.access:type_name -> openkratos.policy.v1.Access
	1, // 1: openkratos.policy.v1.OperationPolicy.permissions:type_name -> openkratos.policy.v1.PermissionPolicy
	3, // 2: openkratos.policy.v1.default_policy:extendee -> google.protobuf.ServiceOptions
	4, // 3: openkratos.policy.v1.policy:extendee -> google.protobuf.MethodOptions
	2, // 4: openkratos.policy.v1.default_policy:type_name -> openkratos.policy.v1.OperationPolicy
	2, // 5: openkratos.policy.v1.policy:type_name -> openkratos.policy.v1.OperationPolicy
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_openkratos_policy_v1_policy_proto_init() }
func file_openkratos_policy_v1_policy_proto_init() {
	if File_openkratos_policy_v1_policy_proto != nil {
		return
	}
	file_openkratos_policy_v1_policy_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openkratos_policy_v1_policy_proto_rawDesc), len(file_openkratos_policy_v1_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_openkratos_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_openkratos_policy_v1_policy_proto_depIdxs,
		EnumInfos:         file_openkratos_policy_v1_policy_proto_enumTypes,
		MessageInfos:      file_openkratos_policy_v1_policy_proto_msgTypes,
		ExtensionInfos:    file_openkratos_policy_v1_policy_proto_extTypes,
	}.Build()
	File_openkratos_policy_v1_policy_proto = out.File
	file_openkratos_policy_v1_policy_proto_goTypes = nil
	file_openkratos_policy_v1_policy_proto_depIdxs = nil
}
