// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: internal/testdata/binding/test.proto

package binding

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sub           *Sub                   `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	OptInt32      *int32                 `protobuf:"varint,4,opt,name=opt_int32,json=optInt32,proto3,oneof" json:"opt_int32,omitempty"`
	OptInt64      *int64                 `protobuf:"varint,5,opt,name=opt_int64,json=optInt64,proto3,oneof" json:"opt_int64,omitempty"`
	OptString     *string                `protobuf:"bytes,6,opt,name=opt_string,json=optString,proto3,oneof" json:"opt_string,omitempty"`
	SubField      *Sub                   `protobuf:"bytes,7,opt,name=subField,proto3" json:"subField,omitempty"`
	TestRepeated  []string               `protobuf:"bytes,8,rep,name=test_repeated,proto3" json:"test_repeated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_internal_testdata_binding_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_binding_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_internal_testdata_binding_test_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetSub() *Sub {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *HelloRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *HelloRequest) GetOptInt32() int32 {
	if x != nil && x.OptInt32 != nil {
		return *x.OptInt32
	}
	return 0
}

func (x *HelloRequest) GetOptInt64() int64 {
	if x != nil && x.OptInt64 != nil {
		return *x.OptInt64
	}
	return 0
}

func (x *HelloRequest) GetOptString() string {
	if x != nil && x.OptString != nil {
		return *x.OptString
	}
	return ""
}

func (x *HelloRequest) GetSubField() *Sub {
	if x != nil {
		return x.SubField
	}
	return nil
}

func (x *HelloRequest) GetTestRepeated() []string {
	if x != nil {
		return x.TestRepeated
	}
	return nil
}

type Sub struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,json=naming,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sub) Reset() {
	*x = Sub{}
	mi := &file_internal_testdata_binding_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sub) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sub) ProtoMessage() {}

func (x *Sub) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testdata_binding_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sub.ProtoReflect.Descriptor instead.
func (*Sub) Descriptor() ([]byte, []int) {
	return file_internal_testdata_binding_test_proto_rawDescGZIP(), []int{1}
}

func (x *Sub) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_internal_testdata_binding_test_proto protoreflect.FileDescriptor

const file_internal_testdata_binding_test_proto_rawDesc = "" +
	"\n" +
	"$internal/testdata/binding/test.proto\x12\abinding\x1a google/protobuf/field_mask.proto\"\xe2\x02\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\x03sub\x18\x02 \x01(\v2\f.binding.SubR\x03sub\x12;\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12 \n" +
	"\topt_int32\x18\x04 \x01(\x05H\x00R\boptInt32\x88\x01\x01\x12 \n" +
	"\topt_int64\x18\x05 \x01(\x03H\x01R\boptInt64\x88\x01\x01\x12\"\n" +
	"\n" +
	"opt_string\x18\x06 \x01(\tH\x02R\toptString\x88\x01\x01\x12(\n" +
	"\bsubField\x18\a \x01(\v2\f.binding.SubR\bsubField\x12$\n" +
	"\rtest_repeated\x18\b \x03(\tR\rtest_repeatedB\f\n" +
	"\n" +
	"_opt_int32B\f\n" +
	"\n" +
	"_opt_int64B\r\n" +
	"\v_opt_string\"\x1b\n" +
	"\x03Sub\x12\x14\n" +
	"\x04name\x18\x01 \x01(\tR\x06namingB7Z5github.com/sylphylabs/forge/internal/testdata/bindingb\x06proto3"

var (
	file_internal_testdata_binding_test_proto_rawDescOnce sync.Once
	file_internal_testdata_binding_test_proto_rawDescData []byte
)

func file_internal_testdata_binding_test_proto_rawDescGZIP() []byte {
	file_internal_testdata_binding_test_proto_rawDescOnce.Do(func() {
		file_internal_testdata_binding_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testdata_binding_test_proto_rawDesc), len(file_internal_testdata_binding_test_proto_rawDesc)))
	})
	return file_internal_testdata_binding_test_proto_rawDescData
}

var file_internal_testdata_binding_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testdata_binding_test_proto_goTypes = []any{
	(*HelloRequest)(nil),          // 0: binding.HelloRequest
	(*Sub)(nil),                   // 1: binding.Sub
	(*fieldmaskpb.FieldMask)(nil), // 2: google.protobuf.FieldMask
}
var file_internal_testdata_binding_test_proto_depIdxs = []int32{
	1, // 0: binding.HelloRequest.sub:type_name -> binding.Sub
	2, // 1: binding.HelloRequest.update_mask:type_name -> google.protobuf.FieldMask
	1, // 2: binding.HelloRequest.subField:type_name -> binding.Sub
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_testdata_binding_test_proto_init() }
func file_internal_testdata_binding_test_proto_init() {
	if File_internal_testdata_binding_test_proto != nil {
		return
	}
	file_internal_testdata_binding_test_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testdata_binding_test_proto_rawDesc), len(file_internal_testdata_binding_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_testdata_binding_test_proto_goTypes,
		DependencyIndexes: file_internal_testdata_binding_test_proto_depIdxs,
		MessageInfos:      file_internal_testdata_binding_test_proto_msgTypes,
	}.Build()
	File_internal_testdata_binding_test_proto = out.File
	file_internal_testdata_binding_test_proto_goTypes = nil
	file_internal_testdata_binding_test_proto_depIdxs = nil
}
