// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sylphy/openapi/v1/annotations.proto

package openapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Document supplies document-level metadata for a generated OpenAPI document.
//
//	option (sylphy.openapi.v1.document) = {
//	  title: "Library API"
//	  version: "1.2.3"
//	  servers: {url: "https://api.example.com"}
//	};
//
// title, version, and description override the generator's corresponding
// plugin options when set. In merged output mode the annotations of all
// generated files are combined: scalar fields are last-writer-wins in file
// order, servers and security schemes accumulate.
type Document struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// title of the API, emitted as info.title.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// version of the API, emitted as info.version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// description of the API, emitted as info.description.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// servers the API is served on, emitted as the document servers list.
	Servers []*Server `protobuf:"bytes,4,rep,name=servers,proto3" json:"servers,omitempty"`
	// security_schemes defines the named security schemes operation-level
	// security requirements reference. Emitted under
	// components.securitySchemes. A requirement naming a scheme no document
	// annotation defines fails generation.
	SecuritySchemes []*SecurityScheme `protobuf:"bytes,5,rep,name=security_schemes,json=securitySchemes,proto3" json:"security_schemes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Document) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Document) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *Document) GetSecuritySchemes() []*SecurityScheme {
	if x != nil {
		return x.SecuritySchemes
	}
	return nil
}

// Server is one server the API is available at.
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// url of the server.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// description of the server.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Server) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Operation supplies presentation metadata for one method's operation.
//
//	rpc GetBook(GetBookRequest) returns (Book) {
//	  option (google.api.http) = {get: "/v1/books/{name}"};
//	  option (sylphy.openapi.v1.operation) = {
//	    summary: "Get one book"
//	    tags: "books"
//	    security: {schemes: "bearer"}
//	  };
//	}
//
// Responses are deliberately absent: error responses come from
// sylphy.errors.v1 throws declarations and success responses from the method
// signature, so there is no annotation through which documentation can drift
// from the contract.
type Operation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// summary of the operation.
	Summary string `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	// description of the operation; overrides the method's leading comment
	// when set.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// tags of the operation; replaces the generated default (the service name)
	// when set.
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// deprecated marks the operation deprecated.
	Deprecated bool `protobuf:"varint,4,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// security lists the operation's alternative security requirements: a
	// request must satisfy every scheme of one requirement (AND within a
	// requirement, OR across requirements). An empty requirement makes
	// authentication optional, per OpenAPI semantics.
	Security      []*SecurityRequirement `protobuf:"bytes,5,rep,name=security,proto3" json:"security,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *Operation) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Operation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Operation) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Operation) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *Operation) GetSecurity() []*SecurityRequirement {
	if x != nil {
		return x.Security
	}
	return nil
}

// Schema supplies presentation metadata for one message's schema.
type Schema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description of the schema; overrides the message's leading comment
	// when set.
	Description   string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Schema) Reset() {
	*x = Schema{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Schema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Schema) ProtoMessage() {}

func (x *Schema) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Schema.ProtoReflect.Descriptor instead.
func (*Schema) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *Schema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Field supplies presentation metadata for one field's property schema.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// description of the property; overrides the field's leading comment
	// when set.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// example of the property, emitted as a string value.
	Example string `protobuf:"bytes,2,opt,name=example,proto3" json:"example,omitempty"`
	// format of the property; overrides the format derived from the field's
	// protobuf type.
	Format        string `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{4}
}

func (x *Field) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Field) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

func (x *Field) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// SecurityScheme defines one named security scheme. The v1 vocabulary covers
// the two most common forms — HTTP bearer and API key in a header — and other
// forms are added append-only when a need is proven.
type SecurityScheme struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the component key requirements reference.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of the scheme.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Types that are valid to be assigned to Scheme:
	//
	//	*SecurityScheme_HttpBearer
	//	*SecurityScheme_ApiKeyHeader
	Scheme        isSecurityScheme_Scheme `protobuf_oneof:"scheme"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityScheme) Reset() {
	*x = SecurityScheme{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityScheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityScheme) ProtoMessage() {}

func (x *SecurityScheme) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityScheme.ProtoReflect.Descriptor instead.
func (*SecurityScheme) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityScheme) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecurityScheme) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SecurityScheme) GetScheme() isSecurityScheme_Scheme {
	if x != nil {
		return x.Scheme
	}
	return nil
}

func (x *SecurityScheme) GetHttpBearer() *HTTPBearer {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_HttpBearer); ok {
			return x.HttpBearer
		}
	}
	return nil
}

func (x *SecurityScheme) GetApiKeyHeader() *APIKeyHeader {
	if x != nil {
		if x, ok := x.Scheme.(*SecurityScheme_ApiKeyHeader); ok {
			return x.ApiKeyHeader
		}
	}
	return nil
}

type isSecurityScheme_Scheme interface {
	isSecurityScheme_Scheme()
}

type SecurityScheme_HttpBearer struct {
	// http_bearer is an HTTP authentication scheme with the Bearer method
	// (type: http, scheme: bearer).
	HttpBearer *HTTPBearer `protobuf:"bytes,3,opt,name=http_bearer,json=httpBearer,proto3,oneof"`
}

type SecurityScheme_ApiKeyHeader struct {
	// api_key_header is an API key carried in a request header
	// (type: apiKey, in: header).
	ApiKeyHeader *APIKeyHeader `protobuf:"bytes,4,opt,name=api_key_header,json=apiKeyHeader,proto3,oneof"`
}

func (*SecurityScheme_HttpBearer) isSecurityScheme_Scheme() {}

func (*SecurityScheme_ApiKeyHeader) isSecurityScheme_Scheme() {}

// HTTPBearer configures an HTTP bearer security scheme.
type HTTPBearer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bearer_format is a hint naming how the bearer token is formatted,
	// for example "JWT".
	BearerFormat  string `protobuf:"bytes,1,opt,name=bearer_format,json=bearerFormat,proto3" json:"bearer_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPBearer) Reset() {
	*x = HTTPBearer{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPBearer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPBearer) ProtoMessage() {}

func (x *HTTPBearer) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPBearer.ProtoReflect.Descriptor instead.
func (*HTTPBearer) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{6}
}

func (x *HTTPBearer) GetBearerFormat() string {
	if x != nil {
		return x.BearerFormat
	}
	return ""
}

// APIKeyHeader configures an API key security scheme carried in a header.
type APIKeyHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// header is the name of the header carrying the key.
	Header        string `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIKeyHeader) Reset() {
	*x = APIKeyHeader{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIKeyHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIKeyHeader) ProtoMessage() {}

func (x *APIKeyHeader) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIKeyHeader.ProtoReflect.Descriptor instead.
func (*APIKeyHeader) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{7}
}

func (x *APIKeyHeader) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

// SecurityRequirement names the schemes a request must satisfy together.
type SecurityRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// schemes are names of security schemes defined by a Document annotation.
	Schemes       []string `protobuf:"bytes,1,rep,name=schemes,proto3" json:"schemes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequirement) Reset() {
	*x = SecurityRequirement{}
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequirement) ProtoMessage() {}

func (x *SecurityRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_sylphy_openapi_v1_annotations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequirement.ProtoReflect.Descriptor instead.
func (*SecurityRequirement) Descriptor() ([]byte, []int) {
	return file_sylphy_openapi_v1_annotations_proto_rawDescGZIP(), []int{8}
}

func (x *SecurityRequirement) GetSchemes() []string {
	if x != nil {
		return x.Schemes
	}
	return nil
}

var file_sylphy_openapi_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*Document)(nil),
		Field:         500301,
		Name:          "sylphy.openapi.v1.document",
		Tag:           "bytes,500301,opt,name=document",
		Filename:      "sylphy/openapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Operation)(nil),
		Field:         500302,
		Name:          "sylphy.openapi.v1.operation",
		Tag:           "bytes,500302,opt,name=operation",
		Filename:      "sylphy/openapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*Schema)(nil),
		Field:         500303,
		Name:          "sylphy.openapi.v1.schema",
		Tag:           "bytes,500303,opt,name=schema",
		Filename:      "sylphy/openapi/v1/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*Field)(nil),
		Field:         500304,
		Name:          "sylphy.openapi.v1.field",
		Tag:           "bytes,500304,opt,name=field",
		Filename:      "sylphy/openapi/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional sylphy.openapi.v1.Document document = 500301;
	E_Document = &file_sylphy_openapi_v1_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sylphy.openapi.v1.Operation operation = 500302;
	E_Operation = &file_sylphy_openapi_v1_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional sylphy.openapi.v1.Schema schema = 500303;
	E_Schema = &file_sylphy_openapi_v1_annotations_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sylphy.openapi.v1.Field field = 500304;
	E_Field = &file_sylphy_openapi_v1_annotations_proto_extTypes[3]
)

var File_sylphy_openapi_v1_annotations_proto protoreflect.FileDescriptor

const file_sylphy_openapi_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"#sylphy/openapi/v1/annotations.proto\x12\x11sylphy.openapi.v1\x1a google/protobuf/descriptor.proto\"\xdf\x01\n" +
	"\bDocument\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\aservers\x18\x04 \x03(\v2\x19.sylphy.openapi.v1.ServerR\aservers\x12L\n" +
	"\x10security_schemes\x18\x05 \x03(\v2!.sylphy.openapi.v1.SecuritySchemeR\x0fsecuritySchemes\"<\n" +
	"\x06Server\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xbf\x01\n" +
	"\tOperation\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"deprecated\x18\x04 \x01(\bR\n" +
	"deprecated\x12B\n" +
	"\bsecurity\x18\x05 \x03(\v2&.sylphy.openapi.v1.SecurityRequirementR\bsecurity\"*\n" +
	"\x06Schema\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\"[\n" +
	"\x05Field\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x18\n" +
	"\aexample\x18\x02 \x01(\tR\aexample\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"\xdb\x01\n" +
	"\x0eSecurityScheme\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12@\n" +
	"\vhttp_bearer\x18\x03 \x01(\v2\x1d.sylphy.openapi.v1.HTTPBearerH\x00R\n" +
	"httpBearer\x12G\n" +
	"\x0eapi_key_header\x18\x04 \x01(\v2\x1f.sylphy.openapi.v1.APIKeyHeaderH\x00R\fapiKeyHeaderB\b\n" +
	"\x06scheme\"1\n" +
	"\n" +
	"HTTPBearer\x12#\n" +
	"\rbearer_format\x18\x01 \x01(\tR\fbearerFormat\"&\n" +
	"\fAPIKeyHeader\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\"/\n" +
	"\x13SecurityRequirement\x12\x18\n" +
	"\aschemes\x18\x01 \x03(\tR\aschemes:W\n" +
	"\bdocument\x12\x1c.google.protobuf.FileOptions\x18\xcd\xc4\x1e \x01(\v2\x1b.sylphy.openapi.v1.DocumentR\bdocument:\\\n" +
	"\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xce\xc4\x1e \x01(\v2\x1c.sylphy.openapi.v1.OperationR\toperation:T\n" +
	"\x06schema\x12\x1f.google.protobuf.MessageOptions\x18\xcf\xc4\x1e \x01(\v2\x19.sylphy.openapi.v1.SchemaR\x06schema:O\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xd0\xc4\x1e \x01(\v2\x18.sylphy.openapi.v1.FieldR\x05fieldBT\n" +
	"\x1ccom.github.sylphy.openapi.v1P\x01Z2github.com/sylphylabs/forge/api/openapi/v1;openapib\x06proto3"

var (
	file_sylphy_openapi_v1_annotations_proto_rawDescOnce sync.Once
	file_sylphy_openapi_v1_annotations_proto_rawDescData []byte
)

func file_sylphy_openapi_v1_annotations_proto_rawDescGZIP() []byte {
	file_sylphy_openapi_v1_annotations_proto_rawDescOnce.Do(func() {
		file_sylphy_openapi_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sylphy_openapi_v1_annotations_proto_rawDesc), len(file_sylphy_openapi_v1_annotations_proto_rawDesc)))
	})
	return file_sylphy_openapi_v1_annotations_proto_rawDescData
}

var file_sylphy_openapi_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sylphy_openapi_v1_annotations_proto_goTypes = []any{
	(*Document)(nil),                    // 0: sylphy.openapi.v1.Document
	(*Server)(nil),                      // 1: sylphy.openapi.v1.Server
	(*Operation)(nil),                   // 2: sylphy.openapi.v1.Operation
	(*Schema)(nil),                      // 3: sylphy.openapi.v1.Schema
	(*Field)(nil),                       // 4: sylphy.openapi.v1.Field
	(*SecurityScheme)(nil),              // 5: sylphy.openapi.v1.SecurityScheme
	(*HTTPBearer)(nil),                  // 6: sylphy.openapi.v1.HTTPBearer
	(*APIKeyHeader)(nil),                // 7: sylphy.openapi.v1.APIKeyHeader
	(*SecurityRequirement)(nil),         // 8: sylphy.openapi.v1.SecurityRequirement
	(*descriptorpb.FileOptions)(nil),    // 9: google.protobuf.FileOptions
	(*descriptorpb.MethodOptions)(nil),  // 10: google.protobuf.MethodOptions
	(*descriptorpb.MessageOptions)(nil), // 11: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 12: google.protobuf.FieldOptions
}
var file_sylphy_openapi_v1_annotations_proto_depIdxs = []int32{
	1,  // 0: sylphy.openapi.v1.Document.servers:type_name -> sylphy.openapi.v1.Server
	5,  // 1: sylphy.openapi.v1.Document.security_schemes:type_name -> sylphy.openapi.v1.SecurityScheme
	8,  // 2: sylphy.openapi.v1.Operation.security:type_name -> sylphy.openapi.v1.SecurityRequirement
	6,  // 3: sylphy.openapi.v1.SecurityScheme.http_bearer:type_name -> sylphy.openapi.v1.HTTPBearer
	7,  // 4: sylphy.openapi.v1.SecurityScheme.api_key_header:type_name -> sylphy.openapi.v1.APIKeyHeader
	9,  // 5: sylphy.openapi.v1.document:extendee -> google.protobuf.FileOptions
	10, // 6: sylphy.openapi.v1.operation:extendee -> google.protobuf.MethodOptions
	11, // 7: sylphy.openapi.v1.schema:extendee -> google.protobuf.MessageOptions
	12, // 8: sylphy.openapi.v1.field:extendee -> google.protobuf.FieldOptions
	0,  // 9: sylphy.openapi.v1.document:type_name -> sylphy.openapi.v1.Document
	2,  // 10: sylphy.openapi.v1.operation:type_name -> sylphy.openapi.v1.Operation
	3,  // 11: sylphy.openapi.v1.schema:type_name -> sylphy.openapi.v1.Schema
	4,  // 12: sylphy.openapi.v1.field:type_name -> sylphy.openapi.v1.Field
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	9,  // [9:13] is the sub-list for extension type_name
	5,  // [5:9] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_sylphy_openapi_v1_annotations_proto_init() }
func file_sylphy_openapi_v1_annotations_proto_init() {
	if File_sylphy_openapi_v1_annotations_proto != nil {
		return
	}
	file_sylphy_openapi_v1_annotations_proto_msgTypes[5].OneofWrappers = []any{
		(*SecurityScheme_HttpBearer)(nil),
		(*SecurityScheme_ApiKeyHeader)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sylphy_openapi_v1_annotations_proto_rawDesc), len(file_sylphy_openapi_v1_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_sylphy_openapi_v1_annotations_proto_goTypes,
		DependencyIndexes: file_sylphy_openapi_v1_annotations_proto_depIdxs,
		MessageInfos:      file_sylphy_openapi_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_sylphy_openapi_v1_annotations_proto_extTypes,
	}.Build()
	File_sylphy_openapi_v1_annotations_proto = out.File
	file_sylphy_openapi_v1_annotations_proto_goTypes = nil
	file_sylphy_openapi_v1_annotations_proto_depIdxs = nil
}
